heremaps/harp.gl

- README.md
> Remove acronym description from README

- @here/harp-debug-datasource/lib/DebugTileDataSource.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/UtilsTest.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
Changed the ``zoomLevel`` calculation to align with other map renderers.
> HARP-4900: ZoomLevel alignment.

- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
> HARP-4813: Stable zoom level when view is tilted

- @here/harp-mapview/lib/Tile.ts
> MINOR: Fix memory consumption estimation for arrays of numbers

- @here/generator-harp.gl/generators/app/templates/package.json
- @here/harp-map-theme/package.json
- yarn.lock
> Update to harp-font-resources 0.2.3

- @here/generator-harp.gl/generators/app/templates/package.json
- @here/harp-map-theme/package.json
- yarn.lock
> Upgrade to harp-font-resources 0.2.4

- @here/harp-lines/lib/TriangulateLines.ts
Copy of #284 to retrigger CI job
> HARP-2327: Solid lines have wrong thickness

- .gitignore
- .travis.yml
- @here/generator-harp.gl/generators/app/templates/webpack.config.js
- scripts/test-npm-packages.sh
Test that our main deliverables - npm packages - can be used by
sample apps like ones generated by our app generator.
> HARP-5203: Test for deliverables in npm packages.

- @here/harp-mapview-decoder/test/TileDataSourceTest.ts
- @here/harp-mapview/lib/Tile.ts
Signed-off-by: Stepan <11714928+pit-rpg@users.noreply.github.com>
> HARP-4946: Fix empty Tiles

- .travis.yml
- README.md
- docs/index.html
* Added missing font assets for the example page.
* Fix some broken links.
> Github Page Cleanup.

- @here/harp-examples/webpack.config.js
Signed-off-by: Andrés Valencia Téllez <ext-andres.valencia-tellez@here.com>
> Fixed ViewSource links.

- @here/harp-examples/src/camera_free.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/hello.ts
- @here/harp-examples/src/multiview_triple-view.ts
> HARP-5277 Fix tslint issues

- @here/harp-mapview/lib/poi/PoiTableManager.ts
Signed-off-by: Markus Zell <markus.zell@here.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/345)
> Minor: fix warning for missing POI icon mapping to output icon name

- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
Also fixed missing textures in memory estimation for MeshStandardMaterial
> HARP-5324: Properly dispose textures that are created/owned by Tile

- docs/GettingStartedGuide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/355)
> Minor: fixed typo yeoman call in GettingStartedGuide.md

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/test/OmvDecoderTest.ts
Signed-off-by: Stepan <11714928+pit-rpg@users.noreply.github.com>
> HARP-5043: Add missing techniques on omv-datasource

- .gitignore
> MINOR Adding .vscode to .gitignore

- docs/GettingStartedGuide.md
Fixes typedoc references it has been moved on `github.io` pages in #333
> Fix doc references in Getting Started Guide.

- @here/generator-harp.gl/generators/app/templates/tsconfig.json
- @here/harp-datasource-protocol/tsconfig.json
- @here/harp-debug-datasource/tsconfig.json
- @here/harp-examples/tsconfig.json
- @here/harp-fetch/tsconfig.json
- @here/harp-geojson-datasource/tsconfig.json
- @here/harp-geoutils/tsconfig.json
- @here/harp-lines/tsconfig.json
- @here/harp-lrucache/tsconfig.json
- @here/harp-map-controls/tsconfig.json
- @here/harp-map-theme/tsconfig.json
- @here/harp-mapview-decoder/tsconfig.json
- @here/harp-mapview/tsconfig.json
- @here/harp-materials/tsconfig.json
- @here/harp-omv-datasource/tsconfig.json
- @here/harp-test-utils/tsconfig.json
- @here/harp-text-canvas/tsconfig.json
- @here/harp-transfer-manager/tsconfig.json
- @here/harp-utils/tsconfig.json
- @here/harp-webtile-datasource/tsconfig.json
- tsconfig.json
> HARP-5440: Target es6

- @here/harp-geometry/.gitignore
- @here/harp-geometry/LICENSE
- @here/harp-geometry/README.md
- @here/harp-geometry/index.ts
- @here/harp-geometry/lib/OrientedBox3.ts
- @here/harp-geometry/package.json
- @here/harp-geometry/test/OrientedBox3Test.ts
- @here/harp-geometry/tsconfig.json
Introduce the new module @here/harp-geometry for now containing
only OrientedBox3.
> HARP-5185: Add @here/harp-geometry.

- @here/harp-geometry/lib/SphericalGeometrySubdivisionModifier.ts
- @here/harp-geometry/test/SphericalGeometrySubdivisionModifierTest.ts
- yarn.lock
The SubdivisionModifier is used to increase the number of
vertices of polygons meant to be rendered on a sphere.
> HARP-5189: Add a simple SubdivisionModifier.

- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-mapview/index.ts
- @here/harp-mapview/lib/AnimatedExtrusionHandler.ts
- @here/harp-mapview/lib/DepthPrePass.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-materials/lib/EdgeMaterial.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
- @here/harp-materials/lib/Utils.ts
- @here/harp-utils/index.ts
- @here/harp-utils/lib/Functions.ts
- @here/harp-utils/lib/MathUtils.ts
WIP: working on method that decides which extruded object should be animated and which not.
> HARP-4545: Implement animated extrusion of the buildings

- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json
- @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
Just did `Ctrl+S`. No functional change.
> MINOR: Fix theme indentations.

- .travis.yml
> HARP-5247 Ignore test npm packages for tags

- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
MapViewUtils.estimateMeshSize does not count THREE.Points geometry
and throws thus trows warnings. Extend the mesh size estimation for
THREE.Points instances.
Patch-set fixes also some estimation constants, such as estimated cost
per THREE.Object3d and cost of vertex.
> HARP-5488: Improve mesh size (memory cost) approximation.

- @here/generator-harp.gl/generators/app/templates/index.html
The canvas was not properly scaled to the size of the window b/c the wrong element id was used.
> MINOR: Fixed yeoman template for retina displays

- @here/harp-datasource-protocol/lib/Extruder.ts
- @here/harp-datasource-protocol/lib/Outliner.ts
- @here/harp-datasource-protocol/test/OutlinesTest.ts
- @here/harp-geojson-datasource/lib/GeoJsonGeometryCreator.ts
- @here/harp-geojson-datasource/lib/GeoJsonParser.ts
- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-geojson-datasource/test/GeoJsonTest.ts
- @here/harp-lines/lib/HighPrecisionLines.ts
- @here/harp-lines/lib/HighPrecisionPoints.ts
- @here/harp-lines/lib/HighPrecisionUtils.ts
- @here/harp-lines/lib/Lines.ts
- @here/harp-lines/lib/TriangulateLines.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-materials/lib/DashedLineMaterial.ts
- @here/harp-materials/lib/HighPrecisionLineMaterial.ts
- @here/harp-materials/lib/HighPrecisionPointMaterial.ts
- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts
- @here/harp-omv-datasource/test/OmvDecoderTest.ts
- @here/harp-utils/lib/Math2D.ts
> HARP-5184: Preserve Projected Z-Component.

- @here/harp-examples/src/camera_free.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/datasource_webtile.ts
- @here/harp-examples/src/datasource_xyzmvt.ts
- @here/harp-examples/src/textcanvas_dynamic.ts
- package.json
- typedoc.json
- yarn.lock
* Adapt regex of modules to remove the scope from TypeDoc generation
* Render each module's README for TypeDoc
> HARP-5590 Fix code snippets references in examples

- @here/harp-omv-datasource/lib/OmvDataSource.ts
> HARP-5576: Allow setting of storageLevelOffset at runtime

- @here/harp-geoutils/lib/projection/EquirectangularProjection.ts
- @here/harp-geoutils/lib/projection/IdentityProjection.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/lib/projection/Projection.ts
- @here/harp-geoutils/lib/projection/SphereProjection.ts
> Add APIs to distinguish spherical vs planar projections.

- @here/harp-geoutils/lib/projection/EquirectangularProjection.ts
- @here/harp-geoutils/lib/projection/IdentityProjection.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/lib/projection/Projection.ts
- @here/harp-geoutils/lib/projection/SphereProjection.ts
- @here/harp-geoutils/test/SphereProjectionTest.ts
> Add APIs to get the distance projected points and the surface.

- @here/harp-debug-datasource/lib/DebugTileDataSource.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/425)
> HARP-5576: changed storageLevelOffset to -1

- .travis.yml
- scripts/test-npm-packages.sh
> HARP-5577 Add missing packages to test-npm-packages.

- @here/harp-mapview/lib/VisibleTileSet.ts
> Disable tile wrapping when using spherical projections.

- @here/harp-mapview/lib/VisibleTileSet.ts
Add methods getVisibleTilesForDataSources & computeSubTileArea to reduce
size of updateRenderList.
No functional changes, just moving code around.
> MINOR: Refactoring VisibleTileSet

- @here/harp-mapview/lib/VisibleTileSet.ts
> HARP-5631 Fixing missing tiles during tilting / rotating view

- CODINGSTYLE.md
> Add missing coding style rules from team wiki

- .prettierignore
- @here/harp-datasource-protocol/.gitignore
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-map-theme/resources/berlin_tilezen_base.json
- package.json
- scripts/postinstall.ts
- test/LicenseHeaderTest.ts
- yarn.lock
* re-add postinstall script that calls generate json schema for
@here/harp-datasource-protocol
* (minor) ignore generated files in LicenceCheck
> HARP-4697: Generate theme JSON schema.

- @here/harp-mapview/lib/MapView.ts
> HARP-5401: Add option to set maximum frame rate

- @here/harp-mapview/lib/MapView.ts
> HARP-5672 Updating focal length for fixed FovCalculation

- @here/harp-lines/lib/TriangulateLines.ts
- @here/harp-mapview/lib/Tile.ts
Also added missing generation of normals.
> MINOR: Fixed broken geometry in the extruded-line technique.

- @here/harp-examples/README.md
- @here/harp-examples/src/threejs_add-simple-object.ts
Demo which shows how to add a THREE.js object to the scene and position using RTC (relative to center).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/450)
> HARP-5699 Add simple object demo

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Signed-off-by: ninok <Nino Kettlitz 1396039+ninok@users.noreply.github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/437)
> MINOR: Fixed wrong geometry for extruded polygons.

- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
- @here/harp-mapview/test/ConcurrentWorkerSetTest.ts
* Fix ConcurrentWorkerSet queue draining in case of many aborted
tasks.
* Encapsulate ConcurrentWorkerSet even more and adapt tests.
> HARP-5714: Fix decoder task queue draining with many aborted tasks.

- @here/generator-harp.gl/package.json
- @here/harp-datasource-protocol/package.json
- @here/harp-debug-datasource/package.json
- @here/harp-examples/package.json
- @here/harp-fetch/package.json
- @here/harp-geojson-datasource/package.json
- @here/harp-geometry/package.json
- @here/harp-geoutils/package.json
- @here/harp-lines/package.json
- @here/harp-lrucache/package.json
- @here/harp-map-controls/package.json
- @here/harp-map-theme/package.json
- @here/harp-mapview/package.json
- @here/harp-materials/package.json
- @here/harp-omv-datasource/package.json
- @here/harp-test-utils/package.json
- @here/harp-text-canvas/package.json
- @here/harp-transfer-manager/package.json
- @here/harp-utils/package.json
- @here/harp-webtile-datasource/package.json
See individual commits for details.
> Various package.json fixes

- .travis.yml
Disable the testing of npm packages as it seems it is still broken.
> HARP-5577 Merge deploy steps into the same section.

- .travis.yml
> HARP-5577 Change npm deploy script

- .travis.yml
- scripts/publish-packages.sh
> HARP-5577 Bundle deploy scripts in a file

- .prettierignore
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-examples/src/hello_js-bundle.html
- @here/harp-examples/webpack.config.js
- @here/harp-geojson-datasource/lib/GeoJsonDecoder.ts
- @here/harp-geojson-datasource/lib/GeoJsonGeometryCreator.ts
- @here/harp-mapview-decoder/index.ts
- @here/harp-mapview/index.ts
- @here/harp-mapview/lib/workers/WorkerBootstrapDefs.ts
- @here/harp-mapview/lib/workers/WorkerLoader.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp.gl/.gitignore
- @here/harp.gl/.npmignore
- @here/harp.gl/.yarnrc
- @here/harp.gl/LICENSE
- @here/harp.gl/README.md
- @here/harp.gl/lib/BundleMain.ts
- @here/harp.gl/lib/DecoderBootstrap.ts
- @here/harp.gl/lib/DecoderBundleMain.ts
- @here/harp.gl/lib/index.ts
- @here/harp.gl/package.json
- @here/harp.gl/tsconfig.json
- @here/harp.gl/webpack.config.js
- package.json
* new module - `@here/harp.gl` which provides crucial APIs under  `window.harp`
* WorkerLoader - support for worker scripts bootstrap protocol
* remove Vector3Like duplicate definition from Theme.ts
Note, see `@here/harp-examples/src/hello_js-bundle.html` for sample usage.
> Javascript friendly bundle

- @here/harp-debug-datasource/lib/DebugTileDataSource.ts
Create a line geometry on the surface instead instead of
using the corners of the axis aligned bounding box. Also,
place the text at the center of the Tile when using a non
planar projection.
> HARP-5792: Make the DebugTileDataSource compatible with globe.

- @here/harp-mapview/lib/MapView.ts
> Minor: Improve documentation for raycast

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PickHandler.ts
The ray caster is now setup with the correct camera.
> HARP-5817 Fixing broken picking

- @here/harp-examples/src/datasource_xyzmvt.ts
> Tune the camera pose of the xyzmvt example.

- README.md
> HARP-4670: Change link to gh-pages on README

- @here/harp-geometry/.npmignore
> Minor: add .npmignore to harp-geometry

- @here/harp-examples/README.md
- @here/harp-examples/src/threejs_raycast.ts
> HARP-5699 Adding three.js raycast demo

- @here/harp-datasource-protocol/index.ts
- @here/harp-datasource-protocol/lib/PostEffects.ts
- @here/harp-examples/README.md
- @here/harp-examples/src/effects_all.ts
- @here/harp-examples/src/effects_themes.ts
- @here/harp-examples/src/hello.ts
- @here/harp-examples/src/themes.ts
- @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json
- @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json
- @here/harp-map-theme/resources/effects_outlines.json
- @here/harp-map-theme/resources/effects_streets.json
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/composing/MapRenderingManager.ts
- @here/harp-mapview/lib/composing/Outline.ts
- @here/harp-mapview/lib/composing/Pass.ts
- @here/harp-mapview/lib/composing/UnrealBloomPass.ts
- @here/harp-materials/index.ts
- @here/harp-materials/lib/LuminosityHighPassShader.ts
- @here/harp-materials/lib/SepiaShader.ts
- @here/harp-materials/lib/VignetteShader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/446)
> HARP-5679: More textures + introduce posteffects.

- @here/harp-map-theme/resources/berlin_tilezen_base.json
> HARP-5898: Updated berlin_tilezen_base.json

- @here/harp-map-controls/lib/MapControlsUI.ts
Signed-off-by: Stepan Krovspei <ext-stepan.krovspei@here.com>
Signed-off-by: Stepan <ext-stepan.krovspei@here.com>
> MINOR: added dispose method for preventing memory leaks

- @here/harp-examples/src/effects_all.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
> HARP-5954: MapView effects examples are flickering on MacBook pro

- @here/harp-map-controls/lib/MapControls.ts
> HARP-6000: Fix mouseUp handling in cross-origin iframes.

- @here/harp.gl/README.md
- typedoc.json
* Exclude harp.gl bundle doc from official doc.
* Fix links in harp.gl README
> Doc tweaks.

- @here/harp-examples/src/threejs_add-simple-object.ts
> Minor: Adding object requires ctrl + click

- @here/harp-examples/src/threejs_add-animated-object.ts
- @here/harp-examples/src/threejs_add-simple-object.ts
- @here/harp-mapview/lib/MapView.ts
> HARP-5710: Add trackable user MapObjects to MapView

- @here/harp-mapview/lib/MapView.ts
> HARY-5710: Fix documentation typos

- @here/harp-examples/src/threejs_add-simple-object.ts
- @here/harp-examples/src/threejs_raycast.ts
> Minor: Fixing click to add cube

- @here/harp-geoutils/lib/projection/EquirectangularProjection.ts
- @here/harp-geoutils/lib/projection/IdentityProjection.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/lib/projection/Projection.ts
- @here/harp-geoutils/lib/projection/SphereProjection.ts
- @here/harp-geoutils/test/ProjectionTest.ts
Also, make Projection an abstract class and a default
implementation of reprojectPoint.
> HARP-5937: Add APIs to reproject world coordinates.

- CODINGSTYLE.md
> Fix formatting in coding style doc.

- @here/harp.gl/lib/BundleMain.ts
> Fix decoder url detection for tiler in harp.js bundle.

- @here/harp-examples/src/techniques_interpolation.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
Signed-off-by: Oleksii Kanishchev <ext-oleksii.kanishchev@here.com>
> HARP-5883: Interpolation of colors with zoom levels does not work

- @here/harp-examples/src/camera_orbit.ts
- @here/harp-mapview/lib/MapView.ts
Azimuth screwed up in examples.
> MINOR: Fix azimuth in examples.

- @here/harp-examples/src/hello.ts
> MINOR: Make hello example great again

- @here/harp-geojson-datasource/lib/GeoJsonDataProvider.ts
- @here/harp-mapview/lib/MapView.ts
> Add clarification note to API

- docs/docs/index.html
- docs/examples/index.html
This enables https://harp.gl/examples to redirect to examples page
> add redirect from harp.gl/examples

- @here/harp-mapview-decoder/lib/TileDataSource.ts
> HARP-6101 Adding clear method to DataSource

- @here/harp.gl/lib/index.ts
> HARP-6075: Expose all MapView exports in harp.js bundle

- @here/harp-geojson-datasource/lib/GeoJsonDataProvider.ts
> MINOR: Fix spelling

- @here/harp-mapview/lib/MapView.ts
Signed-off-by: Oleksandr Buzin <ext-oleksandr.buzin@here.com>
> HARP-5950: Increase cache limit values

- @here/harp-mapview/lib/MapView.ts
> MINOR: Improve documentation of FovCalculation

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-geoutils/lib/projection/EquirectangularProjection.ts
- @here/harp-geoutils/lib/projection/IdentityProjection.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/lib/projection/Projection.ts
- @here/harp-geoutils/lib/projection/SphereProjection.ts
- @here/harp-geoutils/lib/tiling/HereTilingScheme.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> HARP-6060 Introducing scale to convert from unit to world coordinates

- README.md
> Minor: change name of link

- .github/stale.yml
> Minor: add stale configuration for probot

- @here/harp-geoutils/lib/projection/EquirectangularProjection.ts
- @here/harp-geoutils/test/ProjectionTest.ts
- @here/harp-geoutils/test/TileKeyTest.ts
> HARP-6060 Fix incorrect equirectangular projection

- @here/harp-datasource-protocol/README.md
Signed-off-by: Oleksii Kanishchev <49714978+okanishchev@users.noreply.github.com>
> MINOR: supply harp-datasource-protocol typedoc with technique links

- README.md
- docs/GettingStartedGuide.md
- </cavas> is add
- authentication code is noted.
-----
Note, every developer need to trade in birthday to get authentication code. Is it a common practice?
> Update Readme.md and GetstartedGuide.md

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
Added possibility to use all integer types for attributes, either normalized or not.
> Added possibility to use all integer types for attributes.

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryManager.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-omv-datasource/lib/OmvDataFilter.ts
- @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/OmvDecoderDefs.ts
- @here/harp-omv-datasource/test/OmvTest.ts
> HARP-6162: Add phased loading and geometry filtering by kind

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
* [contribution guidelines](../CONTRIBUTING.md)
* [coding style](../CODINGSTYLE.md)
And please do not forget to sign-off your commit! You …
> HARP-6420: Fix multiple generation of geometry in phased loading

- @here/generator-harp.gl/generators/app/templates/package.json
- @here/harp-examples/webpack.config.js
- @here/harp-map-theme/package.json
- @here/harp-map-theme/scripts/prepack.ts
- @here/harp-text-canvas/test/FontCatalogTest.ts
- @here/harp-text-canvas/test/TextCanvasTest.ts
- README.md
- webpack.tests.config.js
- yarn.lock
> HARP-5596 Use new fontcatalog

- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
Signed-off-by: Oleksii Kanishchev <49714978+okanishchev@users.noreply.github.com>
Simply clearing tile loader cache when mapview tile cache is being cleared.
> HARP-6181: Zombie Level [0...3] Tiles

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
Signed-off-by: Oleksii Kanishchev <49714978+okanishchev@users.noreply.github.com>
> HARP-6436: POI and transport icons are missing for all data souces

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/test/ExprTest.ts
* [contribution guidelines](../CONTRIBUTING.md)
* [coding style](../CODINGSTYLE.md)
And please do not forget to sign-off your commit! You can read more about DCO …
> Fix length semantics

- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
> HARP-6453 Remove obsolete toString from enum call

- .github/pull_request_template.md
> Fix links for PR templates

- @here/harp-examples/src/elevationprovider.ts
- @here/harp-mapview/lib/ElevationProvider.ts
> HARP-6410 Rename getTilingSceme to getTilingScheme

- @here/harp-geometry/test/OrientedBox3Test.ts
- @here/harp-geoutils/test/ProjectionTest.ts
- @here/harp-omv-datasource/test/OmvTomTomFeatureModifierTest.ts
- test/LicenseHeaderTest.ts
> HARP-6492: Move unit tests setup code to 'before' functions.

- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
* Labels can now be hidden and disabled
* Added option to disable phased loading
* [contribution guidelines](../CONTRIBUTING.md)
* [coding style](../CODINGSTYLE.md) …
> HARP-6418: Fix label filtering

- @here/harp-examples/src/datasource_features_lines+points.ts
Team,
Y'all need to learn how to spell
-Ignacio
> MINOR: fix typo on hotspots example

- CODINGSTYLE.md
> MINOR: Fix coding style to mention undefined

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/test/ExprTest.ts
https://github.com/heremaps/harp.gl/pull/633#issue-298467743
> MapEnv: Don't expose properties inherited from prototype.

- @here/harp-mapview-decoder/lib/TileLoader.ts
- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
- @here/harp-mapview/lib/WorkerBasedDecoder.ts
- @here/harp-mapview/lib/WorkerBasedTiler.ts
> HARP-6503: Fix MapView.dispose

- @here/harp-examples/example-browser.ts
> MINOR: Fixing run time undefined access

- README.md
- docs/GettingStartedGuide.md
- docs/css/index.css
- docs/index.html
- Minor code improvements to getting started code in `README.md`
- Window resize and starting location added to `GettingStartedGuide.md`
- Add tutorial to website navigation
> MINOR: Improve getting started documentation and add tutorial to website

- @here/harp-map-controls/lib/MapControls.ts
:warning: Two current limitations visible in this PR in globe, are no inertia and zooming at the center of the screen only. This is a larger limitation of globe handling in MapControls, that will be addressed in separate PRs.
> HARP-6006: Zoom on double click / tap.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
> HARP-6622: Fix z-fighting for background planes.

- docs/index.html
> HARP-6654: Stick to three.js 0.105 for the harp.gl landing page

- @here/harp-mapview/lib/FrustumIntersection.ts
> MINOR: Removed usage of chai.assert

- @here/harp-examples/src/getting-started_free-camera.ts
This includes:
- displaying camera frustum,
- rendering camera transformation gizmo,
- adding support for camera angles constraints. …
> HARP-5995: Fix free camera example.

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-datasource-protocol/lib/TileInfo.ts
- @here/harp-datasource-protocol/test/TileInfoTest.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-geojson-datasource/lib/GeoJsonGeometryCreator.ts
- @here/harp-geojson-datasource/lib/GeoJsonParser.ts
- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts
HARP-5144, HARP-6565, Picking implemented for OMV data source,
fixed issues with road and label picking.
> HARP-5144: Add picking for omv-datasource

- @here/harp-examples/README.md
> MINOR: Fix examples' README links.

- @here/harp-examples/src/datasource_geojson_styling_game.ts
Fix build regression introduced by merging #581
> HARP-5945: Fix typings in examples.

- @here/harp-map-controls/package.json
> MINOR: Added @types/tween.js as dependency for typescript users of harp

- @here/harp-mapview/lib/MapView.ts
> HARP-6379: Camera change interception/hooks

- @here/harp-test-utils/lib/TestUtils.ts
> HARP-6635 Throw an error if waits for event

- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-map-theme/package.json
- @here/harp-map-theme/resources/berlin_derived.json
- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-map-theme/resources/berlin_tilezen_base_globe.json
- @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json
- @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
- @here/harp-map-theme/test/DefaultThemeTest.ts
- webpack.tests.config.js
- yarn.lock
* fix `SelectorValueDefinition.value` typing to contain expressions
* add test for Berlin theme validity against generated JSON schema
* fix berlin themes to comply with schema
> HARP-732: Automatic tests for berlin themes against json schema.

- @here/harp-geojson-datasource/test/GeoJsonTest.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/test/ProjectionTest.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
> HARP-6585 Fix incorrect projectBox function

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
* [contribution guidelines](../CONTRIBUTING.md)
* [coding style](../CODINGSTYLE.md)
And please do not forget to sign-off your commit! You can read more about DCO …
> HARP-5782: Camera clipping planes evaluators

- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
> HARP-6727: Fix filtering of geometry kinds in SimpleTileGeometryManager

- @here/harp-mapview/lib/MapView.ts
> HARP-6736: Enable WebGLPowerPreference im MapView

- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-examples/src/elevation-provider.ts
- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-mapview-decoder/test/TileDataSourceTest.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryManager.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
- @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/OmvDecoderDefs.ts
- @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
Overlay of areas over terrain using vertex displacement maps.
Add DisplacementFeature to MapMeshBasicMaterial, and include the displacement map vertex
shader chunk to its shader.
Change FillTechnique to generate vertex normals and texture coordinates.
> Harp 5728 area overlay

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
This improves TiltBasedClipPlanesEvaluator with equations that supports
camera tilt and yaw.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on …
> HARP-5782: Clipping planes evaluation for spherical projection with tilt.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
> HARP-6646: Render text outline when background is opaque

- @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts
MINOR: added id property to user data in VTJsonDataAdapter
> MINORL: added id property to user data in VTJsonDataAdapter

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Add a naive visitor that searches for usages of
`["==", ["get", "$layer"], "some layer name"]` inside ["all, e1, ...eN]
expressions. When such usages are found the requested layer name
is stored in the `_layer`  member of `StyleInternalParams` and it used
to filter the evaluation of the conditions that need to be checked
by `getMatchingTechniques`.
Also, compile the style conditions when the StyleSetEvaluator is
constructed instead of lazily compile the expressions before
evaluating them.
> HARP-6782: Use the requested $layer to speed up StyleSetEvaluator.

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-6434: Apply label's opacity coming from the theme

- .github/workflows/ci.yml
basic test and build on a matrix configuration of node.js versions and OS
> Create basic CI with github actions

- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
Signed-off-by: bohdanhorpynchuk <ext-bogdan.gorpynchuk@here.com>
> HARP-6605: Added MapView map wrapping param support.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
> HARP-6646: Draw label outline when backgroundSize is set

- @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts
> HARP-6801: Fix rgb format output color result in themes

- @here/harp-examples/src/elevation-provider.ts
- @here/harp-mapview/lib/DisplacementMap.ts
- @here/harp-mapview/lib/ElevationProvider.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
> HARP-5728: Move displacement map texture creation to TileGeometryCreator.

- @here/harp-mapview/lib/AnimatedExtrusionHandler.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryManager.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-mapview/lib/poi/PoiTableManager.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-6636: MapView.FrameComplete event is broken

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
This allows to define maximum and minimum elevation on the ground that
should be covered by camera frustum, giving handy the interface for
terrain and elevation support.
Our bots will check whether your PR can be directly …
> HARP-6270: ClipPlanesEvaluators support for elevation constraints.

- @here/harp-mapview/lib/MapView.ts
> HARP-6729: Disable MSAA for high pixelRatio devices.

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> Minor: Polygon outline bugfix.

- @here/harp-lines/lib/Lines.ts
- @here/harp-lines/package.json
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
- Add texture coordinates and normals to line geometry.
- Change line shader to use displacement map.
> HARP-6718: Overlay lines on terrain.

- @here/harp-mapview/lib/DepthPrePass.ts
> HARP-6877: Update DepthPrePass stencil to match three 107.

- @here/harp-examples/example-browser.ts
- @here/harp-examples/index.html
- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-examples/src/datasource_geojson_chloropleth.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/datasource_xyzmvt.ts
- @here/harp-examples/src/getting-started_free-camera.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-examples/src/styling_extend-a-theme.ts
- @here/harp-examples/src/styling_textured-areas.ts
- @here/harp-examples/src/synchronized-views.ts
- @here/harp-examples/src/textcanvas.ts
- @here/harp-examples/template/example.html
- docs/index.html
- docs/js/index.js
This PR fixes a bunch of examples and makes the navigation panel always collapsible so that the example is fullscreen.
> HARP-6551: Examples fixing and refinements.

- @here/harp-examples/lib/PerformanceConfig.ts
- @here/harp-examples/lib/PerformanceUtils.ts
- @here/harp-examples/package.json
- @here/harp-examples/src/performance_benchmark.ts
- @here/harp-examples/webpack.config.js
- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Statistics.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/WorkerBasedDecoder.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-5222: Implement performance tests in the browser

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
> Minor: Enable GroundPlane depth write.

- .github/workflows/ci-macos.yaml
- .github/workflows/ci.yml
- package.json
> Update minimum engine version to node 10.x and update Github CI action

- @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json
- @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json
- @here/harp-map-theme/test/DefaultThemeTest.ts
- @here/harp-test-utils/lib/TestDataUtils.web.ts
- package.json
- webpack.tests.config.js
- yarn.lock
Followup of #691 
* Fix and and add effects themes to tests
* Fix test copying code
> Fix theme validation tests in browser.

- @here/generator-harp.gl/generators/app/templates/tsconfig.json
- @here/harp-atlas-tools/tsconfig.json
- @here/harp-datasource-protocol/tsconfig.json
- @here/harp-debug-datasource/tsconfig.json
- @here/harp-examples/tsconfig.json
- @here/harp-features-datasource/tsconfig.json
- @here/harp-fetch/tsconfig.json
- @here/harp-geojson-datasource/tsconfig.json
- @here/harp-geometry/tsconfig.json
- @here/harp-geoutils/tsconfig.json
- @here/harp-lines/tsconfig.json
- @here/harp-lrucache/tsconfig.json
- @here/harp-map-controls/tsconfig.json
- @here/harp-map-theme/tsconfig.json
- @here/harp-mapview-decoder/tsconfig.json
- @here/harp-mapview/tsconfig.json
- @here/harp-materials/tsconfig.json
- @here/harp-omv-datasource/tsconfig.json
- @here/harp-test-utils/tsconfig.json
- @here/harp-text-canvas/tsconfig.json
- @here/harp-transfer-manager/tsconfig.json
- @here/harp-utils/tsconfig.json
- @here/harp-webtile-datasource/tsconfig.json
- @here/harp.gl/tsconfig.json
- tsconfig.json
> HARP-6802: ES2017 TS target.

- @here/harp-datasource-protocol/package.json
- @here/harp-debug-datasource/package.json
- @here/harp-examples/package.json
- @here/harp-features-datasource/package.json
- @here/harp-geojson-datasource/package.json
- @here/harp-geometry/package.json
- @here/harp-lines/package.json
- @here/harp-map-controls/package.json
- @here/harp-mapview/lib/composing/Outline.ts
- @here/harp-mapview/package.json
- @here/harp-materials/package.json
- @here/harp-omv-datasource/package.json
- @here/harp-text-canvas/package.json
- @here/harp-webtile-datasource/package.json
- @here/harp.gl/package.json
- docs/index.html
- package.json
- yarn.lock
> HARP-6996: Upgraded to three@0.108.0.

- .github/workflows/ci-macos.yaml
- .github/workflows/ci.yml
> Run github CI only for push on master

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
- @here/harp-mapview/lib/WorkerBasedDecoder.ts
- @here/harp-mapview/lib/WorkerBasedTiler.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
> HARP-6123: ServiceType failed connection logs.

- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
> Harp 6905: Use maximum view range for features fading calculus.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
* Fixes HARP-6858: City centers / countries flicker at end of panning
* Also fixes many occasions of general flickering of point labels
Our bots will check whether your PR can be directly integrated into the mainline. We …
> HARP-6843: Labels disappear after initial load

- @here/harp-examples/src/rendering_synchronous.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-6378: Synchronous rendering

- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryManager.ts
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-utils/lib/GroupedPriorityList.ts
- Overlaid text geometry is updated back in the tile.
- Overlay of labels in a file is spread through 60 frames.
> HARP-6512: Label elevation overlay.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
> HARP-6899: Fix the creation of tiny labels for jaggy rivers

- test/ImportTest.ts
* Read `package.json` files each test, so --watch mode works
* Increase timeout as sometimes we exceed 2s default
> Importcheck test

- @here/harp-mapview/lib/MapView.ts
> HARP-6336: Disappearing tiles on language switch fix.

- @here/harp-mapview/lib/MapView.ts
Fixes `FrameComplete` event for "text-less" themes.
TODO:
Followup of this disccusion: https://github.com/heremaps/harp.gl/pull/724#discussion_r314356473
> Fix first frame complete for themes without text.

- @here/harp-omv-datasource/lib/OmvData.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts
- @here/harp-omv-datasource/lib/OmvUtils.ts
- @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts
- @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
> HARP-6058: Fix GeoJSON lat2tile computation.

- @here/harp-datasource-protocol/index-decoder.ts
- @here/harp-datasource-protocol/lib/ThreeBufferUtils.ts
- @here/harp-examples/README.md
- @here/harp-examples/decoder/custom_decoder.ts
- @here/harp-examples/decoder/custom_decoder_defs.ts
- @here/harp-examples/decoder/decoder.ts
- @here/harp-examples/package.json
- @here/harp-examples/src/datasource_custom.ts
- @here/harp-omv-datasource/lib/IGeometryProcessor.ts
Following features are showcased:
* Usage of the styling engine in a custom datasource
* Decoding and processing in a web-worker
* Creation of three.js objects in a web-worker
> HARP-6948: Added advanced custom datasource example

- .github/workflows/ci-linux.yaml
Align naming with other actions
> Minor: update name of action for Linux

- @here/harp-mapview/lib/MapView.ts
Fixing default value in the documentation for the previous PR https://github.com/heremaps/harp.gl/pull/816
> HARP-7113: Fix docs (minor)

- @here/harp-datasource-protocol/lib/TileInfo.ts
- @here/harp-examples/src/datasource_object-picking.ts
HARP-5144: added picking examples for polygons, lines, labels, POIs
HARP-7129:  fix DataCloneError
> HARP-5144: added picking examples for polygons, lines, labels, POIs

- @here/harp-datasource-protocol/lib/operators/ObjectOperators.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
> MINOR: Add support for dynamic member names to get and has.

- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
HARP-7257: line cups on sharp edges fix
MINOR: +material update
> HARP-7257: line cups on sharp edges fix

- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> Minor: Fix extrusion visual bug.

- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
Fix for transparent lines with line caps. …
> MINOR: Line caps fix

- @here/harp-examples/src/datasource_features_polygons.ts
- @here/harp-geoutils/lib/projection/EarthConstants.ts
- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
> Harp-6270: Gather tiles elevation, store their min/max and update clip planes.

- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> Minor: Increased MIN_BUILDING_HEIGHT.

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-datasource-protocol/lib/WorkerServiceProtocol.ts
- @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
- @here/harp-map-theme/test/DefaultThemeTest.ts
- @here/harp-mapview-decoder/lib/WorkerService.ts
- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
- @here/harp-mapview/test/ConcurrentWorkerSetTest.ts
Minor improvements and fixes in expression handling
- Fix support for interpolators in technique attributes and definitions.
- developer experience: Pass error stacks for exceptions in workers.
- check that references and expressions are valid in theme
> HARP-7103 Fix support for interpolators in technique attributes and definitions.

- @here/harp-omv-datasource/test/MapViewPickingTest.ts
> Skip flaky picking tests

- @here/harp-mapview/lib/MapView.ts
> HARP-6716: MapView exposes phased loading settings.

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-datasource-protocol/lib/TechniqueAttr.ts
Graceful handling of and errors in expressions.
* Handle, log and evaluate to null/undefined and errors detected while
evaluating expressions.
* Coerce nulls into undefineds after Expr evaluation.
> Graceful handling of and errors in expressions.

- @here/harp-datasource-protocol/README.md
- @here/harp-examples/README.md
Change all links to be absolute
Resolves #588
> HARP-5701 Fix dead links of documentation

- docs/index.html
- docs/js/index.js
Marketing pointed out broken copyright on harp.gl site
> Update copyright year

- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts
- @here/harp-datasource-protocol/lib/TechniqueAttr.ts
- @here/harp-datasource-protocol/test/InterpolationTest.ts
This reverts commit d7a625f3de2574901580a0ffe5d8a34759545bc1.
> Revert "HARP-6527: Support discrete interpolators of arbitrary types."

- @here/harp-examples/src/styling_textured-areas.ts
> HARP-7431 Fixing resource locations

- @here/harp-lrucache/lib/LRUCache.ts
- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
> HARP-7292: Improve tile cache use.

- @here/harp-mapview/lib/MapView.ts
> HARP-6724: removed unused code block

- @here/harp-lines/lib/Lines.ts
Do math once for both vertices added in `addVertexPair`.
Measured 30-40% better throughput of `createLineGeometry`.
> createLineGeometry optimized.

- @here/harp-text-canvas/lib/typesetting/LineTypesetter.ts
- @here/harp-text-canvas/test/TextCanvasTest.ts
> HARP-7118: "wrappingMode": "Word" - fix line breaks inside words

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-text-canvas/lib/rendering/TextGeometry.ts
Disabling frustumCulling in favor of VisibleTileTree. …
> HARP-7296: Disabling frustumCulling

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
> HARP-7413: Add APIs to get the dependencies of an expression

- README.md
Match years shown in header of code
> Minor change copyright year

- @here/harp-lrucache/lib/LRUCache.ts
- @here/harp-lrucache/test/LRUCacheTest.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
> Harp-7292: All data sources utilizes single cache for tiles.

- @here/harp-omv-datasource/lib/OmvRestClient.ts
- @here/harp-omv-datasource/test/OmvRestClientTest.ts
> HARP-7392 Add urlParams to OmvRestClient

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/OmvUtils.ts
- @here/harp-test-utils/lib/ProfileHelper.ts
- test/performance/OmvDecoderPerformanceTest.ts
Optimize tile2world.
80% of math in tile2world and world2tile is constant in scope of tile.
> Tile2world & world2tile - decoding optimization.

- @here/harp-mapview/lib/VisibleTileSet.ts
> Harp-7292: Single cache with morton code and offset used in tile identifier.

- @here/harp-examples/src/elevation-provider.ts
- @here/harp-examples/src/getting-started_free-camera.ts
- @here/harp-examples/src/styling_interpolation.ts
- @here/harp-examples/src/synchronized-views.ts
- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-map-controls/lib/MapControlsUI.ts
- @here/harp-mapview/lib/CameraMovementDetector.ts
- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewFog.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/UtilsTest.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
> HARP-5347: Compass button.

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/lib/ExprEvaluator.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
> Restrict the type of JsonExpr

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Move computeDefaultRenderOrder and resolveStyleReferences.
> Simplify the StyleSetEvaluator constructor.

- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts
- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-datasource-protocol/lib/TechniqueAttr.ts
- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
- @here/harp-datasource-protocol/test/InterpolationTest.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
> Removed unused template parameter

- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-geojson-datasource/test/GeoJsonTest.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
* Fix wrong calculation of icon size
* Fix wrong handling of dynamic string properties that are not numeral
* Added interpolation to following properties:
* xOffset
*  yOffset
* iconXOffset
* iconYOffset
* screenWidth
* screenHeight
* vAlignment
* hAlignment
> HARP-7322: City center fixes

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-geojson-datasource/lib/GeoJsonDecoder.ts
- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PathBlockingElement.ts
- @here/harp-mapview/lib/ScreenCollisions.ts
- @here/harp-mapview/lib/ScreenProjector.ts
- @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/ScreenCollisionsTest.ts
- @here/harp-mapview/test/ScreenProjectorTest.ts
- @here/harp-mapview/test/TileGeometryCreatorTest.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Change-Id: Id2fb88f842fa6d6b4d8da49860760074e1043936 Signed-off-by:
Jonathan Stichbury <2533428+nzjony@users.noreply.github.com>
> HARP-7419 Adding technique for world space line to block screen space labels.

- @here/harp-mapview-decoder/lib/GeoJsonTiler.ts
- @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts
> HARP-7194: Fixed tiled geojson picking.

- package.json
- yarn.lock
> Minor: Bump chromedriver to 77.0.0

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
Hide label outline if outline size is set to 0
> HARP-7143: Label outlines are visible even if the outline size is set to 0

- @here/harp-mapview/lib/MapView.ts
> HARP-6636: Fix MapView.FrameComplete event

- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-map-controls/test/MapControlsTest.ts
This PR implements screen-space rotations when interacting with touches on the globe. World space rotation is maintained for flat projections.
> HARP-7586: Fix touch rotation in globe.

- @here/harp-mapview/lib/MapView.ts
That commit caused the regression described in HARP-7652.
This reverts commit 46b8f8f2fb92c57eaaae19240d5e0293e250a633.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you …
> HARP-7652: Revert "HARP-6636: MapView.FrameComplete event"

- @here/harp-datasource-protocol/package.json
- @here/harp-debug-datasource/package.json
- @here/harp-examples/package.json
- @here/harp-features-datasource/package.json
- @here/harp-geojson-datasource/package.json
- @here/harp-geometry/lib/SubdivisionModifier.ts
- @here/harp-geometry/package.json
- @here/harp-geoutils/package.json
- @here/harp-lines/package.json
- @here/harp-map-controls/package.json
- @here/harp-mapview/lib/poi/BoxBuffer.ts
- @here/harp-mapview/package.json
- @here/harp-materials/package.json
- @here/harp-omv-datasource/package.json
- @here/harp-text-canvas/package.json
- @here/harp-webtile-datasource/package.json
- @here/harp.gl/package.json
- docs/index.html
- package.json
- test/performance/package.json
- yarn.lock
> HARP-7639: Update ThreeJS to r109.

- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
Did some changes to the line shader needed for future line animations tickets:
> Minor: Cleaned-up line shader.

- @here/harp-map-theme/resources/berlin_tilezen_base.json
Brings back animation extrusion for the buildings in the main theme.
> MINOR: Bring buildings extrusion animation back.

- @here/harp-mapview/lib/DepthPrePass.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
> MINOR: Make the console enjoy the sound of silence.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/poi/PoiTableManager.ts
- @here/harp-utils/lib/Logger/LoggerManagerImpl.ts
- @here/harp-utils/test/LoggerManagerTest.ts
Softer alternative to silence the console. Warnings are still there in dev, they indicate an issue that should be fixed another way I guess.
> MINOR: Make logging great again.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
> MINOR: Fix setCameraGeolocationAndZoom.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
Fixed map crashing when the theme was switched. …
> HARP-7365: Theme switching bug fix.

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
The bug could cause margin to be applied (as ration) based on negative or
zero near distance - before clamping.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration …
> MINOR: Fix clip planes clamping before applying margins.

- @here/harp-map-theme/package.json
- yarn.lock
> Minor: Bumped font-catalog to 0.1.2.

- @here/harp-map-theme/resources/poi_table_maki.json
Fix the warnings from the maki table.
> MINOR: Fix Maki icon warnings.

- @here/harp-examples/src/getting-started_open-sourced-themes.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-examples/src/rendering_post-effects_all.ts
- @here/harp-examples/src/styling_extend-a-theme.ts
- @here/harp-examples/src/synchronized-views.ts
We always display Berlin and New York. Our data allows displaying other nice places though. The two hello world examples remain on New York (and so do examples extending it), the camera animations example is on Berlin, but this PRs varies the locations of other examples, showcasing: Rome, Moscow, Singapour, Frankfurt and Dubai.
> MINOR: Vary locations displayed in the examples.

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
> HARP-7560: Added secondaryCaps support.

- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Fixes the building animation going through the ground.
> MINOR: Fix the building animation going through ground.

- @here/harp-datasource-protocol/index-decoder.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-lines/lib/Lines.ts
- @here/harp-mapview-decoder/lib/GeoJsonTiler.ts
- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-omv-datasource/lib/IGeometryProcessor.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts
* PR addressing animation of lines using ``SolidLineMaterial.drawRange``.
* Also addressed line joining for smooth animations when using ``GeoJsonDataProvider``.
Depends on #885
> HARP-7204: Implemented animated lines.

- @here/harp-lines/package.json
- @here/harp-lines/test/rendering/RenderLines.ts
- @here/harp-test-utils/index.ts
- @here/harp-test-utils/index.web.ts
- @here/harp-test-utils/lib/rendering/DomImageUtils.ts
- @here/harp-test-utils/lib/rendering/DomReporter.ts
- @here/harp-test-utils/lib/rendering/FeedbackCli.ts
- @here/harp-test-utils/lib/rendering/FeedbackCommon.ts
- @here/harp-test-utils/lib/rendering/FeedbackServer.ts
- @here/harp-test-utils/lib/rendering/FeedbackServerReporter.ts
- @here/harp-test-utils/lib/rendering/HtmlReport.ts
- @here/harp-test-utils/lib/rendering/ImageBasedTestHelper.ts
- @here/harp-test-utils/lib/rendering/ImageLocator.ts
- @here/harp-test-utils/lib/rendering/Interface.ts
- @here/harp-test-utils/lib/rendering/Magnifier.ts
- @here/harp-test-utils/package.json
- @here/harp-text-canvas/package.json
- @here/harp-text-canvas/test/rendering/TextCanvasRenderingTest.ts
- @here/harp-utils/package.json
- @here/harp-utils/test/PerformanceTimerTest.ts
- package.json
- test/rendering.html
- test/rendering/GeoJsonDataRendering.ts
- test/rendering/package.json
- test/resources/basic_polygon.json
- webpack.tests.config.js
Signed-off-by: Arkadiusz Spiewak <ext-arkadiusz.spiewak@here.com> …
> HARP-7582 Move IBCT utils to /coresdk

- @here/harp-atlas-tools/package.json
> HARP-7789 Fixing incorrect package step

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
So far we were looping through all remaining text element groups even if
we didn't place any additional label.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration …
> MINOR: Skip remaining text element groups when placement limit reached.

- @here/harp-omv-datasource/lib/OmvDataSource.ts
- Users should either supply OmvRestClientParameters or a DataProvider
instance
> HARP-7677: Remove another unsupported OmvDataSourceParameter

- @here/harp-mapview/lib/ThemeLoader.ts
> Minor: Disabled dashed-line deprecation warning.

- @here/harp-examples/lib/PerformanceUtils.ts
- @here/harp-mapview/lib/Utils.ts
Change-Id: I5f759ee4fb2e9650494b7e37205cf47c546b713b
> HARP-7808 Moving function to check if map is loading

- test/performance.html
Signed-off-by: Arkadiusz Spiewak <ext-arkadiusz.spiewak@here.com> …
> Minor: Fix missing performance.html warning while building the tests

- @here/harp-mapview/lib/BackgroundDataSource.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
Note, this introduces a regression, which will be fixed by introducing
clipping planes (follow up PR)
Change-Id: I0d96b10242b133f8d8bdbf6a187e04d444b28886
> HARP-7808 Fallback has render order.

- package.json
- yarn.lock
Signed-off-by: Marcel Pursche marcel.pursche@here.com …
> HARP-7629 Updated chromedriver for Chrome 78

- @here/harp-examples/src/rendering_synchronous.ts
> HARP-7711 Changed zoom level in synchronous rendering example to display buildings

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
Change-Id: I90ed4a795f01a02308697874d044bf5485b83d77
> HARP-7808 Clip polygons

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-7373: Remove placement functions dependency from MapView.

- @here/harp-examples/lib/PerformanceConfig.ts
- @here/harp-examples/src/performance_benchmark.ts
> HARP-7916: Add flyover over NY at ZL17 in performance benchmark.

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
Pass to addPointLabel the index of the icon to be placed within the
line marker.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the …
> HARP-7373: Fix line marker labels.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
> HARP-7699: Fix animateExtrusion property handling

- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts
- @here/harp-datasource-protocol/test/StringDecodersTest.ts
> HARP-7904: Restrict string encoded literals

- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts
- @here/harp-omv-datasource/lib/OmvUtils.ts
> HARP-7373: Decode text geometries coordinates in world space.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
Don't apply the clippingPlanes if the projection is not planar.
> HARP-7808 Fix globe polygons not rendering

- @here/harp-map-theme/package.json
- yarn.lock
> Bump fontcatalog version

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
The improved approach compares tangent line angle with actual camera FOV,
if the second angle is smaller then we calculate frustum side (top/right)
planes intersection with globe.
For now only TopViewClipPlaneEvaluator is improved.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests for …
> MINOR: Optimize frustum far plane calculus for globe projections.

- @here/harp-debug-datasource/lib/DebugTileDataSource.ts
Now text elements get coordinates in world space. …
> MINOR: Fix tile key labels created by DebugTile.

- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> Harp 7916 skip new labels pass if no update

- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/RenderState.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementState.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-7916: Remove/speed up frequently used getters.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/poi/PoiRendererFactory.ts
- @here/harp-mapview/lib/text/TextCanvasFactory.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
Move construction of TextCanvas and PoiRenderer out from
TextElementsRenderer. …
> HARP-7373: Add TextCanvasFactory and PoiRendererFactory.

- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-7373: Remove unnecessary methods in PoiRenderer.

- @here/harp-mapview/lib/text/TextElement.ts
> HARP-7373: Add getters/setters for TextElement renderStyle/layoutStyle.

- @here/harp-datasource-protocol/lib/Expr.ts
Prefer to use global functions instead of private static methods.
The reason for this change is that static methods don't minimize very
well, also too many private static methods inside the definition of
`Expr` make the code more difficult to review and maintain.
> MINOR: Remove static mathods for parsing json expr nodes.

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-7375: Fix Label flicker before fade out on collision.

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
* Use maximum view distance to compute far plane for spherical projection.
* Increased number of visible tiles to avoid new visual artifacts. …
> HARP-7410 Changed algorithm to compute near and far plane for globe projection.

- @here/harp-mapview-decoder/lib/TileLoader.ts
- @here/harp-mapview-decoder/package.json
- @here/harp-mapview-decoder/test/TileLoaderTest.ts
- yarn.lock
Signed-off-by: Marcel Pursche marcel.pursche@here.com …
> HARP-8111 Refactored tile loader to fix bug and remove unecessary tile reloads.

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-geojson-datasource/lib/GeoJsonGeometryCreator.ts
- @here/harp-geojson-datasource/lib/GeoJsonParser.ts
- @here/harp-geojson-datasource/lib/GeoJsonTile.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> HARP-7373: Fix decoding of feature ids.

- @here/harp-mapview/lib/text/TextElementGroupState.ts
- @here/harp-mapview/lib/text/TextElementState.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-7373: Point label persistence across zoom levels.

- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-examples/src/datasource_features_polygons.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/getting-started_hello-world_js-bundle.html
- @here/harp-examples/src/getting-started_hello-world_npm.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-examples/src/styling_data-driven.ts
- @here/harp-examples/src/threejs_camera-animation.ts
- @here/harp-geoutils/lib/coordinates/GeoCoordinates.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/test/MapViewTest.ts
- docs/GettingStartedGuide.md
- yarn.lock
> HARP-7399 Added camera properties to MapView constructor

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
When using globe (spherical) projections we found regression that causes
the roads/labels and other fading features to disappear when looking
straight top-down with camera. This is caused by wrong ViewRanges setup
where maximum view range equals far plane distance and thus there is no
place for fading interpolation (between far and max).
This patch-set fixes it.
If you are adding new functionality we would highly appreciate if you …
> HARP-8224: Fix ViewRanges calculus in ClipPlanesEvaluators with globe.

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Remove filtering state bookkeeping that became obsolete after removal of nested styles (#1096)
> Remove deprecated code from StyleSetEvalutator.

- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
> HARP-7373: Use feature id if available for label deduplication.

- @here/harp-mapview/lib/text/Placement.ts
> HARP-8249 Changed calculation for visibily of text labels in spherical projection

- .travis.yml
The deployment script currently fails because of a minor typo in the travis config. This change adresses this. …
> MINOR: Bugfix for website deployment script

- @here/harp-examples/src/getting-started_open-sourced-themes.ts
> Fix theme loading in open-sourced-themes example.

- @here/harp-mapview/lib/MapView.ts
Also, clear it on call to MapView's dispose method. …
> HARP-8173: Clear label states cache on projection change.

- @here/harp-datasource-protocol/index.ts
- @here/harp-datasource-protocol/lib/ColorUtils.ts
- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts
- @here/harp-datasource-protocol/lib/TechniqueDescriptor.ts
- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-datasource-protocol/lib/operators/ColorOperators.ts
- @here/harp-datasource-protocol/test/ColorUtilsTest.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/DepthPrePass.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/text/TextStyleCache.ts
- @here/harp-mapview/test/DecodedTileHelpersTest.ts
- @here/harp-materials/lib/CirclePointsMaterial.ts
- @here/harp-materials/lib/EdgeMaterial.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-materials/lib/Utils.ts
> HARP-7517:  Transparency support via RGBA colors defined in techniques (themes).

- @here/harp-mapview/lib/text/TextElementStateCache.ts
> HARP-7373: Zoom level persistence for path labels.

- @here/harp-debug-datasource/lib/DebugTileDataSource.ts
- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-examples/src/datasource_features_polygons.ts
- @here/harp-examples/src/getting-started_free-camera.ts
- @here/harp-examples/src/getting-started_globe-projection.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PolarTileDataSource.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/FakeOmvDataSource.ts
- @here/harp-mapview/test/PolarTileDataSourceTest.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
> HARP-7238 Implement mixed LOD will all children/no children policy

- @here/harp-mapview/lib/text/TextElementStateCache.ts
If a false duplicate is found for a text element with feature id, try finding again duplicates using text as cache key. …
> HARP-4888: Fallback to dedup with text on feature id collision.

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/clipPolygon.ts
- @here/harp-omv-datasource/test/OmvClippedPolygonsTest.ts
Clip the polygon geometries when using fill and standard techniques.
> HARP-6251: Clip the polygons.

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview/lib/text/TextStyleCache.ts
* tracking
* leading
* maxLines
* lineWidth
* canvasRotation
* lineRotation
* wrappingMode
> MINOR: Made text layout properties pseudo dynamic:

- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
Reintroduce for plane upper limit for spherical projection to improve performance with large tilt angles.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running …
> HARP-8180 Reintroduce plane upper limit for spherical projection

- @here/harp-materials/lib/EdgeMaterial.ts
Extrusion shader chunks where not enabled in the first frame of extrusion
animation, because internal uniform was set to min value by default, so
animation starting with min value caused shader state change after first
frame. …
> HARP-8361: Fix edges extrusion effect flickering (EdgeMaterial).

- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
Renamed to "isPathLabelTooSmall".
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps …
> HARP-4888: Move checkSmallLabels out of TextElementsRenderer.

- @here/harp-mapview/lib/ThemeLoader.ts
- @here/harp-mapview/test/ThemeLoaderTest.ts
> Invoke custom url resolver before resolving relative urls

- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-4888: Move point label placement to separate function.

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
There is a bug when technique color is fixed in theme, but opacity
value is expression (zoom level) based the final material color is not
updated.
This patch-set fixes the problem by linking the opacity and color
properties interpolation, so the corresponding render helper (update
callback) is always applied, whenever one of them changes.
TODO:
- Revise entire render helpers installment, which are strongly related with
fading features,
- Optimize render helpers, so corresponding technique features are applied
independently from each other (currently utilizes the same callback,
sometimes forcing all properties update).
Before requesting a pull request, please remember to check the …
> HARP-6688: Fix color values updates due to opacity interpolation.

- @here/harp-examples/src/getting-started_globe-projection.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-mapview/lib/MapView.ts
> HARP-8442 Enable mixed lod for all examples with globe support.

- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
> HARP-4888: Refactoring addPointLabel method.

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
Code was almost a 1-1 copy of initializeGlyphs() function. …
> HARP-4888: Refactor duplicated code in placeOverlayTextElements.

- @here/harp-mapview/lib/MapViewFog.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/EdgeMaterial.ts
- @here/harp-materials/lib/HighPrecisionLineMaterial.ts
- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-materials/lib/Utils.ts
> HARP-8361: Unify preprocessor defines in SolidLineMaterial shaders.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/test/MapViewTest.ts
- @here/harp-mapview/test/ThemeLoaderTest.ts
> HARP-8387 Add empty default theme to MapView.

- @here/harp-mapview/lib/text/TextStyleCache.ts
This is a partial fix for the lack of default values substituting
missing text technique attributes, here mainly for the TextRenderStyle.
The problem touches much more technique attributes which may be still
undefined. This patch-set ensures setting:
- opacity,
- backgroundOpacity
- color,
- backgroundColor.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and …
> HARP-8531: Fix text disappearing due to lack of opacity/color defined.

- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
> HARP-8427 Fix ios building extrusion bug

- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/RoadPicker.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
Picking returns also techniques is enabled.
Depends (and includes) on picking fix in #1244
Related-to: HARP-8584
> Improve object picking.

- .travis.yml
- scripts/git-check-clean-workspace.sh
- scripts/prepare_doc_deploy.ts
- yarn.lock
> CI: Fix gh-pages deploy script.

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-lines/test/rendering/RenderLines.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> Harp-8819: Extending support for round and diamond shaped dashes

- @here/harp-transfer-manager/package.json
- @here/harp-transfer-manager/src/DeferredPromise.ts
- @here/harp-transfer-manager/src/TransferManager.ts
- @here/harp-transfer-manager/test/DeferredPromiseTest.ts
Minor refactoring for easier debugging and better test coverage. …
> HARP-8560 Refactor transfer manager and add test for DeferredPromise.

- @here/harp-materials/lib/CirclePointsMaterial.ts
- @here/harp-materials/test/CirclePointsMaterialTest.ts
- test/rendering/StylingTest.ts
> HARP-8344 Fixed CirclePointsMaterial and added tests.

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/package.json
- @here/harp-datasource-protocol/test/ThemeTypingsTest.ts
- webpack.tests.config.js
- yarn.lock
Typestring is unmaintained and brings along a super old TypeScript
version. Use the TypeScript Compiler API instead.
> Remove typestring dependency

- @here/harp-mapview/lib/text/TextStyleCache.ts
> Remove bogus colorMap from TextStyleCache.

- www/package.json
Sync harp-website (`www/`) with rest of project, so we've got consistent tags.
> Sync harp-website with rest of project.

- @here/harp-olp-utils/lib/OlpCopyrightProvider.ts
Added configurable environment to OlpCopyrightProvider.
Signed-off-by: Oleksandr Popov <ext-oleksandr.popov@here.com>
> Added configurable environment to OlpCopyrightProvider.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewPoints.ts
- @here/harp-mapview/lib/PickingRaycaster.ts
> Fixes #1270. Construct correct Raycaster

- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/test/PoiInfoBuilder.ts
- @here/harp-mapview/test/TextElementBuilder.ts
- @here/harp-mapview/test/TextElementsRendererTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
- @here/harp-mapview/test/TextElementsRendererTestUtils.ts
> HARP-8717: Support mutable user text elements.

- scripts/rendering-tests-reference-platform.sh
- test/README.md
Signed-off-by: Dmytro Rudakov <ext-dmytro.rudakov@here.com> …
> HARP-8969: Update Docker Chrome version for IBCT

- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-materials/index.ts
- @here/harp-materials/lib/DisplacementFeature.ts
- @here/harp-materials/lib/EdgeMaterial.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
> HARP-8521: Fix extruded buildings overlay.

- @here/harp-datasource-protocol/lib/operators/MathOperators.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
(used by POI styling HARP-7077).
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone …
> Minor: Added support to also use "-" operator to negate numbers

- @here/harp-atlas-tools/package.json
- @here/harp-datasource-protocol/package.json
- @here/harp-debug-datasource/package.json
- @here/harp-examples/package.json
- @here/harp-features-datasource/package.json
- @here/harp-fetch/package.json
- @here/harp-geojson-datasource/package.json
- @here/harp-geometry/package.json
- @here/harp-geoutils/package.json
- @here/harp-lines/package.json
- @here/harp-lrucache/package.json
- @here/harp-map-controls/package.json
- @here/harp-map-theme/package.json
- @here/harp-mapview-decoder/package.json
- @here/harp-mapview/package.json
- @here/harp-materials/package.json
- @here/harp-olp-utils/package.json
- @here/harp-omv-datasource/package.json
- @here/harp-test-utils/package.json
- @here/harp-text-canvas/package.json
- @here/harp-theme-tools/package.json
- @here/harp-transfer-manager/package.json
- @here/harp-utils/package.json
- @here/harp-webpack-utils/package.json
- @here/harp-webtile-datasource/package.json
- @here/harp.gl/package.json
- package.json
- www/package.json
- yarn.lock
> HARP-9110: Update to Typescript 3.8

- test/README.md
Signed-off-by: Dmytro Rudakov <ext-dmytro.rudakov@here.com> …
> MINOR: Fix typos in README.md

- test/performance/OmvDecoderPerformanceTest.ts
> HARP-9128: Fix error while running performance test baseline

- test/rendering/StylingTest.ts
Add IBCT tests for diagonal and dashed lines.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps …
> HARP-8622 Added ibct tests for diagonal and dashed lines

- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/TextElementsRendererTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
- @here/harp-mapview/test/TextElementsRendererTestUtils.ts
- @here/harp-mapview/test/TileTest.ts
- @here/harp-utils/lib/GroupedPriorityList.ts
- @here/harp-utils/test/GroupedPriorityListTest.ts
with maximum priority.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone …
> HARP-8910: Deprecate user text elements. They are just text elements

- @here/harp-geometry/lib/EdgeLengthGeometrySubdivisionModifier.ts
- @here/harp-geometry/package.json
- @here/harp-geometry/test/EdgeLengthGeometrySubdivisionModifierTest.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/LodMesh.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/test/LodMeshTest.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- yarn.lock
Fixes mixed LOD cracks for webtile data source, background datasource and omv data source.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the …
> HARP-8709 Implement strategy to fix mixed LOD cracks

- test/rendering/StylingTest.ts
> Dispose MapViews in StylingTests.

- @here/harp-omv-datasource/lib/OmvDataSource.ts
> Change default level of OMV DataSource to 17

- @here/harp-mapview/lib/ElevationRangeSource.ts
- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-8870 Fix cull frustum setup when terrain data source is used.

- @here/harp-geoutils/lib/math/OrientedBox3.ts
- @here/harp-geoutils/test/OrientedBox3Test.ts
Using slabs intersection algorithm.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps …
> HARP-9275: Implement ray intersection for OrientedBox3.

- README.md
> Add link to register to slack.

- @here/harp-utils/index-common.ts
- @here/harp-utils/lib/SampleBilinear.ts
- @here/harp-utils/test/SampleBilinearTest.ts
> HARP-9275: Move bilinear interpolation sampling to harp utils.

- @here/harp-omv-datasource/lib/OmvDataSource.ts
- @here/harp-omv-datasource/test/OmvDataSourceTest.ts
> Fixed bug in OmvDataSource introduced by PR #1375 (HARP-9037).

- @here/harp-examples/src/rendering_synchronous.ts
> HARP-9460: Fix Synchronous example.

- @here/harp-examples/src/datasource_features_polygons.ts
> MINOR: Update data source polygon example: Implement Brexit.

- @here/harp-examples/lib/PerformanceUtils.ts
- @here/harp-examples/src/datasource_custom.ts
- @here/harp-examples/src/datasource_geojson_choropleth.ts
- @here/harp-examples/src/getting-started_free-camera.ts
- @here/harp-examples/src/getting-started_open-sourced-themes.ts
- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-examples/src/rendering_post-effects_all.ts
- @here/harp-examples/src/rendering_post-effects_themes.ts
- @here/harp-examples/src/rendering_synchronous.ts
- @here/harp-examples/src/styling_extend-a-theme.ts
- @here/harp-examples/src/styling_interpolation.ts
- @here/harp-examples/src/styling_textured-areas.ts
- @here/harp-examples/src/synchronized-views.ts
- @here/harp-examples/src/threejs_animation.ts
- @here/harp-examples/src/threejs_raycast.ts
- @here/harp-examples/src/threejs_shadows.ts
- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-mapview/lib/ClipPlanesEvaluator.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewFog.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/MapViewTest.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-omv-datasource/test/MapViewPickingTest.ts
- test/rendering/GeoJsonDataRendering.ts
- test/rendering/StylingTest.ts
- www/src/index.ts
* MapView.lookAt takes an object parameter now
* added getters for tilt and heading
> HARP-7835: Improved lookAt API

- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/test/PlacementTest.ts
- @here/harp-mapview/test/PoiRendererTest.ts
Fixes label and icon placement when word wrapping and offsets are enabled. …
> HARP-9198 HARP-9280 Fix label and icon placement

- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Avoid evaluating filter conditions when the values of feature
properties used in conditions did not change.
> Speed up getMatchingTechniques.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-omv-datasource/test/MapViewPickingTest.ts
> HARP-7835: Removal of MapView.worldRoot

- @here/harp-mapview/lib/poi/PoiRenderer.ts
> HARP-9273 Fixed flipped texture atlas mipmap generation

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Prefer to use uint16 buffers when possible.
> Reduce the size of the index buffers.

- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/DisplacedMesh.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/overlayOnElevation.ts
- @here/harp-mapview/test/TileCreationTest.ts
- @here/harp-mapview/test/TileTest.ts
> HARP-9275 DisplacedMesh to support picking of elevated meshes.

- @here/harp-mapview/test/TextElementsRendererTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
> HARP-7835: Fix label tests with terrain overlay.

- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
> HARP-9894 Fix flipped textures across browsers.

- @here/harp-mapview/lib/PickHandler.ts
> HARP-9871: Fix label picking on HiDPI screens.

- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
> MINOR: Remove console warnings for shader

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/DisplacedBufferAttribute.ts
- @here/harp-mapview/lib/geometry/DisplacedBufferGeometry.ts
- @here/harp-mapview/lib/geometry/DisplacedMesh.ts
- @here/harp-mapview/lib/geometry/SolidLineMesh.ts
- @here/harp-mapview/test/SolidLineMeshTest.ts
> HARP-8498: SolidLineMesh.

- www/src/index.ts
Fix animation on harp.gl website introduced by mistake in #1392 .
> www: Fix animation.

- @here/harp-mapview/lib/text/LayoutState.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementState.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/PlacementTest.ts
- @here/harp-mapview/test/TextElementBuilder.ts
- @here/harp-mapview/test/TextElementsRendererTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
- @here/harp-mapview/test/stubTextCanvas.ts
- @here/harp-text-canvas/lib/TextCanvas.ts
- @here/harp-text-canvas/lib/rendering/TextStyle.ts
> HARP-6488: Introduce Labels' LayoutState for storing alternative anchor.

- @here/harp-examples/src/object-picking.ts
Also, trigger picking only if there's no dragging. …
> MINOR: Support touch screens in object picking example.

- @here/harp-mapview/lib/geometry/SolidLineMesh.ts
- @here/harp-mapview/test/SolidLineMeshTest.ts
> MINOR: Skip degenerate solid-line segments on picking.

- @here/harp-datasource-protocol/lib/InterpolatedProperty.ts
- @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts
- @here/harp-datasource-protocol/test/InterpolationTest.ts
This change introduces the internal class InterpolatedProperty used
to create and evaluate interpolations.
> Introduce the internal class InterpolatedProperty.

- @here/harp-examples/src/threejs_shadows.ts
- @here/harp-mapview/lib/MapView.ts
> MINOR: Fix documentation and usage of MapView.lights

- @here/harp-omv-datasource/test/MapViewPickingTest.ts
- @here/harp-omv-datasource/test/resources/geoJsonData.ts
Reuse old disabled tests, adding testing for different projections,
terrain overlay and HiDPI screens.
> HARP-10004: Picking e2e testing

- @here/create-harp.gl-app/package.json
- @here/generator-harp.gl/package.json
- @here/harp-datasource-protocol/package.json
- @here/harp-debug-datasource/package.json
- @here/harp-features-datasource/package.json
- @here/harp-fetch/package.json
- @here/harp-geojson-datasource/package.json
- @here/harp-geometry/package.json
- @here/harp-geoutils/package.json
- @here/harp-lines/package.json
- @here/harp-lrucache/package.json
- @here/harp-map-controls/package.json
- @here/harp-map-theme/package.json
- @here/harp-mapview-decoder/package.json
- @here/harp-mapview/package.json
- @here/harp-materials/package.json
- @here/harp-omv-datasource/package.json
- @here/harp-test-utils/package.json
- @here/harp-text-canvas/package.json
- @here/harp-transfer-manager/package.json
- @here/harp-webtile-datasource/package.json
> MINOR: Update mocha to 7.1.1

- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-examples/src/threejs_shadows.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/test/MapViewTest.ts
> Adds Settings to enable transparent canvas

- @here/harp-mapview/lib/ScreenCollisions.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/PlacementTest.ts
> HARP-9898: Change the way how text offset is applied to the Labels.

- @here/harp-mapview/lib/image/Image.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MipMapGenerator.ts
- @here/harp-mapview/lib/poi/Poi.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/test/MipMapGeneratorTest.ts
> HARP-9664 Implement custom mip map generator

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-lines/test/rendering/RenderLines.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/ShaderChunks/LinesChunks.ts
- @here/harp-materials/lib/SolidLineMaterial.ts
> HARP-8308 Adding traffic line offsetting

- @here/harp-map-controls/lib/MapControls.ts
> HARP-10138: Fix state handling when stopping zoom animation.

- @here/harp-map-controls/test/MapControlsTest.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
> HARP-10128: Use elevation at camera position to compute target.

- package.json
- yarn.lock
> MINOR: Update mocha-webdriver-runner

- @here/harp-map-controls/test/MapControlsTest.ts
> HARP-10229: Unit testing globe zoom fix.

- @here/harp-map-controls/test/MapControlsTest.ts
> MINOR: Remove timeout cancellation from MapControls unit test.

- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/MapMaterialAdapter.ts
- @here/harp-mapview/lib/MapObjectAdapter.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PolarTileDataSource.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-mapview/test/MapViewTest.ts
- @here/harp-utils/lib/ObjectUtils.ts
There are two commits
* base introduces MapObjectAdapter and MapMaterialAdapter which should encapsulate data/logic needed to update object/material from scene Pov
* example that installs aproppriate adapter to PolarDataSource, so we can actually intrpolate their properties
> HARP-8740: Skip transparent world space objects.

- .github/workflows/ci.yaml
> Github Actions CI: increase test timeouts.

- @here/harp-geoutils/lib/math/MathUtils.ts
- @here/harp-geoutils/lib/projection/MercatorProjection.ts
- @here/harp-geoutils/lib/projection/Projection.ts
- @here/harp-geoutils/lib/projection/SphereProjection.ts
- @here/harp-geoutils/test/SphereProjectionTest.ts
> HARP-8309 Get LTS at world pos

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview-decoder/lib/WorkerService.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Icon's can be offset using the `offset_direction` attribute in the data and the `offsetWorld` attribute in the style.
> HARP-8309 Add offsetting of icons based on offset_direction

- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
> HARP-10237 Add flag to allow selective disabling of fallback logic.

- yarn.lock
> Running: yarn --update-checksums

- @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts
> HARP-10605: Fix label debug info for lines

- .github/workflows/ci.yaml
> Github CI: Save more hard-source caches.

- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/OmvDecoderDefs.ts
- @here/harp-omv-datasource/lib/OmvPoliticalViewFeatureModifier.ts
> HARP-5644: Support for Political Views via FeatureModifiers stack.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/lib/text/TextElementsRendererOptions.ts
> (HARP-10414): Delays new labels until map movement finishes

- @here/harp-datasource-protocol/index.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-debug-datasource/index.ts
- @here/harp-features-datasource/index.ts
- @here/harp-fetch/index.web.ts
- @here/harp-geojson-datasource/index.ts
- @here/harp-geometry/index.ts
- @here/harp-geoutils/index.ts
- @here/harp-lrucache/index.ts
- @here/harp-map-controls/index.ts
- @here/harp-mapview-decoder/index.ts
- @here/harp-mapview/index.ts
- @here/harp-materials/index.ts
- @here/harp-olp-utils/index.ts
- @here/harp-omv-datasource/index.ts
- @here/harp-text-canvas/index.ts
- @here/harp-transfer-manager/index.ts
- @here/harp-utils/index.ts
- @here/harp-webtile-datasource/index.ts
Also remove deprecate vscode snippets and use @remarks to clean up
the Theme declarations.
> Set up package documentation.

- @here/harp-examples/src/rendering_post-effects_themes.ts
- @here/harp-mapview/lib/composing/Outline.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/EdgeMaterial.ts
> HARP-10603: Fix outline rendering

- @here/harp-map-controls/lib/MapControls.ts
> HARP-10717: Add zoomEnabled and panEnabled to MapControls.

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-geojson-datasource/lib/GeoJsonTileDecoderService.ts
- @here/harp-geometry/lib/OrientedBox3.ts
- @here/harp-geoutils/lib/math/MathUtils.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-omv-datasource/lib/OmvDataSource.ts
Add deprecation message and remove comma characters when using`@deprecate` tsdoc tags.
> Fix deprecate tags

- @here/harp-examples/src/threejs_animation.ts
- @here/harp-mapview/lib/MapAnchors.ts
- @here/harp-mapview/lib/MapView.ts
> HARP-10793: Add overlay property to MapAnchor

- @here/harp-mapview/lib/DepthPrePass.ts
- @here/harp-mapview/lib/composing/Outline.ts
- @here/harp-mapview/test/OutlineTest.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
> HARP-10751: Fix animated extrusion for outline effect

- @here/harp-mapview/lib/AnimatedExtrusionHandler.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/test/AnimatedExtrusionHandlerTest.ts
- @here/harp-materials/lib/MapMeshMaterials.ts
- test/rendering/GeoJsonDataRendering.ts
> HARP-10446: Simplify extruded building animation.

- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-map-controls/test/MapControlsTest.ts
> HARP-10717: Unit tests for Map Controls interaction disabling.

- README.md
Remove the default parameters from the initialization of
the `OmvDataSource`.
> Simplify code snippet in README.md

- .github/workflows/ci.yaml
Remove caching of the hard-source webpack plugin.
> Remove caching of hard-source

- @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts
The GeoJSON adapter was flattening the geometries of the
MultiLineString, also it was assuming that there
was a match from the tiled positions in the original geometry.
Base on this assumption the adapter was filling
the array of geo coordinates.
> HARP-10866: Fix decoding of GeoJSON MultiLineString features.

- @here/harp-geoutils/lib/coordinates/GeoBox.ts
- @here/harp-geoutils/test/GeoBoxTest.ts
- @here/harp-mapview/test/TileTest.ts
> MINOR: Fix GeoBox clone method.

- @here/harp-map-controls/lib/CameraKeyTrackAnimation.ts
> Minor camera animation

- @here/harp-map-theme/package.json
- @here/harp-text-canvas/test/FontCatalogTest.ts
- yarn.lock
> HARP-10847: Upgrade to harp-fontcatalog 0.1.6

- @here/harp-examples/src/performance_benchmark.ts
- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewTaskScheduler.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/lib/geometry/TileGeometryManager.ts
- @here/harp-mapview/test/FakeOmvDataSource.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-utils/index-common.ts
- @here/harp-utils/lib/TaskQueue.ts
- @here/harp-utils/test/TaskQueueTest.ts
> Tile Processing Queue

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
Remove the dependency on the MapView from the VisibleTileSet
> HARP-8943 Minor refactorings

- @here/harp-examples/src/datasource_custom-texture-tile.ts
- @here/harp-examples/src/datasource_here-webtile.ts
- @here/harp-examples/src/rendering_globe-atmosphere.ts
- @here/harp-webtile-datasource/index.ts
- @here/harp-webtile-datasource/lib/HereWebTileDataSource.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- @here/harp-webtile-datasource/test/WebTileTest.ts
> Extract Here API specifc code from Webtiledatasource

- @here/harp-geometry/lib/ClipPolygon.ts
- @here/harp-geometry/package.json
- @here/harp-geometry/test/ClipPolygonTest.ts
- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
This change specializes the Sutherland-Hodgman algorithm to
clip a polygon against rectangular bounds. This should improve
precision and speed up the clipping.
> Specialize the clipping algorithm for the vector-tile use case.

- @here/harp-map-controls/lib/MapControls.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
> HARP-10717: Restrict view to given geo bounds for mercator.

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- @here/harp-omv-datasource/lib/OmvDecoder.ts
- @here/harp-omv-datasource/lib/Ring.ts
- @here/harp-omv-datasource/test/RingTest.ts
- test/rendering/GeoJsonDataRendering.ts
This change simplifies the support for working with rings
and texture coordinates. The Ring now maintains distinct
arrays of position and texture coordinates and has APIs
to flatten the Ring into an Array of numbers.
> HARP-10648: Fix stroking of geometry touching the tile border.

- scripts/setup-docs.ts
> HARP-6703 Fix copying across images

- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-examples/src/datasource_features_polygons.ts
- @here/harp-examples/src/datasource_geojson_choropleth.ts
- @here/harp-examples/src/datasource_here_vector_tile.ts
> HARP-10113: Add missing copyright info in samples

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/image/Image.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MapViewImageCache.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/test/ImageCacheTest.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-10770: Adding methods to remove images from cache

- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/test/TileTest.ts
> Evaluates Tiles of DataSources that are not attached to a MapView as NOT visible

- @here/harp-map-controls/test/MapControlsTest.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
> HARP-11102: Support MapView's max bounds for globe.

- @here/harp-mapview/lib/IntersectParams.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/PickListener.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/PickListenerTest.ts
> Harp 10772 limit picking results

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
> HARP-11222: Add depthTest property for SolidLineTechnique.

- @here/harp-mapview/test/DecodedTileHelpersTest.ts
> HARP-11222: Add unit tests to createMaterial for solid lines depth test.

- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/PickListener.ts
- @here/harp-mapview/test/PickListenerTest.ts
> HARP-10772: Finish PickListener results explicitely.

- .github/workflows/ci.yaml
> Added CI for test on Windows Firefox

- @here/harp-text-canvas/lib/rendering/TextGeometry.ts
> HARP-11090: Labels invisible in Post effects example

- @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
> HARP-11147: Fix transient geometry highlighting in object picking example

- @here/harp-datasource-protocol/lib/DecodedTile.ts
- @here/harp-examples/decoder/custom_decoder.ts
- @here/harp-examples/src/datasource_custom.ts
- @here/harp-examples/src/tile_dependencies.ts
- @here/harp-mapview-decoder/test/TileLoaderTest.ts
- @here/harp-mapview/lib/PickHandler.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-omv-datasource/test/MapViewPickingTest.ts
These have dependencies which allow a tile which has
content that exceeds its border to be visible when it is
within another Tile
> HARP-11205 Adding dependencies to DecodedTile/Tile

- @here/harp-mapview/lib/MapView.ts
> MINOR: Spelling mistake

- .github/workflows/docs.yaml
Add manually triggered action to generate the docs using
api-extractor/documenter.
> Add action to generate the docs.

- .github/workflows/docs.yaml
- .prettierignore
Also, add the github workflow directory to prettierignore.
> Fix docs workflow specification.

- @here/harp-omv-datasource/lib/OmvData.ts
Fix winding at OmvProtobufDataAdapter for XYZ spaces using protobuf.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from our team will …
> HARP-11151: Force ring winding to follow Mapbox Vector Tile spec.

- .github/workflows/ci.yaml
> Remove node 10 and 14 to reduce feedback response time

- .prettierignore
- @here/harp-examples/src/bounds-generation.ts
- @here/harp-geoutils/lib/coordinates/GeoCoordinates.ts
- @here/harp-mapview/index.ts
- @here/harp-mapview/lib/BoundsGenerator.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/test/BoundsGeneratorTest.ts
- @here/harp-mapview/test/TileGeometryCreatorTest.ts
> (HARP-11092) Adds Bounds Generation

- @here/harp-examples/src/bounds-generation.ts
> MINOR Adds instructions to Bounds Example

- @here/harp-mapview/lib/BoundsGenerator.ts
- @here/harp-mapview/test/BoundsGeneratorTest.ts
> MINOR: Adds projection setter to BoundsGenerator

- @here/harp-map-controls/lib/CameraKeyTrackAnimation.ts
> MINOR: Fixes CameraKeyTrackAnimation terminating before last frame is updated

- @here/harp-mapview/lib/BoundsGenerator.ts
- @here/harp-mapview/lib/EventDispatcher.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewTaskScheduler.ts
- @here/harp-mapview/lib/PickingRaycaster.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-utils/lib/TaskQueue.ts
- @here/harp-webtile-datasource/lib/HereWebTileDataSource.ts
- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- package.json
- test/performance/OmvDecoderPerformanceTest.ts
Fix eslint errors introduced from the last time that the
code was checked.
> Fix eslint issues.

- @here/harp-mapview/lib/AnimatedExtrusionHandler.ts
- @here/harp-mapview/test/AnimatedExtrusionHandlerTest.ts
Extrusion animation across multiple data sources was not supported by
extrusion animation handler after latest refactoring. …
> HARP-10889: Fix extrusion animation in polygons example.

- @here/harp-map-theme/resources/berlin_tilezen_base.json
- @here/harp-map-theme/resources/berlin_tilezen_roadshields.json
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementState.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/test/TextElementStateCacheTest.ts
- @here/harp-mapview/test/TextElementStateTest.ts
- @here/harp-vectortile-datasource/lib/OmvDebugLabelsTile.ts
> HARP-11266: Enable generic road shields

- .eslintignore
> Exclude generated files from eslint

- @here/harp-examples/src/datasource_geojson_points.ts
> MINOR: Added marker example with custom icon

- @here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-mapview/test/DataSourceTest.ts
- @here/harp-utils/lib/TaskQueue.ts
- @here/harp-utils/test/TaskQueueTest.ts
> HARP-11458 Detached tiles don't dispose via VisibleTileSet

- @here/harp-examples/src/bounds-generation.ts
- @here/harp-geoutils/index.ts
- @here/harp-geoutils/lib/coordinates/GeoBox.ts
- @here/harp-geoutils/lib/coordinates/GeoCoordLike.ts
- @here/harp-geoutils/lib/coordinates/GeoCoordinates.ts
- @here/harp-geoutils/lib/coordinates/GeoPolygon.ts
- @here/harp-geoutils/lib/coordinates/GeoPolygonLike.ts
- @here/harp-geoutils/test/GeoPolygonTest.ts
- @here/harp-mapview/lib/BoundsGenerator.ts
- @here/harp-mapview/lib/MapAnchors.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/BoundsGeneratorTest.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-11574: Supports GeoPolygon in MapView.lookAt

- @here/harp-map-theme/resources/berlin_tilezen_roadshields.json
> HARP-11648: Fix attributes in road shield style

- .eslintrc.json
- @here/harp-datasource-protocol/lib/WorkerServiceProtocol.ts
- @here/harp-datasource-protocol/lib/operators/StringOperators.ts
- @here/harp-examples/lib/PerformanceUtils.ts
- @here/harp-examples/src/datasource_features_lines-and-points.ts
- @here/harp-examples/src/datasource_features_polygons.ts
- @here/harp-examples/src/performance_benchmark.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
- @here/harp-mapview/lib/EventDispatcher.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MapViewImageCache.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
- @here/harp-test-utils/lib/TestDataUtils.ts
- @here/harp-text-canvas/lib/rendering/FontCatalog.ts
- @here/harp-vectortile-datasource/lib/OmvDataFilter.ts
- @here/harp-vectortile-datasource/lib/OmvDebugLabelsTile.ts
- @here/harp-vectortile-datasource/lib/OmvDecoderDefs.ts
- @here/harp-vectortile-datasource/lib/OmvRestClient.ts
- @here/harp-vectortile-datasource/lib/OmvTomTomFeatureModifier.ts
- @here/harp-vectortile-datasource/test/OmvTest.ts
enable the prefer-includes eslint check.
> enable eslint `prefer-includes` check.

- @here/harp-mapview/lib/BoundsGenerator.ts
> MINOR: Downgrades error on BoundsGenerator to Warning

- @here/harp-mapview/lib/geometry/SolidLineMesh.ts
- @here/harp-mapview/test/SolidLineMeshTest.ts
* Recompute bounding volume for raycasting if geometry changes.
* No automatic detection: requires explicit call to needsUpdate …
> HARP-11044: Recompute bounding volume

- @here/harp-mapview/lib/image/Image.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MapViewImageCache.ts
- @here/harp-mapview/test/ImageCacheTest.ts
…n ImageCache
Signed-off-by: German Zargaryan <german.zargaryan@here.com> …
> HARP-11064: Adds support for HtmlCanvasElement and HtmlImageElement in ImageCache

- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/MapView.ts
> HARP-11780: Make events non-global to allow garbage collection of MapView and DataSource

- .travis.yml
> Modified travis to node v12

- @here/harp-datasource-protocol/lib/ExprEvaluator.ts
- @here/harp-datasource-protocol/test/InterpolationTest.ts
Interpolate the values using a linear interpolation when the base
of the exponential interpolation is equal to 1.
> HARP-11785: Fix exponential interpolations with base equals to 1.

- @here/harp-examples/src/bounds-generation.ts
> Bounds example Fix

- @here/harp-examples/src/tile_dependencies.ts
> HARP-11771: Fixes unreadable info text in example

- @here/harp-examples/src/bounds-generation.ts
> HARP-11772: Fixes boundingbox lines dissapear in example

- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- @here/harp-webtile-datasource/test/HereWebTileDataSourceTest.ts
- @here/harp-webtile-datasource/test/WebTileTest.ts
- test/rendering/WebTileDataRendering.ts
> MINOR: Adds DataSourceOptions to WebTileDataSource

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/TextElementsRendererTest.ts
> HARP-11817: Fixes Labels not clipped by farplane

- @here/harp-mapview/lib/Utils.ts
> Minor: Safeguards access on possible null object

- @here/harp-examples/src/threejs_raycast.ts
- @here/harp-mapview/lib/PickHandler.ts
- Objects added to the MapAnchors are now added to the results of the PickHandler
- Update threejs_raycast example to use MapAnchors
> MINOR: Fixes #1820 raycast not working

- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- @here/harp-webtile-datasource/test/WebTileTest.ts
- test/rendering/WebTileDataRendering.ts
> MINOR: Adds renderOrder support to WebTileDataSource

- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
- @here/harp-webtile-datasource/test/WebTileTest.ts
> MINOR: Webtile hadles rejected Texture Promise

- @here/harp-webtile-datasource/lib/WebTileDataSource.ts
> MINOR: Adds opacity accessors to WebTileDataSource

- @here/harp-geoutils/lib/coordinates/GeoBox.ts
- @here/harp-geoutils/test/GeoBoxTest.ts
- @here/harp-geoutils/test/GeoPolygonTest.ts
> HARP-5550: Adds support for GeoBox to wrap around Antimeridian

- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
> Extruded polygon normals

- @here/harp-datasource-protocol/lib/TechniqueDescriptors.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
This change tags the fill-material attributes that are
kept in sync with their technique value.
> HARP-11247: Declare the automatic properties of the fill technique.

- @here/harp-datasource-protocol/lib/TechniqueDescriptors.ts
- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
This change tags the automatic technique properties of solid-line,
lines and segments techniques.
> HARP-11247: Declare automatic attributes for solid lines and segments.

- @here/harp-datasource-protocol/lib/TechniqueDescriptors.ts
- @here/harp-mapview/lib/DecodedTileHelpers.ts
Tags the attribute of terrain, standard and extruded-polygon techniques.
> HARP-11247: Declare the automatic attributes for the standard techniques

- @here/harp-examples/src/getting-started_orbiting-view.ts
- @here/harp-examples/src/textcanvas.ts
- package.json
- yarn.lock
and add ability to change heading speed, in order to better monitor memory usage.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from …
> HARP-11671 Orbit example, add stats

- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-materials/lib/EdgeMaterial.ts
- test/rendering/GeoJsonDataRendering.ts
> Handles lineWidth as Expression for ExtrudedPolygonTechnique

- yarn.lock
> MINOR: Upgrades webpack-dev-server to use later node-forge for security reasons

- @here/harp-olp-utils/package.json
- yarn.lock
> Upgrade olp packages to update dependencies on node-fetch 1.6.0

- @here/harp-geoutils/lib/coordinates/GeoCoordinates.ts
- @here/harp-geoutils/lib/coordinates/GeoPolygon.ts
- @here/harp-geoutils/test/GeoCoordinatesTest.ts
- @here/harp-map-controls/lib/CameraAnimationBuilder.ts
- @here/harp-mapview/lib/BoundsGenerator.ts
- @here/harp-mapview/lib/MapViewFog.ts
- @here/harp-mapview/lib/SphereHorizon.ts
- @here/harp-mapview/test/BoundsGeneratorTest.ts
- @here/harp-utils/lib/MathUtils.ts
> HARP-11531: Handle pole wrapping for view bounds on sphere.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/test/FakeOmvDataSource.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-11801: Set languages in all datasources

- @here/harp-olp-utils/lib/OlpDataProvider.ts
> MINOR: Makes environment configurable in OlpDataProvider

- @here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts
- @here/harp-mapview/lib/BackgroundDataSource.ts
- @here/harp-mapview/lib/Tile.ts
- @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
- @here/harp-vectortile-datasource/lib/OmvDebugLabelsTile.ts
> HARP-11672: Add TileGeometryLoader's finished promise

- CODINGSTYLE.md
> MINOR: Prefer implicit boolean conversion for objects in coding style.

- @here/harp-mapview/lib/ConcurrentWorkerSet.ts
> HARP-12087: No exception if decoder was destroyed first

- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/lib/text/TextElementsRendererOptions.ts
- @here/harp-mapview/test/stubFontCatalogLoader.ts
- @here/harp-text-canvas/lib/rendering/FontCatalog.ts
- @here/harp-text-canvas/lib/rendering/GlyphData.ts
- @here/harp-text-canvas/test/FontCatalogTest.ts
- @here/harp-text-canvas/test/rendering/TextCanvasRenderingTest.ts
> HARP-11679: Hide replacement glyphs in production

- @here/harp-mapview/lib/FrustumIntersection.ts
- @here/harp-mapview/lib/MapView.ts
Change-Id: Iafb9884df9b858fc8eb5bc8783d9f89b745a1765
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next …
> HARP-12359: Adds minimum tile size configuration for mixed Lod

- @here/harp-mapview/lib/Utils.ts
- @here/harp-mapview/test/UtilsTest.ts
> HARP-12026 Apply tilt limit also to rotation center

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/TileObjectsRenderer.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
> HARP-12587: Moves TileObject rendering to TileObjectRenderer class

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/VisibleTileSet.ts
- @here/harp-mapview/test/VisibleTileSetTest.ts
> HARP-11672: Reload tiles on scheduled tasks when marked dirty.

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewEnvironment.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/MapViewTest.ts
> HARP-12599: Moves Datsource independent styling to MapViewEnvironment

- @here/harp-mapview/lib/MapAnchors.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/poi/PoiTableManager.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
> HARP-12599: Preparations for Async Theme Settting

- @here/harp-examples/src/getting-started_look-at.ts
- @here/harp-examples/src/getting-started_open-sourced-themes.ts
- @here/harp-examples/src/performance_benchmark.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewThemeManager.ts
- @here/harp-mapview/test/MapViewTest.ts
> Async theme

- @here/harp-mapview/lib/MapViewEnvironment.ts
> HARP-12777: Fixes shadow flickering on tilt

- @here/harp-geometry/lib/ClipLineString.ts
- @here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts
- test/rendering/GeoJsonDataRendering.ts
This change introduces the function clipLineString that can be used
to clip lines against the tile bounding box.
> HARP-12403: Add support for clipping lines against the tile bounds.

- @here/harp-datasource-protocol/lib/ITileDecoder.ts
- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-datasource-protocol/lib/Techniques.ts
- @here/harp-datasource-protocol/lib/WorkerDecoderProtocol.ts
- @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/styling_interpolation.ts
- @here/harp-map-theme/test/DefaultThemeTest.ts
- @here/harp-mapview-decoder/lib/ThemedTileDecoder.ts
- @here/harp-mapview-decoder/lib/TileDataSource.ts
- @here/harp-mapview-decoder/lib/TileDecoderService.ts
- @here/harp-mapview/lib/DataSource.ts
- @here/harp-mapview/lib/PolarTileDataSource.ts
- @here/harp-mapview/lib/WorkerBasedDecoder.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/test/PolarTileDataSourceTest.ts
- @here/harp-mapview/test/TileGeometryCreatorTest.ts
- @here/harp-vectortile-datasource/lib/VectorTileDataSource.ts
- @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts
- @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts
- test/performance/OmvDecoderPerformanceTest.ts
> Styleset priorities

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/MapViewEnvironment.ts
- @here/harp-mapview/lib/MapViewFog.ts
- @here/harp-mapview/lib/MapViewThemeManager.ts
- @here/harp-mapview/lib/poi/PoiTableManager.ts
- @here/harp-mapview/lib/text/FontCatalogLoader.ts
- @here/harp-mapview/lib/text/TextStyleCache.ts
- @here/harp-mapview/test/MapViewFogTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
> Preparations for FlatTheme support

- @here/harp-datasource-protocol/lib/ITileDecoder.ts
- @here/harp-mapview-decoder/lib/ThemedTileDecoder.ts
- @here/harp-mapview-decoder/lib/TileDecoderService.ts
- @here/harp-mapview-decoder/lib/TileLoader.ts
- @here/harp-vectortile-datasource/test/VectorTileDecoderTest.ts
> MINOR: Decoder.decodeTile does not throw

- .github/workflows/ci.yaml
CI fails if any of the jobs fail
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from our …
> Modified fail-fast to true

- @here/harp-mapview/lib/image/Image.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MapViewImageCache.ts
- @here/harp-mapview/lib/image/MipMapGenerator.ts
- @here/harp-mapview/lib/poi/BoxBuffer.ts
- @here/harp-mapview/lib/poi/PixelPicker.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/test/ImageCacheTest.ts
- @here/harp-mapview/test/MapViewTest.ts
- @here/harp-mapview/test/MipMapGeneratorTest.ts
- @here/harp-mapview/test/PoiInfoBuilder.ts
> HARP-12700: Refactor Image caches

- @here/harp-datasource-protocol/lib/TechniqueParams.ts
- @here/harp-examples/package.json
- @here/harp-examples/src/datasource_geojson_visibility.ts
- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/TileObjectsRenderer.ts
- @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- @here/harp-mapview/lib/poi/PoiManager.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-vectortile-datasource/lib/OmvDebugLabelsTile.ts
- yarn.lock
This change uses the MapView zoom level to hide objects with their
visibility constrained using min/maxZoomLevel.
> HARP-12867: Fix the visibility of techniques using min/maxZoomLevel.

- @here/harp-mapview/lib/image/Image.ts
- @here/harp-mapview/lib/image/ImageCache.ts
- @here/harp-mapview/lib/image/MapViewImageCache.ts
- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/test/ImageCacheTest.ts
- @here/harp-mapview/test/MipMapGeneratorTest.ts
- @here/harp-mapview/test/PoiInfoBuilder.ts
> HARP-12700 - Further image cache refactoring

- .github/workflows/ci.yaml
> Disable test on windows firefox

- @here/harp-mapview/test/ImageCacheTest.ts
> MINOR: Fix unhandled promise rejections.

- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
* also fixes infinite render loop due to only part of road shields rendered
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots …
> HARP-12773: Roadshield icon disappear, while text remains visible

- @here/harp-utils/test/LoggerManagerTest.ts
The test was enabling all logging channels in the real LoggerManager instance,
leaving them enabled for any other tests. …
> MINOR: Fix LoggerManagerTest.

- .github/workflows/ci.yaml
- @here/harp-mapview-decoder/test/TileDataSourceTest.ts
- @here/harp-mapview/test/BoundsGeneratorTest.ts
- @here/harp-mapview/test/ImageCacheTest.ts
- @here/harp-mapview/test/MapViewTest.ts
- @here/harp-mapview/test/PolarTileDataSourceTest.ts
- @here/harp-mapview/test/StatisticsTest.ts
- @here/harp-mapview/test/TextElementStateCacheTest.ts
- @here/harp-mapview/test/TextElementsRendererTestFixture.ts
- @here/harp-mapview/test/TileTest.ts
- @here/harp-mapview/test/WorkerLoaderTest.ts
- @here/harp-test-utils/lib/TestUtils.ts
- @here/harp-utils/lib/Logger/ILogger.ts
- @here/harp-vectortile-datasource/test/MapViewPickingTest.ts
- @here/harp-vectortile-datasource/test/OmvDataSourceTest.ts
- @here/harp-vectortile-datasource/test/VectorTileDecoderTest.ts
- karma.conf.js
- package.json
- test/browser-resources.js
- yarn.lock
Add configurations and scripts to run the unit tests using karma.
Tests targeting the browser environment must be built using
```
yarn build-tests
```
the following scripts can be used to run the tests
```
yarn karma-browser  # runs the tests using chrome
yarn karma-headless  # runs the tests using chrome headless
yarn karma-headless-firefox  # runs the tests using firefox headless
```
Also, the GitHub workflow is updated to tests both chrome and firefox on linux and windows.
> Use karma for testing harp with selenium.

- @here/harp-mapview/test/PolarTileDataSourceTest.ts
- @here/harp-mapview/test/WorkerLoaderTest.ts
- @here/harp-test-utils/test/TestDataUtilsTest.ts
> MINOR: Fix some tests that were failing with Karma on Windows.

- karma.conf.js
- karma.options.js
Add common karma default options to karma.options.js so they can be
included by external karma configuration files.
> HARP-13084: Add karma.options.js

- @here/harp-mapview/lib/text/Placement.ts
- @here/harp-mapview/lib/text/TextElementGroupState.ts
- @here/harp-mapview/lib/text/TextElementState.ts
- @here/harp-mapview/lib/text/TextElementStateCache.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- @here/harp-mapview/test/TextElementStateCacheTest.ts
- @here/harp-mapview/test/TextElementStateTest.ts
> HARP-13055: Add individual TextElementStates for line markers

- yarn.lock
Clean up the lock file by running yarn-deduplicate on yarn.lock.
> Run yarn-deduplicate on yarn.lock

- test/rendering/GeoJsonDataRendering.ts
- test/rendering/GeoJsonFeaturesRendering.ts
- test/rendering/ScreenSpaceRenderingTests.ts
- test/rendering/utils/GeoJsonTest.ts
- test/rendering/utils/ThemeBuilder.ts
> Makes TextElementsRenderer update- and reset-able

- www/package.json
- yarn.lock
Older version had deprecated behaviour. …
> HARP-12728: Update Webpack's MiniCssExtractPlugin.

- @here/create-harp.gl-app/package.json
- yarn.lock
> MINOR: Update ini to avoid security issue

- @here/create-harp.gl-app/package.json
- yarn.lock
> Remove Duplicate Dependencies

- package.json
- yarn.lock
> MINOR: Remove unneeded dependency

- @here/harp-mapview/lib/MapView.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- test/rendering/ScreenSpaceRenderingTests.ts
- test/rendering/utils/GeoJsonTest.ts
> TextElements frozen on theme change

- @here/harp-map-controls/lib/MapAnimations.ts
- @here/harp-map-controls/package.json
- yarn.lock
Signed-off-by: Daniele Bacarella <daniele.bacarella@here.com> …
> Update Tween dependency

- .gitlab-ci.yml
- scripts/generate-config.sh
> HARP-13842 - Adding gitlab-CI related file

- @here/harp-olp-utils/package.json
- yarn.lock
Signed-off-by: Daniele Bacarella <daniele.bacarella@here.com> …
> Update OLP SDK dependencies

- .github/workflows/deploy_to_npm.yaml
> HARP-11448: Adds github workflow for package publishing

- .github/workflows/deploy_to_npm.yaml
> Publish with GitHub actions

- .github/workflows/deploy_to_npm.yaml
> HARP-11448: Fixes not found cross-env

- .github/workflows/ci.yaml
- @here/harp-map-theme/package.json
> Add Package Testing to Github Actions CI workflow

- .github/workflows/rebase.yml
This reverts commit 827e8a70b79db2bceb4be4cb124f27ba626233ff.
> Revert debug info from rebase + add contributor to people who can rebase.

- @here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts
- test/rendering/GeoJsonFeaturesRendering.ts
- test/rendering/utils/GeoJsonStore.ts
This PR ensures that the winding of the polygons decoded by the tiled geojson adapter follow
the winding convention expected by the rendering techniques.
> HARP-13254: Fix rendering of extruded polygon having CW winding.

- @here/harp-vectortile-datasource/test/MapViewPickingTest.ts
Sometimes they timeout in karma on Windows.
> MINOR: Increase timeout for picking tests.

- .github/workflows/deploy_to_npm.yaml
- scripts/prepare_doc_deploy.ts
Branch passed through was incorrect, and therefore the `master` version wasn't being updated.
> MINOR: Fix deploy documentation

- @here/harp-webtile-datasource/lib/WebTileLoader.ts
> HARP-14500: Fixes blinking webtiles on globe

- @here/harp-examples/src/real-time-shadows.ts
> MINOR: Fixes shadow example not showing buildings on webtiles

- @here/harp-examples/package.json
> HARP-14567: Stop publishing @here/harp-examples

- @here/harp-examples/src/camera-animations_quaternion-slerp.ts
- @here/harp-examples/src/styling_extend-a-theme.ts
- docs/GettingStartedGuide.md
> MINOR: Fix some incorrect documentation / grammar

- @here/harp-mapview/lib/PickListener.ts
- @here/harp-mapview/test/PickListenerTest.ts
> HARP-14553: Ignore small distance differences on picking.

- .gitlab-ci.yml
> HARP-15134 Add jobs to update github status

- package.json
- yarn.lock
> HARP-15180 Fixing security warnings by upgrading karma

- @here/harp-examples/src/datasource_geojson_visibility.ts
- @here/harp-features-datasource/lib/FeaturesDataSource.ts
> HARP-15488 Don't add ground planes to FeatureDataSources

- @here/harp-examples/src/datasource_geojson_choropleth.ts
- @here/harp-examples/src/datasource_geojson_custom-shader.ts
- @here/harp-examples/src/datasource_geojson_elevated-markers.ts
- @here/harp-examples/src/datasource_geojson_points.ts
- @here/harp-examples/src/datasource_geojson_styling_game.ts
- @here/harp-examples/src/datasource_geojson_visibility.ts
- @here/harp-mapview/lib/MapView.ts
> HARP-14728 Don't add ground plane to geojson

- @here/harp-mapview-decoder/lib/ThemedTileDecoder.ts
- @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts
> MINOR: Fix wrong parameter type in overridden function

- @here/harp-text-canvas/test/FontCatalogTest.ts
> MINOR: Increase timeout for FontCatalogTest.

- .gitlab-ci.yml
> HARP-16532 - Fix github status update script

- @here/harp-olp-utils/lib/OlpCopyrightProvider.ts
- @here/harp-olp-utils/lib/OlpDataProvider.ts
- @here/harp-olp-utils/package.json
- yarn.lock
update here-data-sdk-typescript to latest version (1.11.0)
> OLPRPS-8830: update here-data-sdk-typescript to latest version

- @here/harp.gl/README.md
Signed-off-by: Daniele Bacarella <daniele.bacarella@here.com> …
> MINOR: fixed links to doc in README

- @here/harp-olp-utils/package.json
- yarn.lock
updates olp-sdk-... dependencies to the latest 0.12.0 version
> OLPRPS-8988: update here-data-sdk-typescript to 1.12.0

- @here/harp-datasource-protocol/StyleExpressions.md
- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/lib/ExprEvaluator.ts
- @here/harp-datasource-protocol/lib/ExprInstantiator.ts
- @here/harp-datasource-protocol/lib/ExprPool.ts
- @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-datasource-protocol/lib/operators/MiscOperators.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
- @here/harp-datasource-protocol/test/ExprPoolTest.ts
- @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
- @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts
- @here/harp-vectortile-datasource/test/VectorTileDataProcessorTest.ts
> HARP-16769: Lookup style operator.

- @here/harp-datasource-protocol/lib/Expr.ts
- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
- @here/harp-datasource-protocol/test/ExprTest.ts
- @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
- @here/harp-mapview/lib/ThemeLoader.ts
- @here/harp-mapview/test/ThemeLoaderTest.ts
- @here/harp-mapview/test/resources/baseTheme.json
> HARP-17632: Implements simple style variable definition

- @here/harp-mapview/lib/poi/PoiRenderer.ts
- @here/harp-mapview/lib/text/TextElement.ts
- @here/harp-mapview/lib/text/TextElementsRenderer.ts
- test/rendering/ScreenSpaceRenderingTests.ts
- test/rendering/utils/ThemeBuilder.ts
> HARP-17671: Fixes missing Marker on not loaded icon

- @here/harp-datasource-protocol/lib/Theme.ts
- @here/harp-datasource-protocol/package.json
- yarn.lock
> MAPSJS-3095: Adds support for FlatTheme in JsonSchema generation

- README.md
> DEPRECATION_NOTICE
