@here/harp-examples/src/textcanvas_dynamic.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/poi/PoiRenderer.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-text-canvas/lib/TextCanvas.ts, @here/harp-text-canvas/lib/rendering/FontCatalog.ts, @here/harp-text-canvas/lib/rendering/GlyphTextureCache.ts, @here/harp-text-canvas/lib/rendering/TextGeometry.ts, @here/harp-text-canvas/lib/rendering/TextMaterials.ts, @here/harp-text-canvas/test/TextCanvasTest.ts
* Optimized ``GlyphTextureCache`` internal buffers to only store attributes relevant to glyph copy/clear operations.
* Modified ``TextGeometry`` to be dinamically resized, also reducing the initial allocation size.
=> HARP-5103: Reduce TextCanvas memory usage.

@here/harp-datasource-protocol/lib/Theme.ts
* Exposing InterpolatedPropertyDefinition in harp-datasource-protocol.
* Moved style "attr" inline type defintion to a dedicated "AttributeValue" type.
=> HARP-5167: Expose map theme related types.

package.json, typedoc.json, yarn.lock
* re-add `typedoc-plugin-external-module-map` responsible for cleaning up of layout in our typedoc
* ignore code in `@here/generator-harp.gl`
=> HARP-2104: Fix typedoc module mapping.

README.md
Since the repository is public, we can consume the public icon
Signed-off-by: Harald Fernengel <harald.fernengel@here.com>
=> Consume public build badge in README.md

@here/harp-mapview/lib/ConcurrentWorkerSet.ts, @here/harp-mapview/lib/MapView.ts
* Reduce heap usage, since all workers have a copy of code and data
=> MINOR: Limit default number of decoders to maximum of 4

@here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-utils/lib/GroupedPriorityList.ts, @here/harp-utils/test/GroupedPriorityListTest.ts
* A workaround for situations of massive label overload
* Restricted to dynamic sitiations, not static rendering
* Keeps up interactivity
=> MINOR: Introducing overloaded - handling massive text labels

@here/harp-lines/lib/Lines.ts
Removed unused `N` array.
According to benchmark (https://jsbench.me/igjttyjttb), preallocating array of known size is about 75% faster in Chrome, while performance improvement in FF is negligible.
Signed-off-by: Oleksandr Popov <ext-oleksandr.popov@here.com>
=> Performance improvements for generation of lines geometries.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
TextElementsRenderer is fully initialized and can be used for
label layout only when all font catalogs are loaded.
Introduce `#ready` property and use it to prevent initial
label placement until in MapView until font catalog is loaded.
=> MapView: fix first FrameComplete event.

@here/harp-webtile-datasource/lib/WebTileDataSource.ts
* ensure that webtiles texture is `disposed` when we're disposing Tile
* invalidate memory resource usage after texture is loaded, so tile cache can has up-to-date view of tiles size
=> HARP-5263: Fix high GPU usage with WebTileDataSource.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts
**General description of a fix:** camera pitch calculation behaves much more precise rather than angle between quats.
=> HARP-5193: ZoomLevel replace with more precise calculation

@here/harp-map-controls/lib/MapControls.ts
Modify the ``easeOutCubic`` function used in ``MapControls`` to snap to desired values when different between desired and current value is smaller than ``EPSILON``.
=> HARP-5128: Fix zoom for small steps.

@here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
* Set technique to "none" for all 'urban_area' layers.
Those layer were not applied previously, but after #359
they get applied, which technically is the right behavior.
I am setting the technique to "none" so we still have the structure for
urban areas in place, in case we want to style them in the future.
=> MINOR: Visual regression fix after #359 for berlin based themes.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts
- Cache eviction is now controlled by when the tile was last requested,
and not whether the tile is visible.
- "visibleTiles" renamed because it was a bit confusing as there are
tiles which are not visible in the visibleTiles list because they are
still loading.
=> Cache eviction happens when last requested

@here/harp-mapview/lib/DataSource.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts
This allows to update and read this property via MapView and thus
control level offsets in demo app.
WebTileDataSource should use default level offset set to -1 which
corresponds to 512 tile sizes used.
=> HARP-5371: DataSource exposes getter/setter for storage level offset.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts
Implement screen space sizing (pixelToWorld ratio) based on camera
focal length and camera target distance.
Formula allows to render objects in exact screen space size given in
pixels for the objects close to camera focus point, objects closer or
farther then that are perspective scaled acordingly.
Formula is camera tilt and roll angle independent as also does not require
any raycasting, so works even with camera oriented to sky.
=> HARP-5286: Styling size metric based on screen space pixel sizes.

@here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
Themes fix, the styles should not filter buildings. Remove the `$level`
condition from all styles relevant for the buildings polygon data.
=> HARP-5484: Buildings should be shown at all available storage levels.

.travis.yml
The script assumes that the repository versions and the versions in
npmjs.com match, which is not always true, for example after we bumped
the versions in preparation for publishing.
Since this is blocking publishing, we need to remove it until we find a
more correct solution to this problem.
=> Remove faulty test-npm-packages.sh check

.travis.yml, @here/harp-examples/webpack.config.js, package.json, scripts/doc-snippets.ts
* Exclude .gitignore and .npmignore when building examples
* Copy LICENSE and files under docs/ folder before running typedoc
=> HARP-5577 Simplify travis configuration

@here/harp-mapview/lib/Tile.ts
This is needed to make sure that three.js objects that are added to the scene by the are depth tested properly.
=> MINOR: Enable depth write for ground plane.

@here/harp-datasource-protocol/lib/Theme.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
* TextStyle was defined twice, but each TextStyle definition has
a different purpose. Renamed TextStyle to TextStyleDefinition inside
the Theme definition. TextStyleDefinition defines the TextStyle resource,
where TextStyle defines one instance of a TextStyle for an item on the map.
=> MINOR: Resolved double TextStyle definition in Theme definition

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
with fill technique in case of data containing "min_height"
Signed-off-by: Markus Zell <markus.zell@here.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/harp.gl/433)
=> HARP-5629: fix flying pieces of building footprints

@here/harp-map-controls/lib/MapControlsUI.ts
Added zoom level show/input options
Added option for disable default CSS styling for easier overriding of CSS styles
=> HARP-5599 Add zoom level display to map editor

@here/generator-harp.gl/generators/app/templates/decoder.ts
The missing tiler service was leading to the geojson data provider to not work.
It would be hard for the user to know these details, so the tiler service should always be started.
=> MINOR: Add missing initialization of the tiler service in Yeoman generator

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-examples/src/hello_textured_areas.ts, @here/harp-mapview-decoder/lib/TileDecoderService.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/DepthPrePass.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/test/TileCreationTest.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts, @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
* Introduced textureCoordinateType for "extruded-polygon" and "standard" technique
* Removed obsolete "standard-textured" technique
=> HARP-5678: Added texture coordinates to extruded-polygon technique

.travis.yml
Due to limitations of the GitHub API, pushing more than three tags at a
time does not trigger Travis CI's tag filter.
Thus, we must change our 'release' trigger. For now, pushing to a
special 'release' branch will trigger releases. The RM should only ever
fast-forward changes into the 'release' branch, which will automagically
trigger a release to github-pages and to npmjs.com
=> HARP-5577: Only publish from 'release' branch

@here/harp-omv-datasource/lib/OmvRestClient.ts
Add an XYZ Space as an APIFormat to be used within OmvDataSource. This enables a developer to visualize data from an XYZ Space, using the .mvt endpoint from XYZ. Example endpoint:
```
https://xyz.api.here.com/hub/spaces/your-space-id/tile/web/{z}_{x}_{y}.mvt?access_token=your-access-token
```
Example of adding data from XYZ Space to map:
```
const xyzDataSource = new OmvDataSource({
baseUrl: "https://xyz.api.here.com/hub/spaces/2vDrakce/tile/web",
apiFormat: APIFormat.XYZSpace,
styleSetName: "geojson",
maxZoomLevel: 17,
authenticationCode: "your-access-token"
});
map.addDataSource(xyzDataSource);
```
=> MINOR: Add XYZ Space as APIFormat

@here/harp-examples/README.md, @here/harp-examples/src/datasource_satellitetile.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts
Add `ppi` to request only if explicitly initialized with a value, otherwise satellite tiles do not work.
Change valid zoom levels of web tiles from 1 to 20.
=> HARP-5900 Add satellite tiles example

@here/harp-datasource-protocol/lib/Techniques.ts
Reverts heremaps/harp.gl#470
As mentioned by @ninok, this isn't needed.
=> Revert "HARP-5432 Normal vectors are now the projection's surface normal."

@here/harp-omv-datasource/lib/OmvUtils.ts
Geojson and custom features are meeting the `SharedArrayBuffer` check, which is undefined everywhere but in Chrome.
=> HARP-5847: Remove SharedArrayBuffer reference.

@here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
The return statement isn't used, hence removing to reduce confusion.
=> HARP-5432 Removing return statement

@here/harp-mapview/lib/Tile.ts
The z component is required to do ray casting on the CPU, however on the
GPU we use a displacement map to do this, so we zero the z value.
=> HARP-5432 Remove z component from mesh

@here/harp-examples/src/hello_js-bundle.html
Use, "local" fonts and resources in hello / js-bundle.
We cannot use already published themes in our example because them at best may be outdated, in worst case incompatible.
=> Fix broken hello - js_bundle example.

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-datasource-protocol/lib/IMeshBuffers.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Based on the results of #507 , fixed batching for ``fill`` outlines, which were previously rendered with a unique draw call per-feature.
=> HARP-5760: Outline Batching bugfix.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/package.json, @here/harp-geojson-datasource/lib/GeoJsonTile.ts, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, yarn.lock
Extend json scheme to support editing in monaco editor/map-editor
Fix theme and technique interfaces;
Fix priority interpolation;
Add color format to enable colorpicker in editor;
Export defaultSnippets to json schema;
Cleanup berlin_tilezen theme files;
Signed-off-by: Oleksii Kanishchev <ext-oleksii.kanishchev@here.com>
=> HARP-5717: Extend json schema

@here/harp-geoutils/lib/projection/SphereProjection.ts, @here/harp-geoutils/test/ProjectionTest.ts
Reimplement `SphereProjection.reprojectPoint` to support fast
reprojection from WEB Mercator coordinates to spherical globe.
=> HARP-6097: Project directly from mercator coords to spherical globe.

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts, @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts
Use the winding of the 1st ring of a polygon feature
to distinguish between inner and outer rings.
=> HARP-6160: Improve the classification of outer/inner rings.

@here/harp-omv-datasource/lib/IGeometryProcessor.ts, @here/harp-omv-datasource/lib/OmvData.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts, @here/harp-omv-datasource/lib/OmvTileInfoEmitter.ts, @here/harp-omv-datasource/lib/VTJsonDataAdapter.ts, @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
Changed the OMV decoder and its helper classes to work in webmercator
space and use `Projection.reprojectPoint` to fast reproject between
projected coordinates. This change should avoid a huge number of
conversions from WEB Mercator to geo space and then back to web mercator
or globe.
=> HARP-6151: Refactored the OMV decoder to work in webmercator space.

@here/harp-geoutils/lib/projection/SphereProjection.ts
To correctly incapsulate the projection APIs, the symbol
`sphereProjection` should be exported as type `Projection` and not as
`SphereProjection`.
=> MINOR: Restrict the type of the exported symbol sphereProjection.

@here/harp-geometry/lib/SphericalGeometrySubdivisionModifier.ts, @here/harp-geometry/lib/SubdivisionModifier.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts
This change generalizes the subdividion modifier so it can be used
to subdivide geometries in their world space.
Subdividing in the world space of the data ensures that no geometry
crossing the tile boundaries is introduced while subdividing, also
it makes possible to generate texture coordinates for the new vertices.
=> HARP-6099: Subdivide tiles in the world space of their tiling scheme.

@here/harp-mapview/lib/MapView.ts
Avoid calling ``MapViewUtils.getBrowserLanguages()`` implicitly when no language settings are set, since ``navigator.languages`` and ``navigator.language`` return unconsistent values across browsers (i.e. chrome treats your configured languages as an array and doesn't care about which one you've actually set).
=> HARP-5949: Default language support.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
The property ``exponent`` was not properly being passed to the THREE.js interpolants from the theme.
=> HARP-6210: Exponential interpolation bugfix.

@here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts
Clear cache when changing style set.
=> HARP-6101: Clear loader cache in TileDataSource(s).

@here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json, @here/harp-map-theme/resources/poi_table_maki.json, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/poi/PoiTableManager.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
All open-source themes utilizes maki-icons set created with internal
tool-chain (harp-texture-atlas-tools).
TODO:
- move icon texture name solving code from OmvDecodedTileEmitter to more
generic parts,
- clear m_tileLoaderCache in all classes that inherits from TileDataSource.
=> HARP-5557: Support for rendering POI icons on every map theme.

@here/harp-geoutils/lib/coordinates/GeoCoordinates.ts, @here/harp-geoutils/test/GeoCoordinatesTest.ts, @here/harp-mapview/lib/MapView.ts
One more problem was encountered while debugging this task:
- `GeoCoordinates#normalized()` method was not supporting negative values (like -711, -400, ...). **Problem was solved**.
Introduced normalized value for `MapView#geoCenter` accessor.
=> HARP-5755: Fix normalization bug & use normalized coord in geoCenter

README.md, docs/GettingStartedGuide.md
Now that harp.gl is getting some publicity (conferences, workshops, [blog posts](https://developer.here.com/blog/introducing-harp.gl-3d-vector-maps-for-the-web), [tutorials](https://developer.here.com/tutorials/harpgl)), the readme should prioritize information about how to quickly get started with the api.
=> MINOR: update readme and getting started guide to include simple bundle

@here/harp-mapview-decoder/lib/TilerService.ts
Fixes
```
Error: DataCloneError: Failed to execute 'postMessage' on
'DedicatedWorkerGlobalScope': #<Promise> could not be cloned
```
error caused introduced in #526.
=> Fix GeoJsonDataProvider caused by improper async usage in TilerService.

@here/harp-datasource-protocol/index.ts, @here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/test/InterpolationTest.ts, @here/harp-examples/src/techniques_interpolation.ts, @here/harp-mapview/lib/ColorCache.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/RoadPicker.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
* Added support for ``StringEncodedNumeral``, which are number values which can be specifed as strings (i.e. colors, distances in pixel, etc.).
* Improved the ``TechniqueParams`` typings to be more strict with the new ``color`` and ``length`` types.
* Implemented mix interpolation between:
- Pixels and meter values (``metricUnit`` is now deprecated).
- Hex, rgb and hsl colors (interpolation is performed internally in HSL space for better results).
* Refactored the ``getPropertyValue`` API to always return ``number`` (and also handle ``length`` and ``color`` interpolation properly).
=> HARP-5574: StringEncodedNumeral support.

@here/harp-map-controls/lib/MapControlsUI.ts
This is a proposal for new map controls button style.
The white button style had slightly too much contrast and was distracting from the map in my opinion. I ported the dark style from Arnaud's product to harp.gl. This not only reduces the contrast of the buttons in comparison to the base map, but also adds a *tiny* bit of unification between harp.gl and the other product.
Please discuss what you like better.
Previous button style:
New button style:
=> MINOR: New CSS for map controls button

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts
fadeNear technique property was set to fadeFar local variable.
=> Minor: Fix copy-paste error in TileGeometryGenerator.createTextElements

@here/harp-examples/src/datasource_webtile.ts, @here/harp-examples/src/datasource_webtile_globe.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts, @here/harp-webtile-datasource/test/WebTileTest.ts
Add enums for `ppi` and `resolution`.
Add checks for invalid combinations of `ppi`, `resolution` and `tileBaseAddress`.
Add test cases for all of the above.
=> HARP-6453 Control zoom level for WebTileDataSource

@here/harp-webtile-datasource/lib/WebTileDataSource.ts, @here/harp-webtile-datasource/test/WebTileTest.ts
When creating a default `WebTileDataSource` with aerial tiles there is an error thrown because of wrong usage of `ppi`.
=> HARP-6453 Fix webtile example

@here/harp-map-controls/lib/MapControls.ts
Setting `panInertiaDampingDuration` or `zoomInertiaDampingDuration` to `0` was breaking the controls.
=> HARP-5197: Fix inertia durations of 0.

docs/docs/index.html, docs/examples/index.html, docs/index.html, docs/js/index.js
* Use `www.harp.gl` domain for all documentation and examples so that we can have `https` and remove temporary s3 and gh-pages urls.
* Rename `master` as `latest` to make it more accessible for users on the main website.
* Reduce the visible distance to 1500m
* Add (c) to footer
=> Use new www.harp.gl domain

@here/harp-map-controls/lib/MapControls.ts
The code for touches is handled differently. In mouse, being in the voids stops further calculations, while with touches we still want to explore the case of 2 or 3 fingers, hence a different solution.
=> HARP-6559: Fix touch outside globe.

@here/harp-map-controls/lib/MapControls.ts
This PR fixes broken zoom when viewing a flat projection on a touch device, when zooming with the button after zooming with 2 fingers. The internal `this.m_currentZoom` was not updated by the method used by the touches.
=> HARP-6574: Fix touch zoom not updating known zoomLevel value.

@here/generator-harp.gl/package.json, @here/harp-atlas-tools/package.json, @here/harp-datasource-protocol/package.json, @here/harp-debug-datasource/package.json, @here/harp-examples/package.json, @here/harp-features-datasource/package.json, @here/harp-fetch/package.json, @here/harp-geojson-datasource/package.json, @here/harp-geometry/package.json, @here/harp-geoutils/package.json, @here/harp-lines/package.json, @here/harp-lrucache/package.json, @here/harp-map-controls/package.json, @here/harp-map-theme/package.json, @here/harp-mapview-decoder/package.json, @here/harp-mapview/package.json, @here/harp-materials/package.json, @here/harp-omv-datasource/package.json, @here/harp-test-utils/package.json, @here/harp-text-canvas/package.json, @here/harp-transfer-manager/package.json, @here/harp-utils/package.json, @here/harp-webtile-datasource/package.json, @here/harp.gl/package.json, package.json
Using HTTPS allows users to clone the repository using tools like OSS Review Toolkit without authentication.
=> Change repository url from SSH to HTTPS

@here/harp-features-datasource/lib/FeaturesDataSource.ts, @here/harp-geoutils/lib/tiling/SubTiles.ts, @here/harp-geoutils/lib/tiling/TileTreeTraverse.ts, @here/harp-geoutils/test/SubTilesTest.ts, @here/harp-mapview/lib/BackgroundDataSource.ts, @here/harp-mapview/lib/CameraMovementDetector.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/FrustumIntersection.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/BackgroundDataSourceTest.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/VisibleTileSetTest.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts
There are 3 commits in this PR:
1. Move creation of background area geometry to a separate data source: BackgroundDataSource.
2. Fix a bug found in TileTreeTraverse.subTiles() where it returns invalid tiles for halfquad tile subdivision scheme.
3. Add tile intersection caching so that intersection tiles are reused for data sources with same tiling scheme. Otherwise, with the addition of BackgroundDataSource we would be calculating the same tile intersections at least twice.
=> Harp 5722 background data source

@here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/geometry/PhasedTileGeometryManager.ts
Phased loader can't load generated tiles, and reports they are not finished, producing continuous redraws.
=> HARP-6638: Continuous redraws in MapView

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-datasource-protocol/package.json, @here/harp-geojson-datasource/lib/GeoJsonDecoder.ts, @here/harp-geojson-datasource/package.json, @here/harp-geometry/lib/OrientedBox3.ts, @here/harp-geometry/test/OrientedBox3Test.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
Change the semantics of `Tile.boundingBox` to use oriented bounding
boxes to represent tile world bounds. This change should improve
the precision of tile geometries projected on spherical globe,
because the center of the tile will be closer to the surface.
=> HARP-6204: Use OBBs instead of AABBs to represent tile bounds.

@here/harp-mapview/lib/BackgroundDataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/test/BackgroundDataSourceTest.ts, @here/harp-mapview/test/MapViewTest.ts
So the tiling scheme is pre-defined or passed via mapview options. But background tiles still needs to be same size or smaller than the regular tiles to look good.
=> HARP-6669: BackgroundDataSource can pick wrong tiling scheme

package.json, yarn.lock
Among others, typedoc uses new typescript.
See https://github.com/TypeStrong/typedoc/releases/tag/v0.15.0
=> Upgrade typedoc to 0.15.0.

@here/harp-geoutils/lib/tiling/SubTiles.ts, @here/harp-geoutils/lib/tiling/TileTreeTraverse.ts, @here/harp-geoutils/lib/tiling/TilingScheme.ts, @here/harp-geoutils/package.json, @here/harp-geoutils/test/SubTilesTest.ts, @here/harp-geoutils/test/TileTreeTraverseTest.ts, @here/harp-mapview/lib/AnimatedExtrusionHandler.ts, @here/harp-mapview/lib/FrustumIntersection.ts, @here/harp-mapview/lib/VisibleTileSet.ts
Signed-off-by: Oleksii Kanishchev <49714978+okanishchev@users.noreply.github.com>
Fixed SubTiles to support custom subdivision schemes;
Force SubTiles to return an iterator and as result avoid using IIFE while iterating over SubTiles.
=> HARP-6763: SubTiles generate bad tile keys on custom subdivision schemes

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/TileInfo.ts, @here/harp-datasource-protocol/test/ExprTest.ts, @here/harp-geojson-datasource/lib/GeoJsonParser.ts, @here/harp-omv-datasource/lib/OmvData.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
This change removes 'undefined' from the possible types that
the evaluation of expression can generate. That is, 'undefined'
values when evaluating expressions should be treated as errors.
=> HARP-6781: Restrict the values manipilated by style expressions.

@here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json, @here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
This presents new approach for distance scaling based on camera focus
point distance in opposite to near/far planes relation. Because new
camera clip planes evaluators may change near/far positions dynamically
the old approach does not apply and may provide unacceptable user
experience.
Moreover distance based rendering constraints (limits) are now improved
by providing different constraint (still far plane based) for text and
POI labels. Hardcoded values are now removed.
* [coding …
=> HARP-6798: Fix labels rendering distance constraints, improve scaling.

@here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/ConcurrentDecoderFacade.ts, @here/harp-mapview/lib/ConcurrentTilerFacade.ts
- Users may now also override the MapView default worker count when
instantiating a TileDataSource
=> HARP-6776: Allow worker count to be set independently per decoder bundle

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewFog.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/poi/PixelPicker.ts, @here/harp-utils/lib/MathUtils.ts
MapViewFog is now tilt angle dependent and should work with any kind of
projection type. Moreover it allows to define both vertical (looking top-
down) and horizontal density. This values may be moved in future to the
Theme fog definition.
This change is required in order to support dynamic frustum (near/far
planes) changes, because old implementation is only far plane related
and does not support precise far plane setup just below the ground level.
* [coding …
=> HARP-6811: Improve map view fog calculation.

@here/harp-mapview/lib/DepthPrePass.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/overlayOnElevation.ts, @here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/SolidLineMaterial.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
First implementation of extruded building overlay without creating sockets. All building vertices are displaced using the elevation map texture.
Tested on fake terrain since ElevationProvider does not provide yet elevation maps for zoom levels where extruded buildings are visible.
=> HARP-6773: Extruded building overlay without sockets.

@here/harp-geoutils/lib/tiling/TileKeyUtils.ts, @here/harp-mapview/lib/ElevationProvider.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/TileGeometryManager.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
getDisplacementMap and getHeight methods in TerrainElevationProvider do a linear search over all terrain tiles cached in the VisibleTileSet until the tile with the requested key/geopoint is found.
This change improves this by getting directly the proper tile from the LRU tile cache.
For getHeight, the tile key is calculated from the given geopoint using terrainSource.getTilingScheme().getTileKey().
=> HARP-6512 Remove linear tile search from TerrainElevationProvider

@here/harp-datasource-protocol/lib/WorkerServiceProtocol.ts, @here/harp-geojson-datasource/lib/GeoJsonDataProvider.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/ConcurrentWorkerSet.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/WorkerBasedDecoder.ts, @here/harp-mapview/lib/WorkerBasedTiler.ts, @here/harp-mapview/lib/workers/WorkerBootstrapDefs.ts, @here/harp-mapview/lib/workers/WorkerLoader.ts, @here/harp-mapview/test/ConcurrentWorkerSetTest.ts, @here/harp-mapview/test/FakeWebWorker.ts, @here/harp-mapview/test/WorkerLoaderTest.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-test-utils/lib/TestUtils.ts, @here/harp-test-utils/package.json
Followup of #760 
* `ConcurrentWorkerSet#connect` now
* properly waits for all workers (and rejects if any of them failed)
* throws meaningful message if trying to connect to unknown service
* timeouts if created worker doesn't respond at all
* implementations of `DataSource`/`DataProvider` pass `connect` failures up
to `MapView`
* `MapView#addDataSource` handles and logs `DS#connect` errors
* `OmvDataSource#connect` shows hint, if `omv-decoder` service is not
registered in decoder
* `GeoJsonDataProvider` shows hint in console, if `omv-tiler` service
is not registered in decoder
TODO:
=> HARP-7009: Improve error handling when connecting to datasource

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Interpolator related code moved away from `StyleSetEvaluator`.
Only code move, no functional change.
(Needed by #695)
=> Move InterpolatedProperty handling outside of StyleSetEvaluator.

@here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts
ThemeLoader resolves `["ref", ...]` expressions embedded within other expressions.
=> HARP-6556: Support for 'ref' in expressions.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
The newly introduced property 'layer' can be used to restrict the
matching of techniques to a specific layer. For example, the following
two style conditions are equivalent:
{
"when": [
"all",
["==", ["get", "$layer"], "water"],
["==", ["get", "$geometryType"], "polygon"]
],
...
}
{
"layer": "water",
"when": [
"all",
["==", ["get", "$geometryType"], "polygon"]
],
...
}
=> HARP-7107: Introduce the property 'layer'.

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/MapMeshMaterials.ts
Signed-off-by: Andrés Valencia Téllez <ext-andres.valencia-tellez@here.com>
Improved present z-fighting by:
* Fixing extrusionFeature attribute copy (broken depth pre-pass for non animated buildings).
* Removing the polygonOffset applied to meshes and applying instead a VS depth offset for edge geometries.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add …
=> HARP-6886: Z-fighting improvements.

@here/harp-omv-datasource/test/MapViewPickingTest.ts
Temporarily disable flaky picking tests.
Travis Ci is broken since unit-tests for picking PR: https://github.com/heremaps/harp.gl/pull/733
Example:
master https://travis-ci.com/heremaps/harp.gl/jobs/234907907 (restarted 3 times, always failure)
random PR: https://github.com/heremaps/harp.gl/pull/796/checks?check_run_id=223384743
Interesting fact - they fail only in Travis CI (unit-tests are "passing" in Github and in internal CI).
Nevertheless, i believe these tests are broken as async callbacks from TextElementsRenderer are crossing test boundary.
=> Disable flaky picking tests.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/package.json, @here/harp-lines/lib/Lines.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-materials/lib/ShaderChunks/LinesChunks.ts, @here/harp-materials/lib/SolidLineMaterial.ts, @here/harp-materials/package.json
Added caps support for lines.
The following types are supported now:
"Square", "Round", "None", "TriangleOut", "TriangleIn"
=> HARP-6249: Caps for lines endings

@here/harp-examples/src/datasource_geojson_choropleth.ts, @here/harp-geojson-datasource/lib/GeoJsonDataProvider.ts
GeoJsonDataProvider waits for data to be tiles, before reporting its
readiness via `connect`.
Removed necessity for workarounds like this in examples:
mapView.addDataSource(geoJsonDataSource).then(() => {
geoJsonDataSource.setStyleSet(theme.style.something);
});
used always with this data provider.
=> GeoJsonDataProvider waits for data.

.github/workflows/ci-linux.yaml, .github/workflows/ci-windows.yaml, @here/harp-test-utils/lib/TestDataUtils.ts, @here/harp-test-utils/lib/TestDataUtils.web.ts, @here/harp-test-utils/package.json, @here/harp-utils/package.json, @here/harp-utils/test/PerformanceTimerTest.ts, package.json, test/LicenseHeaderTest.ts, yarn.lock
* github actions windows deserves it's own job definition - reenable most checks for windows
* `node-fetch` on windows, needs proper `file://` URL
* increase `LicenseHeaderCheck` as `glob` is slower on windows
* `PerformanceTimer#now` test fixed
=> Support for test execution on windows.

@here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- Added custom shaderChunk for extruded buildings normals.
- Extruded buildings normals on spherical projection look correct after this change. …
=> HARP-6982: Correct normals on spherically projected extruded buildings.

@here/harp-omv-datasource/test/MapViewPickingTest.ts, @here/harp-omv-datasource/test/resources/geoJsonData.ts
Reenabled picking tests except for text picking emulation.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots …
=> MINOR: Picking tests update.

@here/harp-mapview-decoder/lib/GeoJsonTiler.ts
`geojsonvt` returns `null` for tiles with no data, so ensure we
return empty object in this case.
Among others, removes spurious errors from test logs like this:
```
TileLoader: [geojson]: failed to load tile 371506851 TypeError: Cannot read property 'byteLength' of null
at TileLoader.onLoaded (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/lib/TileLoader.ts:258:42)
at dataProvider.getTile.then.payload (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/lib/TileLoader.ts:230:22)
```
=> GeoJsonTiler fix for empty tiles

@here/harp-examples/src/datasource_geojson_styling_game.ts, @here/harp-examples/src/getting-started_open-sourced-themes.ts, @here/harp-features-datasource/lib/FeaturesDataSource.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts
`TileDataSource` and `OmvDataSource` now automatically updates
owned tiles when decoder configuration (style, languages, options)
is changed.
Additionally, configure decoder only after successfull `#connect`.
=> HARP-6728: Cleanup configure/setStyleSet flow in TileDataSource

@here/harp-mapview/lib/MapView.ts
Disable phased loading until the tile's flickering issue is fixed (https://github.com/heremaps/harp.gl/pull/812)
=> HARP-7113: Make phased loading disabled by default

@here/harp-mapview/lib/MapView.ts
The default size of just 20MBs is too small to efficiently renderer
city centers with many extruded buildings.
=> MINOR: Tune the size of the default tile cache.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
Implemented !in and !has as operator aliases.
=> HARP-7278: Add support for !in and !has operators.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
Classify the styling rules based on the requested geoemtry type, and
make use of requested $geometryType to filter the style conditions.
=> MINOR: Filter techniques by $geometryType.

@here/harp-mapview/lib/RoadPicker.ts, @here/harp-mapview/lib/Tile.ts
Support for continous zoom level inteprpolation in RoadPicker.
Makes road picking accurate when tilting map.
Width properties of `solid-line`s can be dynamically interpolated
in scope of one zoom level, so `widths` of road data have to be
interpolated based on actual zoom level.
Improvement will be visible once #734, is merged.
=> Support for continous zoom level inteprpolation in RoadPicker.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ITileDecoder.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/WorkerDecoderProtocol.ts, @here/harp-datasource-protocol/lib/operators/MathOperators.ts, @here/harp-datasource-protocol/test/ExprTest.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-mapview-decoder/lib/ThemedTileDecoder.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview-decoder/lib/TileDecoderService.ts, @here/harp-mapview/lib/BackgroundDataSource.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/lib/WorkerBasedDecoder.ts, @here/harp-mapview/test/ThemeLoaderTest.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
Support for 'compile'-time' (`Expr.fromJSON`) reference resolving.
MapView changes:
* `DataSource.setTheme` revived as main theming interface for
datasources because decoder based datasources require
`theme.definitions` too
* `Definitions` are communicated from `MapView` to decoder
* `StyleSetEvaluator` now resolves references using `Expr.fromJSON`
* `ThemeLoader` doesn't resolve references by default
* (minor) BackgroundDataSource reacts to theme change
Rationale
We expect that objects and expressions in `Theme.definitions` can be big and this should be sent as one to decoders and we should reuse their instances to save memory.
=> HARP-7103: Support for 'ref' in Expr.fromJSON

@here/harp-mapview/lib/MapView.ts
Fixes getter to properly reflect current situation, before it would happen
that anti-aliasing was enabled due to pixelRatio, but getter returns false. …
=> MINOR: Fix MapView.nativeWebglAntialiasEnabled property getter.

@here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/DataSource.ts
TileDataSource shouldn't update styleset in `setTheme` if theme doesn't
define styleset with `styleSetName` of datasource.
This fixes backwards compatibility bug introduced in #796.
Among others fixes `datasource_features_polygons` demo.
=> Fix theme handling in TileDataSource.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/poi/PoiManager.ts
Create `TextElementsRenderer` only if there's actual text elements created for any of the tiles, or overlay text exists. The `MapView` knows if there's text elements on the tile from the `Tile::hasTextElements()` that is checked for every tile every frame before one is found. Then the renderer creation is delayed to avoid affecting frame time.
If `MapView`'s theme was changed, remove text renderer completely. That allows to create new renderer with font catalogs and text styles changed if any text will be rendererd. And disable text rendering at all if none.
Has a drawback of loading font catalog files (json and png) every time the theme changes, even if they are the same. Not really crucial as files are taken from browser cache, but still.
Also there's a small overhead if no text is …
=> HARP-7201: All examples from Labeling section are broken

README.md
One of our best differentiators is missing, hence adding mention of TypeScript.
=> MINOR: Add link to TypeScript

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/VisibleTileSet.ts
Because (by default) all buildings height is "projected" to preserve
consistency with other map features, we need to take it into account
when evaluating near/far planes based on ground elevation.
This patchset improves evaluation of clip planes when buildings height is
added to terrain elevation.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests …
=> MINOR: Account for height geo-projection when calculating clip planes.

.github/workflows/ci.yaml, .travis.yml, package.json, test/ImportTest.ts, test/LicenseHeaderTest.ts
* alias `yarn code-rules-tests` for code quality tests in `test/* folder`
* alias `pre-check` for them and `tslint` and `prettier` to align
experience with CI `Pre check` step
* remove timeouts from code quality check, as they are sometimes very
heavy and timeout is not a failure, run them with `--no-timeouts`
* add `--forbid-only` to `mocha` test runs to prevent accidental green,
but actually not ran tests
=> Test related tweaks.

@here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts, @here/harp-mapview/test/resources/baseTheme.json, @here/harp-utils/index.ts, @here/harp-utils/lib/UrlPlatformUtils.ts, @here/harp-utils/lib/UrlPlatformUtils.web.ts
Fix double problems with double theme loading by resolving theme `url`
property to absolute url at first load.
Extra: for inline themes, assign page base url on initial load.
=> Improve handling of url in ThemeLoader.

.github/workflows/ci.yaml, .nycrc, .travis.yml, @here/harp-geoutils/test/TileTreeTraverseTest.ts, package.json, yarn.lock
Coverage analysis for tests in node.
* `test-cov` target added that runs Node.Js tests under `nyc` to generate
coverage report.
* `cov-report-html` script added to generate coverage report in
`coverage/`
* CI runs tests with coverage analysis and saves report as artifacts
=> Coverage analysis for tests in node

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts, @here/harp-datasource-protocol/lib/TechniqueAttr.ts, @here/harp-datasource-protocol/test/InterpolationTest.ts
Also, remove the requirement of InterpolatedProperty to store
zoomLevels and values as Float32Array.
=> HARP-6527: Support discrete interpolators of arbitrary types.

@here/harp-utils/lib/UrlUtils.ts
The default font catalog was loading with an incorrect link when a project whose opened
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running …
=> MINOR: Fix missing labels in 'xyz-project' example

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvUtils.ts, @here/harp-omv-datasource/test/OmvDecodedTileEmitterTest.ts
Decoding performance improvement, followup of #852, #853, #881.
`world2tile` is executed for every point in tile, allocating less mem gives very slight improvement. 
~ 5.5 -> 4.5% of whole `OmvDecoderPerformanceTest`.
=> Decrease number of allocations in world2tile.

@here/harp-datasource-protocol/lib/ViewRanges.ts, @here/harp-mapview/lib/AnimatedExtrusionHandler.ts, @here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts, test/ImportTest.ts
Remove circular dependency between material & mapview packages.
Fix `ImportCheck` tests, so bogus imports from `../../` are marked as errors.
=> Remove circular dependency between material & mapview packages.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/package.json, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-omv-datasource/lib/OmvDataFilter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts, @here/harp-omv-datasource/lib/StyleSetDataFilter.ts, @here/harp-test-utils/lib/ProfileHelper.ts, README.md, package.json, test/performance/LinesPerformanceTest.ts, test/performance/OmvDecoderPerformanceTest.ts, test/performance/package.json, webpack.tests.config.js
Skip processing of layer/features not selected by styleSet.
Basing on changes from #852, we can use pre-filtered styleSet
lists to check if particular layer/geometryType combination can
be completly ignored before decoding OMV/GeoJson data.
ProfileHelper and tests are from #875
=> Skip processing of layer/features not selected by styleSet.

@here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
Also, returns the default value of the 'step' when the input evaluates
to 'null'.
=> MINOR: Check the number of arguments before evaluating 'step'.

.github/workflows/ci.yaml
Following warning will be fixed with this change:
> Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use node-version instead
=> MINOR: Fixed Github CI warning

@here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
* In tile update scenario, ensure that we clear and create geometry in very same frame to prevent flickering in scenarios like style update.
* Fix regression which caused `MapView.markTilesDirty` to clear cache from tiles owned other datasources.
=> Fix flickering when updating style.

scripts/publish-packages.sh
We need to tell `lerna` to tag as latest only the non-alpha packages.
Using [verdaccio](https://github.com/verdaccio/verdaccio) locally I was able to test and verify the following behavior with [this sample project](https://github.com/musculman/yarn-workspaces-example)
1. do changes
2. run `lerna version preminor` to create a _minor alpha_ version
3. `lerna publish -y from-git --pre-dist-tag alpha` publishes the expected _minor alpha_ packages
4. do some more changes
5. run `lerna version minor` to create a _minor_ version
6. `lerna publish -y from-git --pre-dist-tag alpha` publishes the expected _minor_ packages
=> HARP-7579 Add pre-dist-tag to publish

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
Improve the StyleSetEvaluator support for constant expressions.
This change improves the processing of styling expressions that
don't depend on data feature properties, e.g interpolations
defined using the "interpolate" operator instead of the deprecated
object-like syntax.
=> Sse improved constexpr

@here/harp-mapview/lib/text/RenderState.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementType.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/TextElementsRendererTest.ts
So far the state of a text element was held in the Tile. This is generally wrong from the design point of view, a tile shouldn't hold any state related to rendering.
Furthermore, this meant that the state of a label was not reachable once the tile was not in the visible tile list anymore (e.g. during zoom level changes). This made impossible reusing a label state when a new label corresponding to the same map object in a different zoom level is rendered.
=> HARP-7373: Move text element render state to TextElementState.

.github/workflows/ci.yaml
Disable node-js tests or GithubActions / Windows as they are not reliable.
=> HARP-7670: Fix CI for windows

@here/harp-mapview/lib/MapView.ts
Fix condition, where PoiTableManager is last one to be ready.
Before fix, finish of PoiTableManager didn't trigger update and thus
there was no change to observer, first complete frame.
Followup of #917
=> HARP-6638: Fix MapView.FrameComplete event.

@here/harp-mapview/lib/text/TextElementsRenderer.ts
textIsOptional = false was not handled properly (i.e. the icon was rendered without text).
In addition the rendering was never finished (infinite animation loop)
=> HARP-7356: Fix textIsOptional property

@here/harp-examples/src/datasource_custom.ts, @here/harp-examples/src/datasource_xyzmvt.ts, @here/harp-examples/src/getting-started_hello-world_js-bundle.html, @here/harp-examples/src/getting-started_hello-world_npm.ts, @here/harp-examples/src/getting-started_open-sourced-themes.ts, @here/harp-examples/src/rendering_post-effects_all.ts, @here/harp-examples/src/styling_extend-a-theme.ts, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json, @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
Show extruded buildings only when the zoom level is greater than 15.
=> HARP-7271: Tune the rules for decoding the extruded buildings.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/ExprPool.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/operators/ArrayOperators.ts, @here/harp-datasource-protocol/lib/operators/CastOperators.ts, @here/harp-datasource-protocol/lib/operators/ColorOperators.ts, @here/harp-datasource-protocol/lib/operators/ComparisonOperators.ts, @here/harp-datasource-protocol/lib/operators/FeatureOperators.ts, @here/harp-datasource-protocol/lib/operators/FlowOperators.ts, @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/lib/operators/MathOperators.ts, @here/harp-datasource-protocol/lib/operators/MiscOperators.ts, @here/harp-datasource-protocol/lib/operators/ObjectOperators.ts, @here/harp-datasource-protocol/lib/operators/StringOperators.ts, @here/harp-datasource-protocol/lib/operators/TypeOperators.ts, @here/harp-datasource-protocol/test/ExprTest.ts
Prefer to pass the CallExpr instead of just the list of actual
arguments. This change will allow the operators to use properties
stored together with the CallExpr node. Also, it makes it possible
for evaluators to return the CallExpr node when partially evaluating
expressions.
=> Change signatures of the style operator descriptors.

yarn.lock
Threejs was removed in the yarn.lock with the ThreeJS update, this brings it back.
=> MINOR: Fix yarn.lock.

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-materials/lib/EdgeMaterial.ts
Depth offset was multiplied by homogeneous 'w' coordinate, which results
in constant offset in NDC space, although it seems to be correct,
because of depth buffer non-linear nature, this may promote some occluded
edges before their buildings geometry. This comes from fact that varying
offset (dependent on homogeneous w) applied in clip space provides huge
depth differences, thus resulting in z-fight (and win) of buildings
outlines rendered behind the actual geometry (in certeain frustum settings)
Second problem solved in this PR was promoting clipped geometry (outlines)
from outside the clip range -1 < z < 1 to inside of it, resulting in
rendering outlines of clipped buildings, this requires conditional
offseting - only if vertexes are not to be clipped in the next phase.
Signed-off-by: …
=> MINOR: Fix buildings outlines (edges) rendering.

@here/harp-datasource-protocol/lib/Techniques.ts
Due to usage of MakeTechniqueAttrs typedoc was not able to detect the inheritance of our techniques, hence no properties are listed in the typedoc. With this change there is at least a link to the parent class.
=> MINOR: Fix broken typedoc for techniques due to MakeTechniqueAttrs

@here/harp-examples/src/datasource_features_polygons.ts, @here/harp-examples/src/datasource_satellite-tile.ts, @here/harp-examples/src/datasource_satellite-tile_globe.ts, @here/harp-examples/src/datasource_webtile.ts, @here/harp-examples/src/datasource_webtile_globe.ts, @here/harp-examples/src/datasource_xyzmvt.ts, @here/harp-examples/src/getting-started_globe-projection.ts, @here/harp-mapview/lib/MapView.ts
If `lookAt`, `setCameraGeolocationAndZoom` or `geoCenter` are not specified in the client code, MapView currently sets the camera above Berlin. This PR makes the initial view a wide world view from afar that fits both planar and globe instead.
=> MINOR: Initial view is not Berlin.

@here/harp-examples/src/synchronized-views.ts
This example has never perfectly worked because different controls apply to the 2 MapViews on the border, breaking touches when the fingers are on two different canvases, and breaking the rotation center for other interactions than panning and zooming.
The solution here is to put the central MapView canvas in full page size behind the 2 canvas on the sides, and cancel pointer-events in the CSS for these 2 ones.
=> MINOR: Make sync view great again.

@here/harp-mapview/lib/ClipPlanesEvaluator.ts
Instead of using absolute values for obligatory near-far distance (margin),
we calculate margin as quantity relative to near plane distance. This
fixes the problems with frustum calculus (and matrices multiplication)
rounding errors when huge distances (near distance) encounter small planes
distances.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even …
=> MINOR: ClipPlanesEvaluators uses relative margin between planes.

@here/harp-examples/src/getting-started_free-camera.ts
The default was the new large view, too far away for the default far plane in this example. Switched to a close up of Geneva.
=> Fix free camera example.

.prettierignore, @here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-examples/src/datasource_features_polygons.ts, @here/harp-geojson-datasource/test/GeoJsonTest.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/VisibleTileSetTest.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Fix problems with near clip plane, if geometry contains unnaturally tall extruded polygons.
Instead of hard-coding maximum height of real building, aggregate maximum height
of geometry in `OmvDecodedTileEmitter` and then use as input to `ClipPlanesEvaluator`.
Fixes "black circle" in https://www.harp.gl/docs/master/examples/#datasource_features_polygons.html
Depends on #987 (includes commit).
=> Gather actual max geometry height from tiles.

@here/harp-examples/src/datasource_features_lines-and-points.ts, @here/harp-examples/src/datasource_features_polygons.ts, @here/harp-examples/src/geojson-viewer.ts, @here/harp-features-datasource/lib/FeaturesDataSource.ts, @here/harp-features-datasource/package.json
`FeatureDataSource` now works just with parameters passed from
constructor.
Highlights:
* supports all normal `OmvDataSource` parameters, like `styleSetName`
* support `GeoJsonDataProvider` options to enable cusotmization of
tiler
* supports `geoJson`&`features` option to set features/GeoJson content
right at construction time
Update examples to use new API.
=> Robust FeatureDataSource.

.github/workflows/ci.yaml
Github Actions mac checks are failing globally: https://github.community/t5/GitHub-Actions/macOS-VM-failing-immediately/m-p/36969#M2743
Disabling them until workaround and/or fix is available.
Related-To: HARP-7766
=> Disable Github CI on mac.

@here/harp-examples/src/geojson-viewer.ts, @here/harp-examples/src/getting-started_hello-world_js-bundle.html, @here/harp-examples/src/getting-started_hello-world_npm.ts, @here/harp-examples/src/getting-started_open-sourced-themes.ts, @here/harp-examples/src/object-picking.ts, @here/harp-examples/src/rendering_post-effects_all.ts, @here/harp-examples/src/rendering_post-effects_themes.ts, @here/harp-examples/src/styling_extend-a-theme.ts, @here/harp-examples/src/styling_interpolation.ts, @here/harp-examples/src/synchronized-views.ts, @here/harp-examples/src/theme_data-driven.ts, @here/harp-examples/src/threejs_add-object.ts, @here/harp-examples/src/threejs_camera-animation.ts, @here/harp-examples/src/threejs_raycast.ts
Harmonizes the CSS, adds missing descriptions where needed, sets the zoom level to 16.1 when it is needed to see the buildings, like in the hello world examples (using the distance in `lookAt` results in different zoom levels depending on the height of the viewport).
=> MINOR: Minor examples improvements.

@here/harp-examples/src/getting-started_hello-world_npm.ts, @here/harp-examples/src/theme_data-driven.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvRestClient.ts, @here/harp-omv-datasource/test/OmvRestClientTest.ts
Support url-pattern for locating tiles in `OMVRestClient` and
`OMVDataSource`. Example:
https://my-base-url.com/vector-tiles/{z}/{x}/{y}.mvt
Implements #904
Related-to: HARP-7392
=> Allow custom URLs patterns in OmvDataSource.

@here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Fading state must be updated at the beginning of the frame, otherwise
label opacity will be 0 for the two first frames it's fading in.
In other words, we would be rendering labels with the opacity corresponding
to the previous frame.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests …
=> HARP-7373: Move TextElementStateCache update to beginning of frame.

@here/harp-datasource-protocol/README.md, @here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/lib/operators/ColorOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts
Gives compatibility for themes using 4 channel colors in styling with
attributes expressions like:
- color: rgba[255, 255, 255, 0.5]
- backgroundColor: "rgba(255, 255, 255, 0.5)"
Although those styling attributes will be parsed and read, the alpha
channel component will be silently ignored. Full support for alpha channel
need to be implemented.
TODO:
- support RGBA/ARGB colors internally in engine,
- alpha channel mapping to THREE.js opacity and transparent material
properties,
- support four channel color interpolation,
- more unit tests.
* [contribution …
=> HARP-7517: Partial support for rgba[..] and "rgba(..)" expressions in style.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change adds an overload to getPropertyValue that accepts
enviroments. Also, it introduces a new evaluation scope
called ExprScope.Dynamic that can be used by the Expr operators
to provide different semantics depending on how the expression is used
(e.g. an expression used during decoding vs an expression
used at rending time can potentially have different values).
=> Add support for evaluating expressions to 'getPropertyValue'.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts
A partial evaluation of an Expr is defined to return a new Expr
semantically equivalent to the original Expr but with a different
structure.
=> Add internal APIs to partially evaluate expressions.

@here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/operators/FlowOperators.ts
Move the implementation of common control flow operators to
FlowOperators.ts. This will allow ExprEvaluator to potentially
cache previous computed expressions containing these operators.
=> HARP-7072: Reimplement "all", "any" and "none" as flow operators.

@here/harp-mapview/lib/text/TextElementsRenderer.ts
Moved to debug channel. Also now it's logged only when entering
overload mode instead of logging on every frame with text updates. …
=> MINOR: Change TextElementsRenderer's overload mode logging.

.github/workflows/ci.yaml
Re-enabling checks disabled in #997.
See, https://github.community/t5/GitHub-Actions/macOS-VM-failing-immediately/td-p/36969/page/2
Related-to: HARP-7766
=> Re-enable GitHub CI checks on macOS.

@here/harp-omv-datasource/lib/OmvDataSource.ts
- Users should either supply OmvRestClientParameters or a DataProvider
instance
=> HARP-7677: Remove unsupported OmvDataSourceParameters

@here/harp-mapview/lib/text/TextElementsRenderer.ts
TextElementsRenderer was taking labels for placement from
VisibleTileSet's visibleTiles. Changed to use renderedTiles instead. …
=> HARP-7819: Fix missing labels in Asia in zl 4.

@here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
Expressions used in a "dynamic evaluation scope" should evaluate their
interpolations instead of returning the unvaluated interpolators.
=> HARP-7072: Add support to evaluate interpolation in dynamic scopes.

@here/harp.gl/lib/BundleMain.ts
Ensure that `getBundleScriptUrl` is called during main script load and
that it loaded `harp(.min).js`.
Fixes regression introduced in #901.
Related-to: HARP-7933
=> Fix resolving of decoder script in harp.js

@here/harp-examples/lib/PerformanceUtils.ts, @here/harp-examples/src/performance_benchmark.ts
Fix performance benchmark example by using proper API to set initial map location.
=> Fix performance benchmark example.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/test/InterpolationTest.ts
Default conversion to HSL color space causes inaccuracy's even when
using static colors in themes. Current unit tests (and methods) works only
because of passing color definition (string encoded) directly into to
THREE.js library (without HSL conversion).
In order to support for RGBA color channels and provide common mechanism
for colors decoding, color values may not be converted between spaces
unless needed or requested by special interpolation methods (to be
implemented).
* [coding …
=> HARP-7898: Color interpolation switches to RGB space instead of HSL.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts
This patch-set provides support for defining theme colors in extended HEX
formats that contains alpha channel, such as
- #RGBA (#F008 - semi opaque red),
- #RRGGBBAA (#FF000088 - as above).
Although such colors may be defined in themes, there is no internal engine
support for alpha channel specified, which is silently ignored.
Note:
This also fixes RGBA colors parsing that were not passing via
getPropertyValue() call - static (not interpolated) color values.
* [coding …
=> HARP-7517: Partial support for HEX encoded RGBA colors.

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts
- Increased the expand factor to 1% when zooming out, the factor was not enough to prevent some aliasing at the tile borders
- fixed the calculation of the right / left offsets to take into consideration the tile's offsets.
=> HARP-7808 Fixing issue with tile offset + some artifacts

@here/harp-mapview/lib/text/TextElementGroupState.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Simplify deduplication cache to avoid creating an object for each entry. Now it only holds references to text element state objects.
Also, simplify logic to decide which duplicate is kept and which one is discarded.
Our bots …
=> HARP-7373: Perf improvements in point label deduplication.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts
Fallback tiles now store the offset from the requested tile, for example
Grandparent tiles are -2, parent are -1 and children's children are +1
This ensures that grandparent and parent tiles don't overlap and cause
artifacts as shown in HARP-7985
There are cases, theoretically where the child's child's child overlaps
the child's child, this is also handled (because +2 has a higher render
order than +1).
=> HARP-7985 Correct offset for fallback tiles

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Points rendered with any technique other than Text or POI is
decoded in local tile space (like the rest of non-text geometries). …
=> MINOR: Decode local tile space coordinates for non-text points.

@here/harp-mapview/lib/MapView.ts
Reset the renderOrder of objects, because they may have been previously a fallback tile.
=> HARP-7808 Fix renderOrder not being reset

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/lib/ThemeVisitor.ts
Nesting the style rules is not well supported by our tools.
Also, thanks to the "style expressions" and the StyleSetEvaluator
caching of the filter conditions, nesting rules is not needed.
=> HARP-8047: Remove support for nested style rules.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts
Offsets, scales and biases can be implemented using expressions, e.g.
"renderOrder": ["+", ["get", "sort_rank"], 123]
=> HARP-8050: Remove style properties for tuning the render order

@here/harp-mapview/lib/text/TextElementGroupState.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Sorting labels by camera distance is one of the bottlenecks in label placement.
Also, current implementation is broken, since sorting is done per tile
and not across tiles.
Furthermore, the improvement brought by sorting labels by distance is arguable.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also …
=> HARP-7916: Remove label sorting by camera distance.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/text/FontCatalogLoader.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextStyleCache.ts
Move font catalog loading out of TextElementsRenderer into
a separate class. …
=> HARP-7373: Add FontCatalogLoader.

@here/harp-mapview/lib/text/TextElementsRenderer.ts
Till now mesh was always initialized when TextElementsRenderer
was initialized.
Now it's not initialized until DEBUG_GLYPHS debug option is enabled. …
=> HARP-7373: Lazy initialization of glyph debugging mesh.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json, @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json
This change adds the property 'minZoomLevel' and 'maxZoomLevel'
to the style rules. These properties can be used to filter the rule
based on the zoom level.
=> HARP-7850: Add support for filtering style rules based on the zoom level

.travis.yml
Removing the condition of `tags:true` as it does not behave as expected.
We are reworking the way we tag releases
=> Revert: MINOR: Release only when tags are added to release branch (#103)

@here/harp-mapview/lib/text/TextElementsRenderer.ts
Remove unnecessary call to checkStartFadeIn. Preparation to delete
checkStartFadeIn and checkStartFadeOut methods. …
=> HARP-7373: Minor simplification in path label placement.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/lib/operators/MapOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change adds the method 'isDynamic()' to the class Expr. This
method can be used to classify expressions based on their expected
execution context. For example, ["zoom"] is expected to always be
executed using a dynamic context.
=> HARP-7872: Add 'Expr.isDynamic()'

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-datasource-protocol/lib/IMeshBuffers.ts, @here/harp-geojson-datasource/lib/GeoJsonGeometryCreator.ts, @here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/geometry/TileDataAccessor.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
IDs are now extracted directly from 'objInfos' member in Geometry interface,
which contains the whole attribute map. …
=> HARP-8165: Clean unneeded feature ids.

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-examples/src/datasource_geojson_styling_game.ts, @here/harp-examples/src/object-picking.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts, @here/harp-omv-datasource/lib/OmvDecoderDefs.ts, @here/harp-omv-datasource/test/MapViewPickingTest.ts
'gatherFeatureIds' is deprecated. Feature ids are always decoded,
the rest of the attributes are decoded only if gatherFeatureAttributes
option is set to true (default is false).
Our bots will check whether your PR can be …
=> HARP-8165: Add gatherFeatureAttributes to OmvDataSourceParameters.

@here/harp-mapview/test/PoiInfoBuilder.ts, @here/harp-mapview/test/TextElementBuilder.ts
Facilitate the construction of text element and poi info objects
for testing using the builder pattern.
Used in TextElementsRenderer tests in follow-up PR. …
=> HARP_7373: PoiInfo and TextElement builders for testing.

@here/harp-mapview/lib/VisibleTileSet.ts
This fixes a bug in the fallback logic where if a parent was already added to the set of renderedTiles, then subsequent siblings would search for their children, giving strange results. Now if there is a parent tile found, it is added and all siblings don't search for their children.
Added tests also, see gerrit.
=> Harp 8066: Fix bug with fallback + IBCT tests.

@here/harp-mapview/test/stubFontCatalog.ts, @here/harp-mapview/test/stubFontCatalogLoader.ts, @here/harp-mapview/test/stubPoiManager.ts, @here/harp-mapview/test/stubPoiRenderer.ts, @here/harp-mapview/test/stubScreenProjector.ts, @here/harp-mapview/test/stubTextCanvas.ts
Add helper functions for testing that stub dependencies for
TextElementsRenderer unit tests.
Unit tests are implemented in follow-up PR.
Our bots will check whether your PR can be directly integrated into the mainline. We have …
=> HARP-7373: Stub TextElementsRenderer dependencies for testing.

scripts/rendering-tests-reference-platform.sh, scripts/with-docker-selenium.sh
Allow running rendering test on Mac using `host.docker.internal` feature of Docker for Mac.
Related-to: HARP-6510
Followup of: #1025
=> Rendering tests for Mac.

@here/harp-mapview/lib/text/RenderState.ts, @here/harp-mapview/lib/text/TextElementGroupState.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Fade out transitions for non-visited labels causes a lot of flickering,
especially on quick zoom out movements.
Google maps, mapbox and tangram don't fade out for unvisited labels either.
Our bots will check whether your PR can …
=> HARP-7373: Remove fade out for non-visited labels.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueAttr.ts, @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-datasource-protocol/test/ExprTest.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/RoadPicker.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/TileCreationTest.ts
This change modifies the logic of the StyleSetEvaluator so preserve
(and eventually forward to the main thread) the interpolations. That is,
after this change, the interpolations are handled like any other
dynamic expression.
=> HARP-7872: Reimplement interpolations as dynamic expressions.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-geojson-datasource/lib/GeoJsonDecoder.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
StyleSetEvaluator instances are reused in several tiles, so we need
to reset technique list that accumulates techniques for one tile.
=> Fix technique leak in StyleSetEvaluator.

@here/harp-mapview/lib/PolarTileDataSource.ts
- Tiles that are generated by the PolarTileDataSource without a material
return early, they have no geometry, so the VisibleTileSet thinks
that these are still loading, and the FRAME_COMPLETE event never arrives,
by forcing the geometry, then we get the FRAME_COMPLETE event.
=> HARP-8008 Fix bug in PolarTileDataSource

@here/harp-map-theme/resources/berlin_tilezen_base.json
Remove tertiary and residential road outlines for certain zoom levels to avoid flickering artifacts.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the …
=> HARP-8057 Changed berlin style to avoid flickering of roads.

@here/harp-mapview/lib/CameraMovementDetector.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
* CameraMovementDetector fix
FirstFrameComplete was unnecessary delayed by bogus movement detected by
CameraMovementDetector because CMD detected initial camera setup as move
and then blocked FFC for 300ms because of its timeout.
Initial camera setup is by no means movement and shouldn't set dynamic
frame state for 300ms.
* TileGeometryLoader fix
Additionally, CVM improvement revealed race condition i TGL, which
reported allGeometryLoaded=true before it really finished.
=> Fix bogus FirstFrameComplete delay.

@here/harp-map-theme/package.json, yarn.lock
Upgrade harp-fontcatalog dependency to current (should include Georgian
and Armenian fonts).
Related-to: HARP-6021
=> Upgrade harp-fontcatalog.

@here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Small caps were being applied to measure text but not
to create the text buffer object. As a result small caps were
actually rendered in all caps, but with a smaller bounding box.
Our bots will check whether your PR can be …
=> HARP-8337: Fix small caps rendering.

@here/harp-mapview/lib/text/TextElementState.ts
When a label was replaced, the glyphs of its predecessor where
always used, even if the replacement already had its glyphs loaded. …
=> HARP-8356: Fix label intersections.

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
If world offset is not taken into account, two equivalent text elements
(same feature id) belonging to different world offsets in mercator
projection are considered duplicates, and hence only one is displayed.
Our bots will …
=> HARP-8319: Check world offset on text deduplication with feature id.

@here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-materials/lib/Utils.ts
Introduces performance fix. Blending mode changes does not require material updates
(shader recompilation or getting from the cache), blend modes are solely implemented
using glBlendFunc in THREE.js, without affecting the shaders. Remove material
updates on blend modes changes.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some …
=> HARP-7517: Do not force material update when blending mode changes.

@here/harp-mapview/lib/MapViewFog.ts, @here/harp-materials/lib/CirclePointsMaterial.ts, @here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/SolidLineMaterial.ts
Because THREE.js material update may take quite a long time and force
new shader buildup, it is recommended to use Material.needsUpdate flag
carefully.
This patch-set limits material updates only to real state changes,
affecting shader structure, thus reducing needs for shader re-build to
minimum.
Fixed classes:
- MapViewFog,
- CirclePointsMaterial,
- EdgeMaterial.
If you are adding new functionality we would highly appreciate if …
=> HARP-8361: Reduce forced material updates (needsUpdate flag usage).

@here/harp-datasource-protocol/lib/Theme.ts, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts
`Theme`s `extends` can now be array of base theme URLs or `Theme`
objects.
Example:
{
extends: [
"./berlin-colors.json",
"./berlin-rules-tilezen.json"
]
}
Related-to: HARP-7361
=> Theme can now extends / inherit from many base themes.

@here/harp-mapview/lib/AnimatedExtrusionHandler.ts, @here/harp-materials/index.ts, @here/harp-materials/lib/EdgeMaterial.ts, @here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-materials/lib/MapMeshMaterialsDefs.ts, @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/package.json
Don't animate appearance of extruded buildings with height near 0 (or very small)
to prevent flickering caused by float precision issues when panning & overlapping tiles
Fixes:
* flickering of whole building area of appearing building with height ~0
* most of flickering of said buildings on tile borders
At expense of _not animating_ exposure or height of those buildings at all.
Fallback tiles still cause flickering from time to time.
Related-to: HARP-8279
=> Fix z-fighting of animated buildings with 0 height.

@here/harp-mapview/lib/text/TextElementsRenderer.ts
Path text state was being fully resetted after it was rejected, which
meant that the label was rejected for the next frames until the next
label update took place.
Now only the fade state is rejected but the view distance is kept. That
way the label will go through placement on the the next frames.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better …
=> HARP-4888: Fix path text flicker caused by state reset on rejection.

@here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
Fixes regression introduced by #1119 caused by incorrect clamping of
extrusion ratio of _not_ flat buildings.
Related-to: HARP-8421, HARP-8279
=> Fix animated extrusion direction.

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/text/TextElementGroupState.ts
Tweaked priority was not being used anyway since the label group priority
is floored.
Furthermore, there's better options to ensure longer path labels get displayed:
1. Give higher priority to higher category street labels in the style.
2. Use OMV street label layer (ticket in backlog) to improve placement of
path labels so that they don't collide with intersecting streets.
If you are adding new functionality we would highly …
=> HARP-4888: Remove path label priority tweaking w.r.t path length.

@here/harp-mapview-decoder/lib/TileDecoderService.ts
Check that geom.objInfos[0] is an object before trying to check if
it has the "displacementMap" property. …
=> HARP-8455: Fix crash in TileDecoderService.

@here/harp-datasource-protocol/lib/operators/MapOperators.ts
These operators are used to convert from pixels to world space
based on the reference ppi (always 72 for now), the zoom level,
and the reference zoom level (for harp.gl it is defined to be 17).
=> HARP-8439: Add support for the ppi-scale family operators.

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/TextElementBuilder.ts, @here/harp-mapview/test/TextElementsRendererTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-mapview/test/stubTextCanvas.ts
Now there's different criteria to select the "best" label duplicate for point labels and for path labels when feature ids are not available.
- For point labels the best duplicate is the closest label with same text (as long as it's within the maximum distance tolerance to consider a label a duplicate).
- For path labels, the best duplicate is the longest path label with same text within the maximum distance tolerance. Choosing the longest path makes it more likely that it'll remain visible for a longer time even if there's camera changes, since paths shorter than a minimum length are discarded.
* …
=> HARP-4888: Change path label duplicate criteria.

@here/harp-mapview/lib/ScreenCollisions.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/ScreenCollisionsTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-utils/lib/Math2D.ts
Glyph BBs are now saved together with the label global BB in the screen collision RTree.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the …
=> HARP-4888: Test glyph BBs on label collision.

@here/harp-utils/index-common.ts, @here/harp-utils/index.web.ts, @here/harp-utils/package.json
@here/harp-utils contains platform-dependent module - UrlPlatformUtils
that has to be resolved differently in node and web context.
Follow strategy from `@node/fetch` and use `package.json`s `browser`
field, so `.web` versions are default in `web` target.
=> Improve resolving @here/harp-utils symbols in web target.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts
Avoid possible exceptions when the value to be tested by
isInterpolatedProperty is null. …
=> Fix isInterpolatedProperty.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/test/ExprTest.ts, @here/harp-map-theme/resources/berlin_derived.json, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts
Currently theme definitions require a `type` attribute to classify values and selectors.
Introduce shortcut syntax, where literal string/number/boolean values:.
"definitions": {
"a": { "value": 123},
"b": { "value", "#f00f00"},
"foo": 123,
"bar": "#f0f0f0",
"spam": true
}
Related-to: HARP-8438
=> Make the type attribute of theme definitions optional

@here/harp-features-datasource/lib/FeaturesDataSource.ts, @here/harp-features-datasource/package.json, @here/harp-test-utils/lib/rendering/RenderingTestHelper.ts, test/rendering/StylingTest.ts, test/rendering/package.json, webpack.tests.config.js
Map styling tests (GeoJson + OmvDataSource + MapView) of following
techniques with focus on transparency.
- text
- solid-line
- fill
- standard
- extruded-polygon
=> Styling tests for RGBA support

@here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/test/StringDecodersTest.ts
There was a bug that encoded alpha channel as integer value. …
=> HARP-8531: Fix styling rgba(...) expression encoder.

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
TileDisplacementMap was not being set as user data
for terrain objects in TileGeometryCreator.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on …
=> HARP-8521: Fix terrain overlay.

@here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview-decoder/lib/TileLoader.ts, @here/harp-mapview-decoder/test/TileDataSourceTest.ts
Remove tile loader cache because of several issues(tile loaders canceled to soon, styles not updated).
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on …
=> HARP-8560 Fix for tiles not loading in sphere view

@here/harp-mapview/lib/AnimatedExtrusionHandler.ts, @here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-materials/lib/Utils.ts
MapMeshMaterials defines mixins that are injected into standard THREE.js
materials to allow adding new features:
- fading,
- extrusion,
- displacement map.
The logic of mixin features was very inefficient and time consuming, such
as it forced many materials (and uniform) updates (re-compilation).
This patchset limits such WebGl shader re-compilation and uniforms
transfer to minimum. It also provides the chaining of onBeforeCompile
callback so all the mixins may be applied simultaneously. Previously there
was a bug that allowed only one feature to be applied to THREE.Material.
TODO:
- possibly implement generic mixins that could be applied also to
EdgeMaterial and SolidLineMaterial. …
=> HARP-8361: Fix unnecessary materials & uniforms updates in MapMeshMaterials

@here/harp-map-controls/lib/MapControls.ts, @here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewFog.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/text/MapViewState.ts
In some cases focus point (and tilt angle) may not be calculated because
Camera is looking to the void. In this scenarios the last known focus point
is used and the highest possible tilt value is exposed (90 degrees).
This allows to keep camera pivot consistent (when changing the projection
type, or manipulating camera manually) and computations based on tilt
stable (using maximum tilt), this may be: fog, fading effect, etc.
If you …
=> HARP-7907: Limit number of raycasts used for Camera tilt calculus.

.travis.yml, package.json, yarn.lock
Travis CI always uses "current stable" version of chrome, and `chromedriver` has very limited compatibility (usually 1 or 2 major versions max).
Detect actual chrome version on system and upgrade chromedriver used for browser integration testing.
=> Sync chromedriver version with actual chrome in CI.

@here/harp-datasource-protocol/lib/Theme.ts, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts
Flat themes are HARP themes where all the style declarations
are flattened in one single array. This change adds initial
support for loading flat themes by converting them to
HARP themes. The conversion is done so we can start experimenting
with this new file format without changing too much the HARP code base.
=> HARP-8615: Add support for reading flat themes.

@here/harp-datasource-protocol/lib/ColorUtils.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts
Our toolchain is unable to remove `assert` calls yet, and JIT is unable to skip creation of assert arguments (observed in profiler), so don't create dynamic strings in assert arguments.
=> Don't create dynamic strings in 'hot' asserts.

@here/harp-olp-utils/lib/OlpCopyrightProvider.ts, @here/harp-olp-utils/lib/OlpDataProvider.ts
http/204 errors are now propagated as exceptions, not as replies.
Also handle the version in OlpCopyrightProvider as the license might
change between catalog versions.
=> Better handling of olp data

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts
Previously SolidLineTechnique outline color was using ColorCache which
does not support alpha channel, this change provides RGBA support for
outline color. …
=> MINOR: Add support for RGBA encoded outline colors in SolidLineTechnique.

@here/harp-test-utils/package.json
chai was both in dependencies and devDependencies. Since the package
seems to use chai in public API, remove the devDependency
=> Remove chai from devDependencies

@here/harp-atlas-tools/package.json, @here/harp-datasource-protocol/package.json, @here/harp-datasource-protocol/test/ThemeTypingsTest.ts, @here/harp-debug-datasource/package.json, @here/harp-features-datasource/package.json, @here/harp-fetch/package.json, @here/harp-geojson-datasource/package.json, @here/harp-geometry/package.json, @here/harp-geoutils/lib/projection/TransverseMercatorProjection.ts, @here/harp-geoutils/package.json, @here/harp-lines/package.json, @here/harp-lines/test/rendering/RenderLines.ts, @here/harp-lrucache/package.json, @here/harp-map-controls/package.json, @here/harp-map-theme/package.json, @here/harp-mapview-decoder/package.json, @here/harp-mapview/package.json, @here/harp-mapview/test/UtilsTest.ts, @here/harp-materials/package.json, @here/harp-olp-utils/package.json, @here/harp-omv-datasource/package.json, @here/harp-test-utils/lib/TestUtils.ts, @here/harp-test-utils/package.json, @here/harp-text-canvas/package.json, @here/harp-text-canvas/test/rendering/TextCanvasRenderingTest.ts, @here/harp-transfer-manager/package.json, @here/harp-utils/package.json, @here/harp-webpack-utils/package.json, @here/harp-webtile-datasource/package.json
Allows us to pass extra options to tsc when running from within e.g.
lerna. Good to try out new compiler options.
Also fixed some super strict linter warnings.
=> Honor $EXTRA_TSC_ARGS when building

@here/harp-mapview/lib/geometry/TileGeometryManager.ts
Some of the kinds in a set or array were not added due to the shortcircuited
evaluation of the or conditions.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration …
=> HARP-8521: Fix TileGeometryManager.hideKind()

@here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-materials/lib/ShaderChunks/ExtrusionChunks.ts
Disable "z-figthing workaround" for EdgeMaterial.
PR #1179 introduced workaround to prevent z-fighting of small buildings
(height ~ 0).  This workaround is viable for translucent polygons, but
not for lines ... esp. lines that are always on z=0 such as footprints.
As result #1179, accidentaly completly disabled "animated exposure"
of footprints, causing them to be visible with opacity=1 from frame 1,
only to be clobbered by other geometry few frames later, effectively
producing annoying flicker.
Related-to: HARP-8448
=> Fix animated exposure of building footprint.

@here/harp-datasource-protocol/lib/operators/MapOperators.ts
Increase the reference zoom level used by "world-discrete-ppi-scale"
to convert pixels to world units.
=> HARP-7814: Tune the internal discrete scaling functions.

@here/harp-olp-utils/lib/OlpDataProvider.ts, @here/harp-olp-utils/package.json, @here/harp-olp-utils/test/OlpDataProviderTest.ts
Don't handle `AbortError` in OlpDataProvider.getTile as this should
be loaded up in call chain by `TileLoader`.
Related-to: HARP-8768
=> HARP-8768: Fix cancellation handling in OlpDataProvider.

@here/harp-mapview/lib/MapView.ts
The phased loading in options is interpreted as 'false' by default, such
as it is disabled when the option is undefined.
Fix getter implementation to comply with options interpretation.
Our bots will check whether your PR can …
=> MINOR: Fix phased loading default value interpretation.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/TechniqueAttr.ts, @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-datasource-protocol/test/InterpolationTest.ts, @here/harp-geojson-datasource/lib/GeoJsonTile.ts, @here/harp-geojson-datasource/test/GeoJsonTest.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/PolarTileDataSource.ts, @here/harp-mapview/lib/RoadPicker.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/poi/PoiRenderer.ts, @here/harp-mapview/lib/text/MapViewState.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/lib/text/ViewState.ts, @here/harp-mapview/test/DecodedTileHelpersTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-mapview/test/TileCreationTest.ts, @here/harp-mapview/test/stubPoiRenderer.ts, @here/harp-omv-datasource/lib/OmvDebugLabelsTile.ts
Use `Env` in invocations of `getPropertyValue` to support other dynamic
properties than `zoomLevel` only.
=> Use Env for dynamic expressions.

@here/harp-mapview-decoder/lib/TileLoader.ts, @here/harp-mapview-decoder/test/TileLoaderTest.ts, @here/harp-mapview/test/CopyrightProvidersTest.ts
Removes the errors from the console, i.e.:
```
TileLoader: [anonymous-datasource#5]: failed to load tile 1 Error: No connection.
at MockDataProvider.getTile (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/test/TileLoaderTest.ts:50:35)
at TileLoader.startLoading (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/lib/TileLoader.ts:87:9)
at TileLoader.loadAndDecode (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/lib/TileLoader.ts:26:6)
at Context.<anonymous> (/home/travis/build/heremaps/harp.gl/@here/harp-mapview-decoder/test/TileLoaderTest.ts:194:44)
```
Before requesting a pull request, please remember to check the following …
=> MINOR: Remove logging to console and check with spy instead

@here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts, @here/harp-mapview/lib/geometry/PhasedTileGeometryLoader.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
The decoded tiles geometry was loaded/generated multiple times, both with
techniques processing in SimpleTileGeometryLoader.
This patchset fixes the flow so the request for tile load after decoding is
processed only once.
It also adds some sanity checks that ensures us that disposed or unvisible
tiles are no longer loaded/processed.
If you are adding new functionality we would highly appreciate if you can describe what is the …
=> HARP-8604: Fix for multiple time tile loading using setTimeout() call.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/Env.ts, @here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprInstantiator.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/operators/ObjectOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
Dynamic properties are properties that are resolved at rendering
time.
This change also removes the special handling of ["zoom"] when
computing the dependencies of an expression.
=> Add support for dynamic properties.

@here/harp-examples/src/styling_data-driven.ts
This particular example demonstrates how to create a new style set
by importing rules from an existing theme. Unfortunately, instead of
creating a new style set this example was simply appending rules to the
imported style set named 'tilezen' defined in berlin_tilezen_base.json
=> HARP-9079: Fix the styling data driven example.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueAttr.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/lib/operators/InterpolationOperators.ts, @here/harp-datasource-protocol/test/InterpolationTest.ts
InterpolatedProperty is only used in scope of interpolation
operators so can be removed from typings and "general" codebase.
=> Remove InterpolatedProperty from Technique.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/operators/FeatureOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-examples/src/datasource_features_polygons.ts, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json, @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json, test/rendering/GeoJsonDataRendering.ts
Also remove the deprecate usages of $geometryType in harp-map-theme.
=> Add support for the style operators 'id' and 'geometry-type'

@here/harp-mapview/lib/copyrights/CopyrightInfo.ts
Copyright links are now opening in new tab.
=> OLPSUP-9660: Implemented opening of copyright links in new tab.

@here/harp-mapview/lib/MapView.ts
At the beginning of a frame, the previous frame objects are
removed from the scene calling MapView's mapTilesRoot.remove()
for each one of them. Each remove() call searches for the object
in an array and then splices it.
It's much simpler to just set the root's children array to length 0.
The average speedup is small, but it gets rid of some peaks where the
whole removal was taking ~1ms.
If you are adding new functionality we would …
=> MINOR: Remove 3D objects from root more efficiently.

@here/harp-omv-datasource/lib/OmvData.ts
OMV payloads without explicit values for feature.id should
not set $id to 0.
=> Fix the decoding of feature ids.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/test/TileInfoTest.ts, @here/harp-geojson-datasource/lib/GeoJsonTile.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/lib/text/TileTextStyleCache.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
This patch removed IndexedTechnique._key from usage in render phase and
changes scope of caching of text style from "datasource" to "tile", as this
allows to identify text styles by `IndexedTechnique._index` only.
Followup of #1299
=> Remove the usages of Technique._keys take #2

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Statistics.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts, @here/harp-mapview/test/StatisticsTest.ts
Previously the fullFrameTime was computed by subtracting the last frame start time from the current frame start time.
This was done to make sure we also measure the time we spend outside the current animation frame (i.e. geometry creation time).
Unfortunately with this approach we also measure everything the application/test is doing.
With this change the fullFrameTime is explicitly computed by adding the geometry creation time to the current frame.
If you are adding new functionality we would …
=> HARP-8971: Fix wrong computation of fullFrameTime (hence fps)

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/test/UtilsTest.ts
Inaccuracies on the 13-th fractional digit of zoom level calculation
may be observed when doing small tilt changes, thus causing the zoom level
to be discretized to smaller value then real one, especially when
calculating tiles' storage or visibility level.
This causes displaying wrong tile set (with different zoom level) for
a certain camera arrangement (angles).
The change introduces zoom level rounding above 10-th fractional digit,
giving enough safety margin for inaccurate zoom level from distance
calculus and quite good precision for zoom level based interpolations.
* [contribution …
=> HARP-8523: Fix zoom level jitter and tiles flickering.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/DepthPrePass.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/test/DecodedTileHelpersTest.ts, @here/harp-test-utils/lib/TestUtils.ts
As dynamic expression may return invalid value (bad type, null, error),
we have to guard places when style expressions/values are used.
This patch protects against style / Expr yielding:
* null
* invalid colors
* errors thrown while evaluating expressions
Related-to: HARP-8515
Followup of #1241 and #1233
=> HARP-8515: Basic checks nulls/undefined/errors in style.

@here/harp-webtile-datasource/lib/WebTileDataSource.ts
`const enum`s are not emitted to Javascript by default, so javascript
users would see `WebTileDataSource.ppiValue` as `undefined`.
Note `const enum`s are there only for performance reasons and those
contants are not intended to be used in performance sensitive code so
there is no reason to hack it around with `preserveConstEnums` compiler
flag.
=> HARP-9344: WebTileDataSource - don't use const enums.

@here/harp-map-controls/lib/MapControls.ts, @here/harp-map-controls/test/MapControlsTest.ts
Whenever MapView canvas is placed with offset from the browser edges
the MapControls calculated the mouse position and NDC cords incorrectly.
This patch-set allows to place canvas anywhere, thus gives support for
canvas translation (offset) and additionally provides support for scaling.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can …
=> HARP-8385: Fix MapControls support for flexible layouts.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/lib/operators/FeatureOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change adds the operator `["feature-state", property]` that
can be used to get property values that are not part of the feature
data.
=> Add support for the feature-state operator.

@here/harp-datasource-protocol/lib/TileInfo.ts
The current code was assuming that label attributes of text
techniques were always string literals. Of course, this
is not the case when using expressions.
=> Fix the evaluation of "label" attributes of text techniques.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-examples/src/object-picking.ts, @here/harp-mapview/lib/AnimatedExtrusionHandler.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/overlayOnElevation.ts
Add support for filtering features based on their state.
This change adds APIs to manipulate the state of a feature.
Note, that currently the feature state can only be used to
enable/disable features. That is, harp.gl themes can use
`["feature-state", property]` in expressions assigned to
the `enabled` attribute, for example:
{
when: ["==", ["geometry-type"], "LineString"],
layer: "roads",
technique: "solid-line",
renderOrder: 10000,
attr: {
enabled: ["feature-state", "enabled"],
lineWidth: "1px",
color: "#c00"
}
}
Application code can programmatically update the state of a feature
using the DataSource API, for example:
dataSource.setFeatureState(featureId, {
enabled: true
});
mapView.update()
=> Add support for filtering features based on their state

@here/harp-mapview/lib/text/TextElementStateCache.ts
It's triggered frequently for region/state labels where the full text
is changed by its abbreviation depending on zoom level. …
=> MINOR: Reduce logging level of text feature id collision message.

@here/harp-debug-datasource/lib/DebugTileDataSource.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/BackgroundDataSource.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/PolarTileDataSource.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/package.json, @here/harp-mapview/test/DataSourceTest.ts, @here/harp-mapview/test/FakeOmvDataSource.ts, @here/harp-mapview/test/PolarTileDataSourceTest.ts, @here/harp-mapview/test/TileTest.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts, @here/harp-webtile-datasource/test/WebTileTest.ts
* Added minDataLevel, maxDataLevel, minDisplayLevel, maxDisplayLevel.
* Deprecated minZoomLevel, maxZoomLevel. …
=> HARP-9037 Refactored DataSource zoom level limits

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts, @here/harp-mapview/test/TileTest.ts
Only objects in intersected tiles are tested for intersection.
Tile bounding boxes are updated to go from minElevation to
maxElevation + maxGeometryHeight. …
=> HARP-9275: Test intersection with tiles on picking.

@here/harp-utils/lib/UrlUtils.ts, @here/harp-utils/test/UrlUtilsTest.ts
In order to support `data:` scheme in `Theme`, we must recognize
`data:` as absolute uri (before this patch `data:` URIs were threated
as `relative path` and thus resolved vs `baseURL`.
Related-to: HARP-7206
=> UrlUtils: Support for data: URI scheme.

@here/harp-mapview/lib/geometry/VertexCache.ts, @here/harp-mapview/test/VertexCacheTest.ts
It'll be used for mesh displacements on picking. Terrain overlay is done
by displacing meshes in the vertex shader. To pick those meshes, they
are displaced in CPU. To avoid allocating the whole position buffer again,
intersection test is done on the fly for every triangle after it's displaced.
To avoid recomputations of the same vertex, a small LRU cache is used.
If you are adding new functionality we would highly appreciate if you …
=> HARP-9275: Implement VertexCache for mesh on the fly transformations.

@here/harp-lines/test/rendering/RenderLines.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-materials/lib/ShaderChunks/LinesChunks.ts, @here/harp-materials/lib/SolidLineMaterial.ts
Cleanup.
SolidLineMaterial.lineWidth was really "extrusion ratio" applied for each half, thus lineWidth=1 means "actual width" 2.
This cleans up and thus SolidLineTechnique.lineWidth doesn't need to be halved before applying to material.
=> HARP-9251: Fix SolidLineMaterial.lineWidth semantics.

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/VisibleTileSet.ts
This change is required in order to provide MapViewAtmosphere support
without MapView dependency (see PR: #1378)
Cleanups the code and changes interfaces to not use MapView reference.
Our bots will check whether your PR can be …
=> MINOR: Refactor ClipPlanesEvaluator(s), remove MapView dependency.

@here/harp-examples/lib/PerformanceConfig.ts, @here/harp-examples/lib/PerformanceUtils.ts, @here/harp-examples/src/performance_benchmark.ts, @here/harp-examples/webpack.config.js
* Add new Berlin zoom testcase that mimics HERE Maps for JavaScript testcase
* Add save functionality
* Allow configuration of themes via webpack (for internal themes)
=> TEST: Added Berlin ZoomIn test

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-examples/decoder/custom_decoder.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
The property `renderOrderOffset` was superseded by dynamic
render order expressions and layer categories.
=> Remove 'renderOrderOffset'.

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
The `featureId` property is not used, the omv datasource was setting it
when decoding some of the features but its value was never read.
=> Remove unused `featureId` from 'Group'.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
* `GeometryKind` is now free string, whereas builtin values moved to
`StandardGeometryKind`
* fix: Pois and LineMarkers can be hidden now
* fix: disabling/enabling fixed (previously it retained state from
initial geometry creation)
* `TileGeometryManager` and friends now use internal technique member
to track actual state derived from `kind` instead of clobbering
`Technique.enabled`
* `Technique.enabled` documented as free for use for filtering
=> HARP-9159: Cleanup kind-based filtering.

@here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/PlacementTest.ts
POC code which checks different anchor point (placements) that comes
internally from hard-coded table. Final solution should read
possible placement points from the technique (theme) definition and
store them in TextElement.m_layoutStyle.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add …
=> HARP-6488: Solve multiple label placements when checking collisions.

@here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/TileCreationTest.ts
Substitude getObjectConstructor by buildObject. Return the created object
instead of the constructor. It's simpler and more flexible, since buildObject
can do more than just choosing a constructor.
Also refactor TileCreationTest to remove all copy-pasta.Frankly the test is useless
and I'd rather remove it completely.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are …
=> HARP-8498: Refactor object construction in TileGeometryCreator.

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-mapview-decoder/lib/TileDecoderService.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
Geometry attachments can be used to create sets of
objects sharing buffer and feature data (e.g. objInfos).
=> HARP-9155: Add support for geometry attachments.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/operators/ArrayOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change introduces the operator 'array' to validate the type
of arrays the operator 'make-array' to create heterogeneous arrays
from sub expressions.
=> HARP-9897: Add support for 'array' and 'make-array'.

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/operators/VectorOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
This change introduces new operator and type conversions to
support vector2/3/4.
=> HARP-9897: Add support for vector2/3/4 operators.

@here/harp-datasource-protocol/lib/InterpolatedProperty.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change extends the InterpolatedProperty so it can be used to
interpolate vector values, e.g.
```json
["interpolate",
["linear"], ["zoom"],
0,  ["make-vector", 0, 0],
20, ["make-vector", 20, 20]]
```
=> HARP-9897: Add support for interpolating vector values.

@here/harp-examples/src/threejs_shadows.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/ThemeHelpers.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-materials/lib/MapMeshMaterials.ts, @here/harp-materials/lib/ShaderChunks/ShadowChunks.ts
This improves the lighting of flat objects, such that the final rendered pixel color isn't impacted by a diffuse component. Previously the color would be based on the direction (using a diffuse shading model), however this dramatically changes the color of the scene and would require a lot of rework from the designers / different theme files for shadow / non shadowed themes.
- "fill" techniques can now handle shadows, when shadows are enabled, they now
use a tweaked version of the standard material.
=> HARP-8744 Fix lighting for shadows

@here/harp-examples/src/styling_data-driven.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/text/RenderState.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/RenderStateTest.ts, @here/harp-mapview/test/TextElementStateTest.ts
* Change to display of city population (countries do not contain population in new data source).
* Fix MapView.disableFadeIn option.
* Implement textFadeTime and iconFadeTime.
Our bots will check whether your PR can be directly …
=> HARP-9576 Fix styling data-driven example

@here/harp-examples/src/threejs_shadows.ts
Buildings are transparent because otherwise the shadow shows through, this can be fixed with some
bias as shown in the PR: #1461, however this introduces z fighting, and the values would need to be
customized for a specific screen resolution etc.
=> HARP-8744 Opaque buildings

@here/harp-examples/src/datasource_geojson_styling_game.ts
This change rewrites the logic of the GeoJson styling game to
use the ["dynamic-properties"] to handle selections instead of
setting a new styleset and redecode the tiles.
=> HARP-10054: Select regions using dynamic properties.

@here/harp-map-controls/lib/MapControls.ts
=> HARP-9984 Fix: MapControls don't cache zoom after end of interaction.

@here/harp-mapview/test/ColorCacheTest.ts, yarn.lock
This change ensures the ColorCache is cleared before the test
starts.
=> Initialize ColorCache before running the tests.

@here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-text-canvas/lib/TextCanvas.ts
This changes includes:
- Cleanup label's TextBufferObject whenever it's layout changes,
- Provide proper copies (not references) of TextRenderStyle and TextLayoutStyle for
TextBufferObject creation.
- Cleanup TextBufferObject whenever TextElementState is reset or replaced
(derived) from predecessor.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even …
=> HARP-9898: Fix TextElement's (labels) TextBufferObject handling.

@here/harp-examples/src/getting-started_look-at.ts, @here/harp-geoutils/index.ts, @here/harp-geoutils/lib/coordinates/GeoBox.ts, @here/harp-geoutils/lib/coordinates/GeoBoxExtentLike.ts, @here/harp-geoutils/lib/math/MathUtils.ts, @here/harp-geoutils/test/GeoBoxTest.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/UtilsTest.ts
MapView.lookAt for GeoBox and arbitrary point support
* MapView.lookAt: supports 'bounds' align view to fit GeoBox or arbitrary
set of geo points
* new "getting-started / look-at" example to showing various usages of
`lookAt`
* MapView: fix re-calculation of tilt/heading in lookAt() on sphere
projection
=> HARP-6501: MapView.lookAt for GeoBox and arbitrary point support

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts
It was only used in MapView utils, and there's a duplicated constant there.
Also, maxTiltAngleRad was set to NaN, MAX_TILT_ANGLE is undefined when the expression
for that constant is executed.
=> HARP-10184: Remove unused MAX_TILT_ANGLE contant from MapView.

@here/harp-mapview/lib/Utils.ts
zoomOnTargetPosition was returning if camera target does not intersect the globe,
therefore zoom was not updated. …
=> HARP-10299: Fix zoom on globe.

.ort.yml
Updating .ort.yml to mark several dirs used for testing as not included in released artifacts to npmjs.com. Replaced scope exclude reason that has been deprecated in OSS Review Toolkit.
See also:
https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md.
Signed-off-by: Thomas Steenbergen <thomas.steenbergen@here.com>
=> .ort.yml: Exclude test dirs and replace deprecated reason

@here/harp-mapview/lib/text/TextElementsRenderer.ts
I was searching for references to position and
didn't find how the POI's are placed in world space
This makes it easier to find in future. …
=> HARP-8309 Fix incorrect position access

@here/harp-mapview-decoder/lib/TileLoader.ts, @here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts, @here/harp-mapview-decoder/test/TileLoaderTest.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts
Empty payloads (empty objects) were not detected and they were
sent down to the decoder. In the case of the terrain that's triggered
the decoding of an invalid terrain tile unnecessarily.
Our bots will check whether your PR can …
=> HARP-10183: Fix empty payload check in TileLoader.onloaded().

@here/harp-omv-datasource/lib/OmvData.ts
OmvProtobufDataAdapter emits proper polygon rings.
Fix long-standing bug where OMV/MVT extruded-buildings were lacking
last/first edge because edge geometry creator expected that polygon
`Ring`s have first and last positions are equivalent (they represent
equivalent points).
This patch aligns geometry emitted by MVT adapter to match concept of
"linear ring" definition from GeoJSON standard.
[1] https://tools.ietf.org/html/rfc7946#page-9
=> HARP-10210: OmvProtobufDataAdapter emits proper polygon rings.

scripts/with-http-server.ts
Fix CI on windows.
On windows, batch files are only recognized if you try to execute them via shell, so trampoline scripts like `npx` or `mocha-webdriver-runner` are not found we attempt to run them directly by system call.
=> Fix CI on windows.

.ort.yml
@here/harp-test-utils is part of the released artifacts, see
https://www.npmjs.com/package/@here/harp-test-utils.
Signed-off-by: Thomas Steenbergen <thomas.steenbergen@here.com>
=> .ort.yml: Remove @here/harp-test-utils as it's publisbed

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/poi/PoiRenderer.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-materials/lib/IconMaterial.ts, test/rendering/StylingTest.ts
PoiTechnique aka `labeled-icon` technique:
* Add `iconColor` support for easy coloring monochromatic/opaque icons.
* Add `iconBrightness` property that adapts brightness of texture/`iconColor`
* Added basic poi/labeled-icon techinique rendering tests.
=> HARP-10179: Add `iconBrightness` and `iconColor` support for POIs.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-mapview/lib/text/LayoutState.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/test/PlacementTest.ts, @here/harp-text-canvas/lib/rendering/TextStyle.ts, @here/harp-text-canvas/test/TextStyleTest.ts
Introduce new `placement` technique attribute for:
- 'labeled-icon' (PoiTechnique),
- 'line-marker' (LineMarkerTechnique),
techniques that are utilizing LineMarkerTechniqueParams set.
Currently only point labels have support for alternative placements.
The attribute holds an string of possible (alternative) text
placements relative to label origin (anchor) point.
If placements are defined they override hAlignment and vAlignment
settings defined in style. Each placement option is defined in array
as 1 or 2 characters string token that describes text position relative to
origin. i.e. "TR" (top-right), "BL", (bottom-left) or simply
"R" (center-right).
Before requesting a pull request, …
=> HARP-6487: Provide `placement` attribute support for point labels.

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts, @here/harp-omv-datasource/lib/OmvDecoder.ts
Removing featureId as parameter, because it is extracted from the context.
=> HARP-8309 Remove unused variable

@here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/geometry/overlayOnElevation.ts, @here/harp-mapview/test/TileTest.ts
HARP-10184: Fix tile's geo bbox computation.
- Use always the geo box computed by the tiling scheme to ensure it covers the whole tile, since it's used later to generate uv coordinates for displacement maps.
- Elevate geo box using elevation range and maximum geometry height (if available).
- Remove wrong unproject of bounding box provided in decodedTile.
=> HARP-10184: Fix tile's geo bbox computation.

@here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/test/PlacementTest.ts, @here/harp-mapview/test/TextElementStateTest.ts
This commit finally switches the alternative text placement
algorithm to use only theme defined list of possible placements.
- Default/hard-coded placement alternatives are no longer used.
- Some more testing scenarios with focus on text placements
(TextLayoutState) for state reset and replace have been added.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and …
=> HARP-6487: Do not use default text placements anymore.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-map-theme/resources/berlin_derived.json, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/resources/berlin_tilezen_base_globe.json, @here/harp-map-theme/resources/berlin_tilezen_day_reduced.json, @here/harp-map-theme/resources/berlin_tilezen_effects_outlines.json, @here/harp-map-theme/resources/berlin_tilezen_effects_streets.json, @here/harp-map-theme/resources/berlin_tilezen_night_reduced.json, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts
Before this change the member "attr" was used to set the technique
parameters and the style properties where stored in the enclosing object.
This was inconsitent and confusing, for example `textMinZoomLevel`
was a member of "attr" but "minZoomLevel" was a member of style.
=> HARP-10452: Merge the style and the technique parameters.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprPool.ts, @here/harp-datasource-protocol/lib/PropertyValue.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
This change introduces a simple `MemoCall` that caches
the previous execution of an Expr.
=> HARP-7073: Use memoization to reduce the number of expr evaluations.

@here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/test/PlacementTest.ts
Additional text margin (used as padding between icon and text) was not
applied to the text position, resulting in growing collision box, but
without effect on relative distance between label icon and text.
This path fixes it and adds support to bounding box measurement via
TextCanvas that are not 0, 0 anchored. This means that change will work
even without margin applied.
If you are adding new functionality we would highly …
=> HARP-10478: Apply text POIs margin to collision box and text offset.

@here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/test/TextElementStateTest.ts
This ensures that bounds are properly calculated in the next frame and
fixes the bug with seldom text offset jumping on zoom level changes.
Our bots will check whether your PR can be directly integrated into the mainline. We …
=> HARP-10490: Reset the text label bounds when reusing other label's state.

@here/harp-datasource-protocol/lib/DecodedTile.ts
Attempt to localize text labels even if `label` property is provided
this allows usage of expressions for `label` and still leverage
builtin mechanism for localization (see MapView.languages).
=> HARP-10240: More robust support for localised labels.

@here/harp-map-controls/lib/MapControlsUI.ts
If zoom buttons are quickly pressed twice in WebKit-based browser, the
generated double click event is propagated to canvas, triggering a zoom in
movement in addition to zoom button action.
Signed-off-by: Andres Mandado Almajano <andres.mandado-almajano@here.com>
=> HARP-10298: Avoid zoom button double click propagation to canvas.

@here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
- Don't compute the roof vertices for non extruded polygons
=> MINOR: Perf improvement for fill techniques

@here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
This change adds support for partial evaluating 'case' expressions
with dynamic conditions.
=> HARP-10609: Fix evaluation of case statements with dynamic conditions.

@here/harp-examples/webpack.config.js, webpack.tests.config.js
This change enables the type checking of webpack config files
using the `//@ts-check` directive.
=> Enable type checking in the webpack config files.

@here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/test/StringDecodersTest.ts
While for example the **rgba(0,85,170,.6)** is a valid CSS color, using it throws a **Unsupported color format** error in harp.gl.
The [RGBA alpha value](https://drafts.csswg.org/css-color/#typedef-alpha-value) can also be specified without a leading zero. The following change is a hotfix to cover it.
=> harp-10621: Fix broken non leading zero float color transparency

@here/harp-datasource-protocol/README.md
This change rewrites the snippets using the expression syntax.
It also removes the section about the outdated usage of nested styles.
=> Fix style snippets

@here/harp-mapview/lib/Utils.ts, @here/harp-mapview/test/UtilsTest.ts
Conversions from zoom level to camera distance and back to zoom level cause a loss of
precision that makes the actual zoom level at each frame fall sometimes below and others
above a given integer zoom level, causing flickering of some map objects (e.g. extruded buildings).
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some …
=> HARP-9673: Snap zoom level to nearest integer if close enough to it.

@here/harp-mapview/lib/text/MapViewState.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/ViewState.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts
Some text labels do appear/disappear showing the current solution unstable
even when camera parameters are not changed and user performs top view (2D)
panning.
This problem is caused by labels distance scaling and changes in their
bounds. Because labels closer to screen center becomes bigger they need
more screen space and thus labels' collisions algorithm may drop them out.
The second problem was caused by limiting the number of labels being placed
from now this limit will be applied only to the new labels to be processed.
* [contribution guidelines](https://github.com/heremaps/harp.gl/blob/master/CONTR …
=> HARP-9926: Suppress labels flickering while panning on 2d view.

.gitignore, @here/harp-geoutils/lib/projection/Projection.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/copyrights/CopyrightCoverageProvider.ts, package.json, scripts/apidocs.ts, yarn.lock
This change adds a npm script to generate markdown documentation
using api-documenter. The documentation is generated using the command:
```
yarn docs
```
After the command `yarn docs` terminates the directory
`markdown` containing the documentation will be created.
=> Add basic support for running api-documenter.

@here/harp-transfer-manager/src/TransferManager.ts
The typing of fetch() uses RequestInfo as first parameter. Use that as
well so TransferManager can become a easy drop-in for fetch() usage.
Signed-off-by: Harald Fernengel <harald.fernengel@here.com>
=> Change TransferManager to use RequestInfo

@here/harp.gl/.npmignore, @here/harp.gl/api-extractor.json, @here/harp.gl/package.json, @here/harp.gl/tsconfig.json, @here/harp.gl/webpack.config.js
This change introduces a simple api-extractor configuration and a npm
script to generate typings information for the bundled @here/harp.gl
package.
The typings are generated in `@here/harp.gl/dist/harp.gl.d.ts` by
the following command:
```
yarn workspace @here/harp.gl run build-typings
```
=> HARP-10715: Use api-extractor to generate rollup d.ts typings.

@here/generator-harp.gl/README.md, @here/harp-examples/src/camera-animations_key-track.ts, @here/harp-examples/src/datasource_features_lines-and-points.ts, @here/harp-examples/src/datasource_features_polygons.ts, @here/harp-examples/src/datasource_geojson_choropleth.ts, @here/harp-examples/src/datasource_geojson_custom-shader.ts, @here/harp-examples/src/geojson-viewer.ts, @here/harp-examples/src/getting-started_free-camera.ts, @here/harp-examples/src/getting-started_globe-projection.ts, @here/harp-examples/src/getting-started_hello-world_npm.ts, @here/harp-examples/src/getting-started_open-sourced-themes.ts, @here/harp-examples/src/getting-started_orbiting-view.ts, @here/harp-examples/src/object-picking.ts, @here/harp-examples/src/real-time-shadows.ts, @here/harp-geojson-datasource/lib/GeoJsonDataSource.ts, @here/harp-omv-datasource/lib/OmvDataSource.ts
This change introduces service specific default values for
vector-tile based data sources. The default service provider is
configured to `https://vector.hereapi.com/v2/vectortiles/base/mc`,
and the relevant options (e.g. tiling scheme, authetication method,
copyright info, ...) are initialized accordingly.
For most cases the following declaration is enough to get a working
vector tile data source.
```
const omvDataSource = new OmvDataSource({
baseUrl: "https://vector.hereapi.com/v2/vectortiles/base/mc",
authenticationCode: apikey
});
```
=> Simplify the initialization of OMV Data Sources.

@here/harp-datasource-protocol/lib/RGBA.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/package.json, @here/harp-datasource-protocol/test/StringDecodersTest.ts, yarn.lock
This change replaces most of the code for parsing color string literals.
The new code is based on csscolorparser, as side effect harp.gl gets
support for CSS string literals (e.g. red, yellow, ...) and hsla
strings.
The hex literals are still parsed using an ad hoc regular expression
because csscolorparser doesn't support #rgba and #rrggbbaa hex
formats.
=> HARP-10627: Use csscolorparser to parse CSS color literals.

.github/workflows/ci.yaml
Right now the windows CI actions is not stable and due to fail-fast, all other platforms were aborted.
Setting fail-fast to false for now to fix it.
=> Let all CI actions run through

@here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts
These global variables are consider internal and should not appear
in the user documentation.
=> Mark as internal the global variables exported by datasource-protocol.

@here/harp-datasource-protocol/lib/Env.ts, @here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/ExprEvaluator.ts, @here/harp-datasource-protocol/lib/ExprInstantiator.ts, @here/harp-datasource-protocol/lib/ExprPool.ts, @here/harp-datasource-protocol/lib/InterpolatedPropertyDefs.ts, @here/harp-datasource-protocol/lib/PropertyValue.ts, @here/harp-datasource-protocol/lib/StringEncodedNumeral.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Techniques.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/lib/WorkerDecoderProtocol.ts, @here/harp-geoutils/lib/math/MathUtils.ts
Add missing documentation for Expr and Env. Also, start to use reference
declaration using `@link` and hide some internal symbols.
=> Add missing documentation for expressions and environments.

@here/harp-mapview/lib/MapView.ts
* Make them available in production mode, as the demo app is for
debugging the labels even in production, not just local development …
=> HARP-9221: Fix label debug collisions

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts
Mark the main overload of `lookAt` with a @label directive and
explicit target this overload when using tsdoc `@link`s.
=> Fix tsdoc links to MapView.lookAt.

test/rendering/GeoJsonDataRendering.ts
The test demonstrates the issues that harp.gl has when
stroking polygons with edges at the tile border.
=> HARP-10648: Add a test for polygons touching the tile border.

@here/harp-datasource-protocol/lib/TechniqueParams.ts
All the declarations of `GeometryKind` must have the same
module visibility.
=> Fix ae-internal-mixed-release-tag error.

@here/harp-mapview/lib/poi/BoxBuffer.ts, @here/harp-materials/lib/IconMaterial.ts
* premultiplied textures now render properly,
where they were blending to white before …
=> HARP-10466: Traffic icons fade to white not transp

@here/harp-test-utils/lib/rendering/DomImageUtils.ts, @here/harp-test-utils/lib/rendering/RenderingTestResultReporter.ts
When testing harp.gl the console is full of diagnostic messages
coming from DomImageUtils and RenderingTestResultReporter. These
messages are too many and they make it difficult to spot other
error messages.
=> Remove verbose log messages.

@here/harp-lines/test/rendering/RenderLines.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-materials/lib/SolidLineMaterial.ts
This change should avoid seeing circles when
rendering adjacent segments of solid lines.
Use the stencil buffer and prefer boxstep to smoothstep
when rendering solid-lines with opacity less than 0.98.
Note that we are using 0.98 instead of 1.0 to avoid possible
issues when interpolations give values close to 1.0 instead
of 1.0.
=> HARP-8201: Avoid glitches when rendering transparent lines

@here/harp-mapview-decoder/lib/GeoJsonTiler.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
This change configures geojson-vt to use a buffer of about 5% of the
extents when tiling. The introduction of the buffer allows us to
better classify the edges introduced when tiling feature geometries.
=> HARP-10648: Add a buffer of about 5% around the clipped tile.

@here/harp-examples/src/performance_benchmark.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
=> Tile upload throttling HARP-10363

@here/harp-omv-datasource/lib/DecodeInfo.ts, @here/harp-omv-datasource/lib/OmvDecodedTileEmitter.ts
Geometries with tile space coordinates outside the [0...extent]
range should be discarded at decoding time.
This is needed to avoid possible glitches when rendering
semi-transparent points.
=> HARP-10979: Discard the point geometries outside the tile bounds.

@here/harp-omv-datasource/lib/OmvUtils.ts
The OMV decoder was projecting latitude to mercator space
using `floor` instead of `round`, but to ensure compatibility
with the precision of WARP tiles `round` should be preferred.
=> HARP-11037: Fix cracks at the tile boundaries.

package.json
=> MINOR: Fix yarn test-browser

test/rendering/GeoJsonDataRendering.ts
This IBCT test is used to reproduce the bug when rendering
area features using the extruded polygon technique without
"vertex color batching" enabled. The expected result is to
have 3 extruded polygons with different colors.
=> HARP-10876: Add a test that renders extruded polygons without batching.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueDescriptor.ts
This change ensures that the correct dynamic attribute scope is
selected for extruded-polygon techniques when vertexColors is not
set.
=> HARP-10876: Fix usage of dynamic color expressions in extruded buildings

.gitignore
This change adds the missing `coverage` directory to the gitignore config file.
=> Add the `coverage` directory to .gitignore

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/DepthPrePass.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewPoints.ts, @here/harp-mapview/lib/Statistics.ts, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/geometry/TileGeometry.ts, @here/harp-mapview/lib/image/ImageCache.ts, @here/harp-mapview/lib/poi/PoiTableManager.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts
Also fix the visibility of some of the internal symbols that
don't have documentation and break the docs layout.
=> HARP-10753: Use @remarks tsdoc tags.

@here/harp-examples/src/datasource_here_vector_tile.ts
The example was referencing the symbol `mapView` instead of `map`
when installing the copyright info handler.
=> HARP-11210: Fix typo in the HERE vector tile example.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/test/MapViewTest.ts
zoomLevel/distance are now taken into account when setting via **MapView** constructor or **lookAt** method.
=> MINOR: Look-at zoomLevel/distance applies together with bounds

@here/harp-mapview-decoder/lib/DataProvider.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-omv-datasource/lib/GeoJsonDataProvider.ts, @here/harp-omv-datasource/test/OmvDataSourceTest.ts
This change introduces an "invalidated" event to DataProvider
and adds an automatic way to clear caches when the
geojson data provider input is updated.
=> HARP-11091: Add DataProvider.onDidInvalidate

.github/workflows/ci.yaml, .travis.yml, @here/harp-examples/webpack.config.js, @here/harp.gl/webpack.config.js, webpack.tests.config.js, www/webpack.config.js
The `HARP_NO_HARD_SOURCE_CACHE` env variable can be used to
control the usage of `hard-source-webpack-plugin`. For example:
HARP_NO_HARD_SOURCE_CACHE=true yarn start
Also, this change disables the usage of the hard-source cache
in the CI.
Note that the value assigned to `HARP_NO_HARD_SOURCE_CACHE` is
not important, that is, as long as the environment variable
`HARP_NO_HARD_SOURCE_CACHE` is defined the hard-source cache will
be disabled.
=> Add environment variable HARP_NO_HARD_SOURCE_CACHE.

@here/harp-debug-datasource/lib/DebugTileDataSource.ts, @here/harp-mapview/lib/BackgroundDataSource.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/PolarTileDataSource.ts, @here/harp-omv-datasource/test/MapViewPickingTest.ts, @here/harp-webtile-datasource/lib/WebTileDataSource.ts
Disabling picking for data sources that don't need it will make it faster.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our …
=> HARP-10772: Add enablePicking to DataSourceOptions

.github/workflows/ci.yaml
Fix a typo in the key assigned to the yarn cache, also
update the restore key to use the yarn cache of a previous
build compatible with the os and node version.
=> Fix cache key and restore keys in ci.yaml.

.github/workflows/ci.yaml
This change ensures that yarn will not generate a lockfile.
Signed-off-by: Roberto Raggi <roberto.raggi@here
=> Install the deps using yarn --frozen-lockfile.

.github/workflows/ci.yaml
Signed-off-by: aluni <gairik.aluni@here.com> …
=> HARP-10966 - Moving build-bundle job before build-example job

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, test/rendering/StylingTest.ts
We need to disable line clipping since HERE Vector Tiles will soon have a smaller margin.
=> HARP-9982 Disable line clipping by default

@here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-materials/lib/EdgeMaterial.ts
The previous code was mixing vertex colors with the edge color
to compute the final color value. The mix was assuming that the
geometry was using vertex colors. This is not the case for the
majority of our themes.
This change introduces the parameter `vertexColors` and
the property `objectColor` that can be used to correctly
compute the final edge color when vertex colors are not
available.
=> HARP-11212: Fix undefined behavior when computing the edge color.

@here/harp-mapview/lib/MapObjectAdapter.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/PickingRaycaster.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/PickingRaycasterTest.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
The flag may be set to false to disable picking for particular objects. Picking is disabled for depth prepass, background, edges and center line of solid lines with outline (knowing whether the outline is picked is enough).
=> HARP-10772: Add pickable flag to object's userData.

test/rendering/StylingTest.ts
Building edges are still rendered even though the buildings are disabled.
=> HARP-10881: Added image regression test to reproduce the issue

@here/harp-examples/src/object-picking.ts
This change ensures that the objects created to visualize
the road and landuse selection are marked as trasient. This is
required to discard these geoemtries when picking objects in
the scene.
=> Mark the geometries created for the selection with transient

@here/harp-map-controls/test/MapControlsTest.ts, @here/harp-mapview/lib/Utils.ts
Camera target must be computed, since mapView.targetWorld might be
outdated, .e.g., during a zoom animation.
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration …
=> HARP-11261: Fix zoomOnTargetPosition

@here/harp-map-controls/lib/CameraKeyTrackAnimation.ts
Changing look-at from within `onFinish` handler was not applied due to race condition with already stopped animation.
=> MINOR: Fix race condition with CameraKeyTrackAnimation

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/lib/Theme.ts, @here/harp-datasource-protocol/lib/ThemeVisitor.ts, @here/harp-datasource-protocol/test/ExprTest.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-examples/src/datasource_features_polygons.ts, @here/harp-examples/src/datasource_geojson_choropleth.ts, @here/harp-examples/src/real-time-shadows.ts, @here/harp-examples/src/styling_data-driven.ts, @here/harp-examples/src/styling_extend-a-theme.ts, @here/harp-map-theme/resources/berlin_derived.json, @here/harp-map-theme/resources/berlin_tilezen_base.json, @here/harp-map-theme/test/DefaultThemeTest.ts, @here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/PolarTileDataSourceTest.ts, @here/harp-mapview/test/ThemeLoaderTest.ts, @here/harp-mapview/test/resources/baseTheme.json, @here/harp-omv-datasource/test/resources/geoJsonData.ts, test/rendering/StylingTest.ts
Add support for extending and overriding existing style rules.
An existing style can be extended by referencing its `id` in
an `extends` property, for example:
base.json
```json
{
"styles": [
{
"styleSet": "tilezen",
"id": "extruded-building-rule",
"layer": "buildings",
"when": ["==", ["geometry-type"], "Polygon"],
"technique": "extruded-building",
"color": "red"
}
]
}
```
can be extended by `derived.json` using
```json
{
"extends": [
"./base.json",
],
"styles": [
{
"styleSet": "tilezen",
"id": "extruded-building-rule",
"color": "yellow",
"minZoomLevel": 16
}
]
}
```
Alternatively, the rule `extruded-building-rule` can be replaced by simply reusing its id in a derived theme, e.g.
```jsonc
{
"extends": [
"./base.json",
],
"styles": [
{
"styleSet": "tilezen",
"id": "extruded-building-rule", …
```
=> HARP-11250: Add support for style extensions.

@here/harp-omv-datasource/index-worker.ts, @here/harp-vectortile-datasource/index-worker.ts, @here/harp-vectortile-datasource/lib/OmvDecoder.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts, @here/harp-vectortile-datasource/test/MapViewPickingTest.ts, @here/harp-vectortile-datasource/test/OmvDataSourceTest.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts, @here/harp.gl/lib/DecoderBundleMain.ts, @here/harp.gl/lib/index.ts, @here/harp.gl/package.json, test/performance/OmvDecoderPerformanceTest.ts, test/rendering/GeoJsonDataRendering.ts, test/rendering/StylingTest.ts, www/src/decoder.ts
This change renames
- OmvTileDecoder to VectorTileDecoder
- OmvDecoder to VectorTileDataProcessor
- OmvTileDecoderService to VectorTileDecoderService 
- OmvDecodedTileEmitter to VectorTileDataEmitter
=> HARP-8067: Renamed OmvTileDecoder to VectorTileDecoder

@here/harp-examples/src/threejs_animation.ts
It got broken due to changes in inflate.min.js dependency in latest
THREE.js release. Fixed by importing module version of FBXLoader.
inflate is imported directly in that module. …
=> HARP-11466: Fix animation example.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/test/MapViewTest.ts
In case the ray-casting of the screen coordinate is not hitting the earth surface a fallback to the far plane will be computed
=> MINOR: Add safe version for screen to geo conversion

@here/generator-harp.gl/README.md, @here/generator-harp.gl/generators/app/index.js, @here/generator-harp.gl/generators/app/templates/javascript/View.js, @here/generator-harp.gl/generators/app/templates/javascript/decoder.js, @here/generator-harp.gl/generators/app/templates/typescript/View.ts, @here/generator-harp.gl/generators/app/templates/typescript/decoder.ts
This change remove usages of the deprecated @here/harp-omv-datasource
from the harp.gl yo templates.
=> HARP-11509: Update the harp.gl yo templates.

@here/harp-mapview/lib/MapView.ts, @here/harp-test-utils/lib/WebGLStub.ts
ext() upon MapView.dispose
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from …
=> HARP-11228: Call WebGlRenderer.forceLooseCont

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/test/MapViewTest.ts
- Added test
- Log warning when set and projection is spherical
=> MINOR: tileWrappingEnabled fixes

@here/harp-materials/lib/GroundAtmosphereMaterial.ts, @here/harp-materials/lib/ShaderChunks/AtmosphereChunks.ts, @here/harp-materials/lib/SkyAtmosphereMaterial.ts
Shader auxiliary functions 'conditionalBranchFree' were not working as expected,
resulting boolean changed from frame to frame.
Dynamic light uniform substituted by define constant, flexibility of the uniform is
not actually required.
Our bots will check whether your PR can be directly …
=> HARP-11430: Fix Atmosphere flickering.

.vscode/extensions.json
This change suggested users of harp.gl to install the eslint
and prettier vscode extensions.
=> Suggest eslint and prettier vscode extensions.

.github/workflows/docs.yaml
This PR saves the API metadata produced by api-extractor
and the markdown docs created by api-documenter
as github artifacts.
=> HARP-10758: Save the API metadata and markdown artifacts.

@here/harp-examples/src/datasource_custom.ts, @here/harp-examples/src/tile_dependencies.ts, @here/harp-mapview-decoder/lib/DataProvider.ts, @here/harp-mapview-decoder/lib/TestDataProviders.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview-decoder/test/DataProviderTest.ts, @here/harp-mapview-decoder/test/TileDataSourceTest.ts, @here/harp-mapview-decoder/test/TileLoaderTest.ts, @here/harp-olp-utils/lib/OlpDataProvider.ts, @here/harp-vectortile-datasource/lib/GeoJsonDataProvider.ts, @here/harp-vectortile-datasource/lib/OmvRestClient.ts, @here/harp-vectortile-datasource/test/OmvDataSourceTest.ts
Both methods are now protected. Clients call instead register/unregister,
and new DataProvider abstract class ensures connect is called on first
registered client and dispose called on last unregistered client.
Breaking API change:
- Classes derived from DataProvider must use "extends" instead of "implements",
and must call super() on constructor.
- Custom Data sources using DataProvider must call register/unregister instead
of connect/dispose.
If you are adding new functionality we would highly …
=> HARP-11487: Ensure DataProvider's connect and disposed are called once.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
This change removes the exceptions raised by `StyleConditionClassifier`
when `step` and `interpolate` expressions are found during the
traversal. These exceptions are not needed and In fact,
it is perfectly acceptable to use `step` or `interpolate` expressions
with a feature attributes as their input in `when` conditions.
=> Add visit methods to classify interpolations in when conditions.

@here/harp-datasource-protocol/lib/Expr.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
A typo in the parser prevents creating interpolations with input
parameter equal to 0.
=> HARP-11784: Fix typo when parsing interpolate operators.

@here/harp-webpack-utils/scripts/HarpWebpackConfig.ts
The code was not handling the case when the entry point is a tsx
file.
=> HARP-11835: Fix typo preventing the detection of typescript react apps.

@here/harp-mapview-decoder/lib/TileLoader.ts, @here/harp-mapview-decoder/test/TileLoaderTest.ts
Empty payload from the data provider now sets the decodedTile to be empty, this ensures that the
ground plane is properly created which is needed because otherwise, if the DataSource
isFullyCovering, it will remove the BackgroundDataSource's tiles and there will be holes in the
map.
=> HARP-11468 Empty payloads are set with an empty decodedTile so that the background plane is still set

@here/harp-utils/lib/Math2D.ts, @here/harp-utils/test/Math2DTest.ts
Used to find intersections of view bounds with horizon on sphere
projection. The horizon on sphere projection is a circle on a plane
perpendicular to the camera normal. …
=> HARP-11531: Add circle and line intersection to Math2DUtils.

@here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/test/PlacementTest.ts
=> HARP-11340: Ignore collision margin when computing text offset

@here/harp-mapview/lib/SphereHorizon.ts, @here/harp-mapview/test/SphereHorizonTest.ts
SphereHorizon computes the horizon for sphere projection, which is
a circle. It provides functions to get any point on it or subdivide
an arc into any number of divisions. …
=> HARP-11531: Sphere horizon computation.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueDescriptors.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts
This change introduces the concept of automatic technique properties.
The value of the underlying material is always kept in sync
with the value of the technique property. So there is no need
to call `material.property = getPropertyValue(technique.property)`
for automatic properties.
Automatic properties must be defined in TechniqueDescriptors.ts, for example:
```
const polygonalTechniqueDescriptor: TechniqueDescriptor<PolygonalTechniqueParams> = {
attrDescriptors: {
polygonOffset: { scope: AttrScope.TechniqueRendering, automatic: true }, // automatic
someOtherProperty: AttrScope.TechniqueRendering, // non automatic
}
```
=> HARP-11247: Add support for automatic technique properties

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/test/ClipPlanesEvaluatorTest.ts
The far plane was being computed too close when the aspect ratio was close to one
The fix is to shoot a ray from the camera along the frustums upper right edge and see if it
intersects the earths sphere. Whether there is an intersection determines how restrictive the far
plane is.
=> HARP-9413 Fixes #1384 far plane too close in globe

@here/harp-datasource-protocol/lib/TechniqueDescriptors.ts
This change adds ensures that updates to dynamic changes to the property `wireframe` are automatically applied to the underlying technique.
=> Made wireframe an automatic property

@here/harp-examples/src/bounds-generation.ts, @here/harp-geoutils/lib/coordinates/GeoCoordinates.ts, @here/harp-geoutils/lib/coordinates/GeoPolygon.ts, @here/harp-geoutils/test/GeoCoordinatesTest.ts, @here/harp-geoutils/test/GeoPolygonTest.ts, @here/harp-mapview/lib/BoundsGenerator.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/test/BoundsGeneratorTest.ts
=> HARP-11531: Look-at bounds for sphere.

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
Adds a simple optional filter function to mark only subset of tiles as dirty.
=> MINOR: Add optional filter to markTilesDirty method

@here/harp-fetch/package.json, package.json, www/package.json, yarn.lock
=> MINOR: Updates node-fetch due to security warning

@here/harp-datasource-protocol/lib/operators/MapOperators.ts
`world-ppi-scale` and `world-discrete-ppi-scale` were using two
different zoom level reference values. This change ensures that
both operators use 17 as base zoom level reference for their
computations.
=> HARP-9962: Change the zoom level reference used by `world-discrete-ppi-scale`

@here/harp-vectortile-datasource/lib/OmvDecoderDefs.ts, @here/harp-vectortile-datasource/lib/VectorTileDataSource.ts, @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts, @here/harp-vectortile-datasource/lib/adapters/omv/OmvDataAdapter.ts
This change introduces the flag `roundUpCoordinatesIfNeeded` to
the `VectorTileDataSource`. When the flag is enabled the decoder
is allowed to adjust the coordinates of liens and polygons close
to the antimeridian to avoid gaps.
=> HARP-12145: Fix gaps along the antimeridian.

@here/harp-text-canvas/lib/rendering/FontCatalog.ts, @here/harp-text-canvas/test/rendering/TextCanvasRenderingTest.ts
* non-rendered control characters are not replacement glyphs
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you …
=> HARP-12342: Fix rendering strings with control characters

@here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts, @here/harp-mapview/lib/geometry/TileGeometryManager.ts, @here/harp-mapview/test/TileTest.ts
A Tile subclass may still need access (e.g. to attach callbacks to the finished promise).
Also, fix uncaught promised exception when a tile is disposed
before it waits on the TileGeometryDecoder promise.
Our bots will check whether your PR can be directly integrated into the mainline. We have …
=> HARP-11672: Make TileGeometryLoader protected.

@here/harp-examples/webpack.config.js, @here/harp-webpack-utils/scripts/HarpWebpackConfig.ts, docs/GettingStartedAngular.md, webpack.tests.config.js
The `stats` object requires the exclude patterns to be relative
paths.
=> HARP-12466: Fix initialization of the webpack's stats.

@here/harp-datasource-protocol/lib/TechniqueDescriptors.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
This change ensures that the 'side' property of the materials is
automatically synchronized with its technique value.
=> HARP-12078: Made the 'side' property of techniques automatic.

.github/workflows/ci.yaml
=> HARP-12470 - Removing set-env from Github CI workflow

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/test/UtilsTest.ts
- Add final flag to getTargetAndDistance return type. The flag will be false if the elevation is not yet ready.
- Also replace getHeightAboveTerrain() by one line of code. …
=> HARP-12192: Request Map view update if camera settings are not final.

@here/harp-mapview/lib/ScreenProjector.ts, @here/harp-mapview/lib/poi/PoiRenderer.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/lib/text/RenderState.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/PlacementTest.ts, @here/harp-mapview/test/PoiInfoBuilder.ts, @here/harp-mapview/test/RenderStateTest.ts, @here/harp-mapview/test/ScreenProjectorTest.ts, @here/harp-mapview/test/TextElementStateCacheTest.ts, @here/harp-mapview/test/TextElementStateTest.ts, @here/harp-mapview/test/TextElementsRendererTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-mapview/test/TextElementsRendererTestUtils.ts, @here/harp-mapview/test/stubPoiRenderer.ts, @here/harp-mapview/test/stubTextCanvas.ts, @here/harp-utils/lib/Math2D.ts
* cull using near/far plane
* render partial text and icons near border …
=> HARP-11899: Cull only labels that are completely off screen

@here/harp-olp-utils/lib/OlpCopyrightProvider.ts, @here/harp-olp-utils/lib/OlpDataProvider.ts
The Data SDK for Typescript will have removed in the next release the
deprecated constructor for the `VersionedLayerClient` and also
methods `getVersion()` and `withVersion()` for the `DataRequest`.
This CR adapts the code according to future changes.
Signed-off-by: Oleksii Zubko <ext-oleksii.zubko@here.com>
=> Stopping use deprecates.

@here/harp-transfer-manager/src/TransferManager.ts
- Tiles were slow to load because tiles that were aborted were being
retried up to 5 times, because the hasOwnProperty didn't work on the
DOMException.
=> HARP-12619 Fix slow loading of tiles when zooming out

@here/harp-geoutils/lib/coordinates/GeoBox.ts, @here/harp-geoutils/test/GeoBoxTest.ts
Previous to this change the longitude of the center of zero-sized
geo boxes was shifted 180 degrees.
=> HARP-12729: Fix GeoBox.center for zero-sized geo boxes.

@here/harp-mapview/lib/FrustumIntersection.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
This is required because otherwise dependent tiles's dependencies are loaded, which continues infinitely.
This PR is split into two commits, the first is just a pure refactor, i.e. there is no functional change.
The second commit shows how the first refactor makes it easy to split the groups and fix the issue.
=> HARP-12759 Split dependent tiles from visible tiles

@here/harp-examples/src/datasource_here-webtile.ts, @here/harp-examples/src/getting-started_open-sourced-themes.ts, @here/harp-examples/src/performance_benchmark.ts, @here/harp-examples/src/rendering_post-effects_themes.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewThemeManager.ts, @here/harp-mapview/test/DataSourceTest.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts
=> Remove deprecated Theme accessors

@here/harp-mapview/lib/ScreenProjector.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextElementsRendererOptions.ts, @here/harp-mapview/test/ScreenProjectorTest.ts
* reject pois that are too far outside of screen
Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next …
=> HARP-12685: Optimize label placement

codecov.yml
Our code coverage has increased over the last year, so increasing it so we don't lose our gains, see: https://codecov.io/gh/heremaps/harp.gl
=> MINOR: Codecov increase target

@here/harp-examples/src/datasource_geojson_styling_game.ts, @here/harp-examples/src/styling_interpolation.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/PolarTileDataSource.ts, @here/harp-mapview/test/PolarTileDataSourceTest.ts
=> Deprecates Datasource.setStyleSet

@here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewThemeManager.ts, @here/harp-mapview/lib/image/ImageCache.ts, @here/harp-mapview/lib/image/MapViewImageCache.ts, @here/harp-mapview/test/ImageCacheTest.ts
* remove images from cache only if not used in any other MapView …
=> HARP-12687: User Images are removed from cache when theme is changed

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/poi/BoxBuffer.ts, @here/harp-mapview/lib/poi/PoiRenderer.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/test/PlacementTest.ts, @here/harp-mapview/test/PoiBatchRegistryTest.ts, @here/harp-mapview/test/PoiInfoBuilder.ts, @here/harp-mapview/test/PoiRendererTest.ts, @here/harp-mapview/test/TileTest.ts
- Share material and texture across pois with same image even if they have different render order.
- Do reference counting on resources to dispose of them when they're not used any longer.
=> HARP-12700: Disposal of POI resources by reference counting.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-mapview-decoder/test/TileDataSourceTest.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/PolarTileDataSource.ts, @here/harp-mapview/test/DataSourceTest.ts, @here/harp-vectortile-datasource/lib/VectorTileDataSource.ts
=> HARP-12599: Deprecates setTheme(theme, languages)

@here/generator-harp.gl/generators/app/templates/javascript/decoder.js, @here/generator-harp.gl/generators/app/templates/javascript/deps.js
=> Fixes #1947 Fix webpack reordering import statements

@here/harp-mapview-decoder/lib/DataProvider.ts, @here/harp-mapview-decoder/test/DataProviderTest.ts
* subsequent register operations should resolve after first connect …
=> HARP-12352: subsequent DataProvider.register() return early

@here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts, @here/harp-mapview-decoder/test/TileLoaderTest.ts, @here/harp-mapview/test/MapViewTest.ts, @here/harp-mapview/test/TileTest.ts, @here/harp-vectortile-datasource/test/MapViewPickingTest.ts, @here/harp-webtile-datasource/test/WebTileLoaderTest.ts, @here/harp-webtile-datasource/test/WebTileTest.ts
=> HARP-12868: Fix Tile and TileGeometryLoader tests

@here/harp-examples/src/datasource_geojson_visibility.ts, @here/harp-mapview-decoder/lib/TileDataSource.ts, @here/harp-vectortile-datasource/test/OmvDataSourceTest.ts
This change replaces the usage of `clearTileCache` with `marksTileDirty`
to ensure smooth updates when the GeoJson document is invalidated.
Also, this change modifies the GeoJson visibility example to
demonstrate how to animate map objects by modifing the GeoJson
features.
=> Fix invalidation of GeoJson inputs

@here/harp-examples/src/datasource_geojson_elevated-markers.ts, @here/harp-geoutils/index.ts, @here/harp-geoutils/lib/math/Vector2Like.ts, @here/harp-geoutils/lib/math/Vector3Like.ts, @here/harp-vectortile-datasource/lib/IGeometryProcessor.ts, @here/harp-vectortile-datasource/lib/OmvUtils.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts, @here/harp-vectortile-datasource/lib/adapters/geojson-vt/GeoJsonVtDataAdapter.ts, @here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts, @here/harp-vectortile-datasource/lib/adapters/omv/OmvDataAdapter.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts, test/performance/OmvDecoderPerformanceTest.ts, test/rendering/GeoJsonDataRendering.ts, test/rendering/StylingTest.ts
- GeoJsonDataProvider forwards now altitude for point features to decoder.
- Data tiled with geojson-vt does not yet support altitude.
- Add public example and IBCT tests.
=> HARP-12959 Support GeoJSON point features with altitude for pre-tiled data.

@here/harp-mapview/lib/text/TextElementsRenderer.ts
This change removes diagnostic messages that show up often when
all the logging channels are enabled.
=> Remove verbose debug messages.

@here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts, test/rendering/GeoJsonDataRendering.ts
This change ensure that the winding of the inner rings of GeoJson
Polygon features is opposite to the winding of the outer ring.
=> HARP-13120: Fix the winding of the inner rings of GeoJson polygon.

test/rendering/GeoJsonDataRendering.ts, test/rendering/GeoJsonFeaturesRendering.ts, test/rendering/utils/GeoJsonTest.ts
Add visual tests for rendering geo features.
This change moves helper code to create GeoJson visual tests
to GeoJsonTest.ts and it adds some initial tests for rendering
circles and stroked arcs.
=> Add geo features tests

@here/harp-datasource-protocol/StyleExpressions.md, @here/harp-datasource-protocol/lib/operators/ArrayOperators.ts, @here/harp-datasource-protocol/test/ExprEvaluatorTest.ts
The slice operator extracts a section of the input `string` or `Array`,
and it follows the semantics of Array.prototype.slice.
Requested in #1961
=> HARP-12977: Add support for the slice operator.

@here/harp-geometry/lib/ClipLineString.ts, @here/harp-geometry/lib/WrapLineString.ts, test/rendering/GeoJsonDataRendering.ts
This change adds the function `wrapLineString` that can be used
to wrap line features crossing the antimeridian.
=> HARP-13251: Add support for wrapping linestrings crossing the antimeridian.

yarn.lock
yarn-deduplicated didn't remove this entry.
=> Remove duplicate readdirp from the yarn lockfile.

@here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextElementsRendererOptions.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts
=> MINOR: Removes default font catalog option

@here/harp-webtile-datasource/lib/HereWebTileDataSource.ts
=> MINOR: support DataSourceOptions in HereWebtileDataSource

@here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextStyleCache.ts, @here/harp-mapview/test/TextElementsRendererTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts
=> Update-able TextStyleCache

@here/harp-mapview/lib/text/TextElementState.ts, @here/harp-mapview/lib/text/TextElementStateCache.ts, @here/harp-mapview/test/TextElementBuilder.ts, @here/harp-mapview/test/TextElementsRendererTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-mapview/test/TextElementsRendererTestUtils.ts, @here/harp-mapview/test/stubTextCanvas.ts
TextElementState.lineMarkerIndex must not be copied to the successor.
Predecessor and successor might have different number of markers. The
marker instance used as replacement is chosen by proximity to the
predecessor.
Also findDuplicateByText() was choosing the wrong cmp function for line
markers.
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests …
=> HARP-13345: Fix line marker replacement.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-mapview/lib/TileObjectsRenderer.ts, @here/harp-mapview/lib/text/Placement.ts, @here/harp-mapview/test/PlacementTest.ts
Signed-off-by: German Zargaryan <german.zargaryan@here.com> …
=> HARP-13493: Make maxZoomLevel value in technique non inclusive

@here/harp-mapview/lib/FrustumIntersection.ts, @here/harp-mapview/test/VisibleTileSetTest.ts
The problem was that the perspective division looses information about
whether the tile was behind the camera or behind the far plane, which
means we can't sort the tiles correctly. Tiles behind the near plane
are therefore given a distance of -1 and those past the far plane
are given a distance of +1. Note, we know that the tiles are visible
because they intersect the frustum.
=> HARP-11894 Fixing partially missing tiles

@here/harp-mapview/lib/text/TextElementsRenderer.ts
In case POI icon is registered as HTMLCanvasElement in the MapViewImageCache it is not immediately "ready", hence we
need to schedule a second frame to render it correctly.
Signed-off-by: German Zargaryan <2526045+germanz@users.noreply.github.com>
Our bots will check whether your PR can be …
=> MINOR: Schedule view update to render POI icon

@here/harp-webtile-datasource/lib/HereWebTileDataSource.ts, @here/harp-webtile-datasource/test/HereWebTileDataSourceTest.ts
storageLevelOffset was not passed through to DataSource correctly.
=> MINOR: Relates to #2019, fix broken storageLevelOffset

@here/harp-examples/webpack.config.js, @here/harp.gl/webpack.config.js
Webpack fails trying to store a cache shared by multiple configurations.
Now each configuration has its own cache. …
=> HARP-13809: Fix Webpack caching for multiple configurations.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts
This change makes the default value of the `constantHeight`
property of the `extruded-polygon` technique depend on the tile's
storage level. That is, unless explictly set, the projection scaling
factor used to convert meters to world units is applied
only if the tile's level is greater than or equal to 12. This
change of behavior may results to a different height when rendering
extruded polygons coming from tiles at low storage levels but it
will avoid possible artifacts when rendering large polygons.
=> HARP-13812: Tune the default value of extruded-polygon's constantHeight.

@here/harp-geometry/lib/ClipPolygon.ts, @here/harp-geometry/test/ClipPolygonTest.ts, @here/harp-vectortile-datasource/lib/Ring.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts
This change modifies `clipPolygon` to store the state of the clipping
in the vertices. Also, this change modifies the clipping planes
to ensure that vertices on the edge are not marked as "clipped".
=> HARP-11233: Store the clipping states in the ring vertices

@here/harp-map-controls/lib/MapControls.ts, @here/harp-mapview/lib/Utils.ts
- Improve the epsilon used when comparing the dot product.
- When the tilt animation has finished, a final check is done to see if the targeted tilt is reached, and if not, we apply the delta needed to reach the desired tilt.
=> HARP-13852 Increase precision, otherwise tilt is too inaccurate

@here/harp-mapview/lib/MapObjectAdapter.ts, @here/harp-mapview/lib/MapView.ts, @here/harp-mapview/lib/MapViewPoints.ts, @here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/PickingRaycaster.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/test/AddGroundPlaneTest.ts, @here/harp-mapview/test/PickingRaycasterTest.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts, @here/harp-vectortile-datasource/test/MapViewPickingTest.ts, @here/harp-vectortile-datasource/test/resources/geoJsonData.ts
Raycaster must specify a threshold distance between ray and line.
=> HARP-13901: Fix THREE.Line and THREE.LineSegments picking.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
The zoom level passed to StyleSetEvaluator through the environment is not accurate for mixed LOD, the actual zoom level might be higher, and therefore an object will not be rendered even when the current zoom level is within the style zoom range.
However this might be sometimes the desired behaviour, for example when skipping decoding of extruded buildings in far tiles.
To accomodate the two behaviours, StyleSetEvaluator now only filters by min/maxZoomLevel if they are fixed values or static expressions.
Partially fixes MAPSJS-2831.
=> MINOR: Do not filter styles by minZoomLevel/maxZoomLevel in StyleSetEvaluator if they're dynamic expressions

@here/harp-vectortile-datasource/lib/OmvUtils.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts, test/rendering/GeoJsonDataRendering.ts
There is a precision issue and the clipping fails to correctly
classify the inner rings of clipped polygons at level 2.
=> HARP-13229: Fix possible precision issues when converting coords from world to local space

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-mapview-decoder/lib/GeoJsonTiler.ts, @here/harp-mapview-decoder/test/GeoJsonTilerTest.ts, @here/harp-mapview/lib/DataSource.ts, @here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/geometry/TileDataAccessor.ts, @here/harp-mapview/lib/poi/PoiBuilder.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts, @here/harp-vectortile-datasource/lib/adapters/geojson-vt/GeoJsonVtDataAdapter.ts, @here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts, @here/harp-vectortile-datasource/test/FakeOmvFeatureFilter.ts, @here/harp-vectortile-datasource/test/GeoJsonDataAdapterTest.ts, @here/harp-vectortile-datasource/test/GeoJsonVtDataAdapterTest.ts, @here/harp-vectortile-datasource/test/MockGeometryProcessor.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts
So far feature ids were expected to be numbers, therefore original feature ids coming from geojson data were ignored.
=> HARP-11013: Support GeoJson feature ids

@here/harp-olp-utils/lib/OlpCopyrightProvider.ts, @here/harp-olp-utils/lib/OlpDataProvider.ts, @here/harp-olp-utils/package.json
The classes `OlpClientSettings` and `HRN` in
`@here/olp-sdk-dataservice-read` will be removed
in the next release.
Those classes copied to the `@here/olp-sdk-core`.
This CR adapts the code according to future changes.
=> Stopping use deprecated code.

@here/harp-transfer-manager/src/TransferManager.ts, @here/harp-transfer-manager/test/TransferManagerTest.ts, @here/harp-vectortile-datasource/lib/OmvRestClient.ts
Thie change handles HTTP error messages which in the case of the OMV client can be due to various reasons:
- **401** Invalid credentials
- **404** No data, when for example the supported ``maxDataLevel`` is exceeded
Error messages obtained from the server are logged for easy troubleshooting. Furthermore, in the case of HTTP client error codes, we do not attempt to fetch the data again.
=> HARP-13952: Handle error states, like 404 in OmvRestClient

@here/harp-datasource-protocol/lib/TechniqueParams.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts
Client code might want to decided per-object whether mercator scaling factor should be applied (e.g. based on object latitude span or extrusion height).
=> MINOR: Make constantHeight technique property dynamic.

test/rendering/GeoJsonFeaturesRendering.ts
The test renderes two stroked semi-transparent boxes.
=> HARP-13243: Add IBCT test for enclosed stroked polygon features.

@here/harp-datasource-protocol/lib/GeoJsonDataType.ts, @here/harp-mapview-decoder/lib/GeoJsonTiler.ts, @here/harp-mapview-decoder/test/GeoJsonTilerTest.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/lib/text/TextElementsRendererOptions.ts
- Remove default label limit of 10K labels.
- Make GeojsonTiler generate feature ids when input data doesn't have them. This makes label deduplication and replacement much faster.
=> HARP-14257: Fix geojson stress example

@here/harp-mapview/lib/MapView.ts, @here/harp-vectortile-datasource/lib/VectorTileDataSource.ts, @here/harp-vectortile-datasource/test/OmvDataSourceTest.ts
Caught error might be just a string from a rejected promise.
=> MINOR: Fix error message on Datasource connection failure.

@here/harp-examples/src/real-time-shadows.ts, @here/harp-mapview/lib/geometry/AddGroundPlane.ts, @here/harp-mapview/test/AddGroundPlaneTest.ts, @here/harp-webtile-datasource/lib/WebTileLoader.ts, @here/harp-webtile-datasource/test/WebTileLoaderTest.ts
=> Enable shadows on WebTiles

@here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementBuilder.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/PickListenerTest.ts, @here/harp-mapview/test/TextElementBuilderTest.ts, README.md
Signed-off-by: German Zargaryan <2526045+germanz@users.noreply.github.com> …
=> MINOR: Adds dataSourceName reference in the PickResult

@here/harp-webtile-datasource/lib/WebTileLoader.ts, test/rendering/WebTileDataRendering.ts
=> HARP-14502: Fixes blue-ish webtiles on sphere

.github/workflows/ci.yaml
The following PR https://github.com/heremaps/harp.gl/pull/2145 removed the dependency from Travis CI, hence it is set up again using GitHub Actions.
=> Re-setup code coverage using GitHub Actions

@here/harp-datasource-protocol/lib/DecodedTile.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts, test/rendering/ScreenSpaceRenderingTests.ts, test/rendering/utils/ThemeBuilder.ts
Screen space elements use world coordinates (other elements use local tile coordinates). Their coordinates were decoded into single precision buffers, and therefore placement was not accurate for high zoom levels.
=> HARP-14465: Fix world coordinates precision for screen space techniques

@here/harp-text-canvas/lib/rendering/TextGeometry.ts, @here/harp-text-canvas/test/TextGeometryTest.ts
Old picking data was still used after clearing the geometry from a text layer.
This means that text that's not visible anymore could still be picked. In this example:
https://rendering.pages.gitlab.in.here.com/harp.gl/sdk/verity-examples/index.html#markers_dynamic.html
If you place a marker and then remove it (with Ctrl click), you still get as pick result the removed marker text.
=> MINOR: Fix text canvas picking.

@here/harp-examples/src/markers_dynamic.ts, @here/harp-map-controls/lib/LongPressHandler.ts, @here/harp-map-controls/test/LongPressHandlerTest.ts
=> MINOR: Fix input handling in dynamic markers example.

www/webpack.config.js
the previous url was behind a CDN and it would be cached, this meant that
it would sometimes return the old version and this would overwrite the
updated releases.json from the publish package action, hence we rely
on the up to date link
If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember …
=> MINOR: Fix broken releases

@here/harp-geometry/lib/ClipPolygon.ts, @here/harp-vectortile-datasource/lib/Ring.ts, @here/harp-vectortile-datasource/lib/VectorTileDataEmitter.ts, @here/harp-vectortile-datasource/lib/adapters/geojson-vt/GeoJsonVtDataAdapter.ts, @here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts, @here/harp-vectortile-datasource/lib/adapters/omv/OmvDataAdapter.ts, @here/harp-vectortile-datasource/test/GeoJsonVtDataAdapterTest.ts, @here/harp-vectortile-datasource/test/OmvDataAdapterTest.ts, @here/harp-vectortile-datasource/test/OmvDecodedTileEmitterTest.ts
Currently, in master, all the ring geometries forming multi-polygons are processed and put into a single polygon composed of an interleaved list of exterior/interior rings. The winding (determined in function of the sign of the area) of these rings is used to differentiate exteriors from interiors.
This layout besides being not fully compliant to the MVT spec, see [Polygon Geometry Type](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4344-polygon-geometry-type), creates confusion in case clipped rings result in a `0` area.
This PR proposes to process and create polygon objects in accordance with the MVT spec while stopping relying on the winding.
=> HARP-14633: island geometry disappears on certain zoom level

@here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/test/PickHandlerTest.ts
This PR fixes picking at polygonal outlines for the `fill` technique.
Before the fix:
* Expected result: when an outline is picked, all resulting objects (belonging to a given datasource) contain `.featureId` and `.userData` derived from original GeoJSON features that were used to render both `Mesh` and `LineSegments` objects.
* Actual result: while for `Mesh` objects results are correct (underlying polygons), for `LineSegments` it's always the first polygon of a given tile that's being returned instead. E.g. on the screenshot above, "Piemonte" is returned instead of "Abruzzo".
Reason:
`PickHandler` was comparing `.faceIndex` with `undefined` when deciding whether to take `.faceIndex * 3` or `.index` in order to recognise the proper feature. In case of `LineSegments` it's `null`, as …
=> HARP-14417: fix picking of polygon outlines

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
Dynamic technique keys are generated using JSON.stringify on the
technique property values. However ArrayBuffers (used for texture
properties) return always the same string "{}", causing a collision
in the dynamic technique cache between different techniques.
This is solved by converting array buffers to arrays before stringifying.
=> MAPSJS-2783: Fix dynamic technique keys for array buffers.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts
Instead of stringifying the array buffers, an id is assigned to them
and used as part of the technique key.
=> MAPSJS-2783: Faster creation of keys for techniques with dynamic array buffer properties.

@here/harp-examples/decoder/custom_decoder.ts, @here/harp-examples/src/tile_dependencies.ts, @here/harp-mapview/lib/VisibleTileSet.ts
HARP-14678 Fix issue with morton codes being stored as 32 bit
The tile dependency example wasn't working with two separate data sources because the morton code was stored in a Float32Array, which doesn't have enough precision and caused issues. This change stores the row, column and level separately and then in the decoder, the mortonCode is computed and stored as a `number`, which has more accuracy that a 32 bit float.
=> HARP-14678 Fix tile dependencies not working

@here/harp-examples/src/threejs_raycast.ts
=> HARP-15031 Move boxes up by half the height to ensure that they sit on top of the buildings

@here/harp-mapview/lib/MapMaterialAdapter.ts
=> HARP-15480 Fix colors not being set correctly on custom materials

@here/generator-harp.gl/package.json, @here/generator-harp.gl/test/test.js, yarn.lock
=> HARP-15180 Upgrading yeoman because it has a transitive dependency (axios) which is out of date

yarn.lock
- Manual update for agent-base [6.0.1 -> 6.0.2]
- Bumb version for https-proxy-agent (pupetteer dependency) [^4.0.0 -> ^5.0.0]
Signed-off-by: Shubham Bhatia <39002688+drametoid@users.noreply.github.com>
Our bots will check whether your PR can be directly integrated into the mainline. We have …
=> MINOR: Fixes #2208 - ERR_INVALID_PROTOCOL while installing behind http proxy

@here/harp-webtile-datasource/lib/WebTileLoader.ts
=> HARP-15773 WebTileDataSource avoids the TileGeometryLoader

@here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/test/PickHandlerTest.ts
Signed-off-by: Daniele Bacarella <daniele.bacarella@here.com> …
=> HARP-14862: add tile coordinates to pick results

@here/harp-mapview-decoder/test/TileGeometryLoaderTest.ts, @here/harp-mapview/lib/DecodedTileHelpers.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/geometry/TileGeometryLoader.ts, @here/harp-mapview/test/DecodedTileHelpersTest.ts, @here/harp-mapview/test/TileGeometryCreatorTest.ts, test/rendering/StylingTest.ts
TileGeometryCreator.createAllGeometries() returns now a promise that
is resolved when all textures in the tile are uploaded in GPU. This ensures that all textures are rendered on frame complete event.
=> HARP-15210: Wait for texture GPU upload on TileGeometryCreator.

@here/harp-datasource-protocol/lib/TechniqueParams.ts, test/rendering/GeoJsonDataRendering.ts, test/rendering/utils/GeoJsonTest.ts
All except Point allowed dynamic size properties, so adjust
PointTechniqueParams to also allow dynamic properties for size.
Tested and worked, seems only the typing needed a small update.
=> Allow dynamic properties for size

@here/harp-mapview/lib/ThemeLoader.ts, @here/harp-mapview/test/ThemeLoaderTest.ts
The specified allows theme extends to work properly when multiple images (textures) are specified.
=> MINOR: Fix theme extends to respect multiple image textures

@here/harp-mapview/lib/ClipPlanesEvaluator.ts
From now on, the default evaluator, TiltViewClipPlanesEvaluator, should be used for top-down views as well.
=> MINOR: Deprecate TopViewClipPlanesEvaluator.

@here/harp-vectortile-datasource/lib/adapters/geojson/GeoJsonDataAdapter.ts, @here/harp-vectortile-datasource/test/GeoJsonDataAdapterTest.ts
The change allows inherited adapters to specify a custom GeoJSON layer name instead of standard ``geojson``.
=> MINOR: Support custom layer name in GeoJSON data adapter

@here/harp-mapview/lib/PickHandler.ts, @here/harp-mapview/lib/PickListener.ts, @here/harp-mapview/lib/geometry/TileGeometryCreator.ts, @here/harp-mapview/lib/poi/PoiManager.ts, @here/harp-mapview/lib/text/TextElement.ts, @here/harp-mapview/lib/text/TextElementBuilder.ts, @here/harp-mapview/lib/text/TextElementsRenderer.ts, @here/harp-mapview/test/PickListenerTest.ts, @here/harp-mapview/test/TextElementBuilderTest.ts
Signed-off-by: Oleksii Markhovskyi <oleksii.markhovskyi@here.com>
This PR introduces a higher tie-breaker (comparator criterion) for sorting picking results - by `.dataSourceOrder`. It defaults those values to zeros to ensure consistent sorting.
It also orders zero-distance results (screen-space objects, e.g. labels) higher, because those are currently rendered on top.
Sorting by `.distance` and `.renderOrder` remains in place for results with same `.dataSourceOrder`.
=> HARP-14531: sort picking results by 'dataSourceOrder'

@here/harp-mapview/lib/ClipPlanesEvaluator.ts, @here/harp-mapview/test/ClipPlanesEvaluatorTest.ts
- Extract some functions out of evaluator class into a private namespace.
- Small documentation changes.
- Minor code rearrangements.
No behaviour changes.
=> ClipPlanesEvaluator cleanup

@here/harp-geoutils/lib/tiling/TileKeyUtils.ts, @here/harp-geoutils/test/TileKeyTest.ts, @here/harp-geoutils/test/TileKeyUtilsTest.ts, @here/harp-mapview/lib/FrustumIntersection.ts, @here/harp-mapview/lib/Tile.ts, @here/harp-mapview/lib/Utils.ts, @here/harp-mapview/lib/VisibleTileSet.ts, @here/harp-mapview/lib/geometry/Object3DUtils.ts, @here/harp-mapview/test/Object3DUtilsTest.ts, @here/harp-mapview/test/TextElementsRendererTestFixture.ts, @here/harp-mapview/test/UtilsTest.ts, @here/harp-mapview/test/VisibleTileSetTest.ts, @here/harp-utils/index-common.ts, @here/harp-utils/lib/DOMUtils.ts
Remove from MapViewUtils functions that are unrelated to MapView.
MapViewUtils namespace has now only functions related to view transformations, camera setup, and view bounds computation.
=> MAPSJS-2660: Clean MapViewUtils namespace

@here/harp-theme-tools/src/cli-build-theme.ts
Signed-off-by: Andrii Heonia <andrii.heonia@here.com>
=> MAPSJS-3047, Split theme to stable and unstable parts

@here/harp-lines/lib/Lines.ts, @here/harp-mapview/lib/geometry/SolidLineMesh.ts, @here/harp-mapview/lib/geometry/TileGeometry.ts, @here/harp-mapview/test/SolidLineMeshTest.ts, @here/harp-materials/lib/CirclePointsMaterial.ts, @here/harp-materials/lib/HighPrecisionLineMaterial.ts, @here/harp-materials/lib/HighPrecisionPointMaterial.ts, @here/harp-materials/lib/SolidLineMaterial.ts, @here/harp-materials/test/CirclePointsMaterialTest.ts
Shader compilation errors using Metal through ANGLE compatibility layer were caused by the uniform names 'diffuse' and 'bitangent'.
=> HARP-17373: Fix shader compilation in Safari 15 on MacOS Monterrey.

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts
=> Minor style fix

@here/harp-datasource-protocol/lib/StyleSetEvaluator.ts, @here/harp-datasource-protocol/test/StyleSetEvaluatorTest.ts, @here/harp-vectortile-datasource/lib/VectorTileDecoder.ts, @here/harp-vectortile-datasource/test/VectorTileDataProcessorTest.ts
=> HARP-17877: Fixes Style Evaluator expression for cached step expression
